<?php

// autoload-classmap.php @generated by Strauss

$trustedlogin = dirname(__FILE__);

return array(
   'GravityView\Psr\Log\LoggerAwareTrait' => $trustedlogin . '/psr/log/Psr/Log/LoggerAwareTrait.php',
   'GravityView\Psr\Log\LoggerInterface' => $trustedlogin . '/psr/log/Psr/Log/LoggerInterface.php',
   'GravityView\Psr\Log\LoggerAwareInterface' => $trustedlogin . '/psr/log/Psr/Log/LoggerAwareInterface.php',
   'GravityView\Psr\Log\NullLogger' => $trustedlogin . '/psr/log/Psr/Log/NullLogger.php',
   'GravityView\Psr\Log\LogLevel' => $trustedlogin . '/psr/log/Psr/Log/LogLevel.php',
   'GravityView\Psr\Log\Test\LoggerInterfaceTest' => $trustedlogin . '/psr/log/Psr/Log/Test/LoggerInterfaceTest.php',
   'GravityView\Psr\Log\Test\TestLogger' => $trustedlogin . '/psr/log/Psr/Log/Test/TestLogger.php',
   'GravityView\Psr\Log\Test\DummyTest' => $trustedlogin . '/psr/log/Psr/Log/Test/DummyTest.php',
   'GravityView\Psr\Log\AbstractLogger' => $trustedlogin . '/psr/log/Psr/Log/AbstractLogger.php',
   'GravityView\Psr\Log\LoggerTrait' => $trustedlogin . '/psr/log/Psr/Log/LoggerTrait.php',
   'GravityView\Psr\Log\InvalidArgumentException' => $trustedlogin . '/psr/log/Psr/Log/InvalidArgumentException.php',
   'GravityView\Katzgrau\KLogger\Logger' => $trustedlogin . '/katzgrau/klogger/src/Logger.php',
   'GravityView\TrustedLogin\Admin' => $trustedlogin . '/trustedlogin/client/src/Admin.php',
   'GravityView\TrustedLogin\Remote' => $trustedlogin . '/trustedlogin/client/src/Remote.php',
   'GravityView\TrustedLogin\Endpoint' => $trustedlogin . '/trustedlogin/client/src/Endpoint.php',
   'GravityView\TrustedLogin\SiteAccess' => $trustedlogin . '/trustedlogin/client/src/SiteAccess.php',
   'GravityView\TrustedLogin\Envelope' => $trustedlogin . '/trustedlogin/client/src/Envelope.php',
   'GravityView\TrustedLogin\Encryption' => $trustedlogin . '/trustedlogin/client/src/Encryption.php',
   'GravityView\TrustedLogin\Config' => $trustedlogin . '/trustedlogin/client/src/Config.php',
   'GravityView\TrustedLogin\SecurityChecks' => $trustedlogin . '/trustedlogin/client/src/SecurityChecks.php',
   'GravityView\TrustedLogin\SupportUser' => $trustedlogin . '/trustedlogin/client/src/SupportUser.php',
   'GravityView\TrustedLogin\Client' => $trustedlogin . '/trustedlogin/client/src/Client.php',
   'GravityView\TrustedLogin\Cron' => $trustedlogin . '/trustedlogin/client/src/Cron.php',
   'GravityView\TrustedLogin\SupportRole' => $trustedlogin . '/trustedlogin/client/src/SupportRole.php',
   'GravityView\TrustedLogin\Ajax' => $trustedlogin . '/trustedlogin/client/src/Ajax.php',
   'GravityView\TrustedLogin\Logging' => $trustedlogin . '/trustedlogin/client/src/Logging.php',
);