GravityView: GravityView_Admin_Metaboxes Class Reference
GravityView_Admin_Metaboxes Class Reference
Register and render the admin metaboxes for GravityView.
Public Member Functions
__construct ()
__return_low ()
Return 'low' as the status for metabox priority.
add_other_metaboxes ()
hide_wordpress_seo_metabox ($options=array())
Modify the WordPress SEO plugin's metabox behavior.
initialize ()
Add WordPress hooks.
register_metaboxes ()
remove_other_metaboxes ()
Modify WooThemes metabox behavior.
render_data_source_metabox ($post)
Render html for 'select form' metabox.
render_select_template_metabox ($post)
Render html for 'select template' metabox.
render_shortcode_hint ()
Render shortcode hint in the Publish metabox.
render_view_configuration_metabox ($post)
Render html for 'View Configuration' metabox.
render_view_settings_metabox ($post)
Render html View General Settings.
settings_metabox_render ($post)
Render the View Settings metabox.
Static Public Member Functions
static render_merge_tags_scripts ($curr_form)
Generate the script tags necessary for the Gravity Forms Merge Tag picker to work.
Static Public Attributes
static $metaboxes_dir
Private Member Functions
add_settings_metabox_tabs ()
Add default tabs to the Settings metabox.
get_data_source_header ($post_id)
Generate the title for Data Source, which includes the Action Links once configured.
Detailed Description
Register and render the admin metaboxes for GravityView.
Definition at line 6 of file class-gravityview-admin-metaboxes.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 13 of file class-gravityview-admin-metaboxes.php.
References GRAVITYVIEW_DIR, initialize(), and GravityView_Compatibility\is_valid().
Member Function Documentation
__return_low ()
Return 'low' as the status for metabox priority.
Returns
string 'low'
Definition at line 54 of file class-gravityview-admin-metaboxes.php.
add_other_metaboxes ()
Definition at line 338 of file class-gravityview-admin-metaboxes.php.
References gravityview_is_admin_page().
add_settings_metabox_tabs () private
Add default tabs to the Settings metabox.
Since
1.8
Runs Filter:
gravityview/metaboxes/default Modify the default settings metabox tabs
Parameters
array $metaboxes
Since
1.8
Definition at line 109 of file class-gravityview-admin-metaboxes.php.
References GravityView_Metabox_Tabs\add().
Referenced by register_metaboxes().
get_data_source_header ($post_id) private
Generate the title for Data Source, which includes the Action Links once configured.
Since
1.8
Parameters
int $post_id ID of the current post
Returns
string "Data Source", plus links if any
Definition at line 166 of file class-gravityview-admin-metaboxes.php.
References $current_form, GravityView_Admin_Views\get_connected_form_links(), and gravityview_get_form_id().
Referenced by register_metaboxes().
hide_wordpress_seo_metabox ($options = array())
Modify the WordPress SEO plugin's metabox behavior.
Only show when the View has been configured.
Parameters
array $options WP SEO options array
Returns
array Modified
Definition at line 357 of file class-gravityview-admin-metaboxes.php.
initialize ()
Add WordPress hooks.
Since
1.7.2
Definition at line 31 of file class-gravityview-admin-metaboxes.php.
Referenced by __construct().
register_metaboxes ()
Definition at line 58 of file class-gravityview-admin-metaboxes.php.
References $post, add_settings_metabox_tabs(), and get_data_source_header().
remove_other_metaboxes ()
Modify WooThemes metabox behavior.
Only show when the View has been configured.
Returns
void
Definition at line 310 of file class-gravityview-admin-metaboxes.php.
References gravityview_is_admin_page().
render_data_source_metabox ($post)
Render html for 'select form' metabox.
public
Parameters
object $post
Returns
void
Definition at line 187 of file class-gravityview-admin-metaboxes.php.
References $post.
static render_merge_tags_scripts ($curr_form) static
Generate the script tags necessary for the Gravity Forms Merge Tag picker to work.
Parameters
mixed $curr_form Form ID
Returns
null|string Merge tags html; NULL if $curr_form isn't defined.
Definition at line 215 of file class-gravityview-admin-metaboxes.php.
References $curr_form, $output, and gravityview_get_form().
render_select_template_metabox ($post)
Render html for 'select template' metabox.
public
Parameters
object $post
Returns
void
Definition at line 204 of file class-gravityview-admin-metaboxes.php.
render_shortcode_hint ()
Render shortcode hint in the Publish metabox.
public
Parameters
object $post
Returns
void
Definition at line 291 of file class-gravityview-admin-metaboxes.php.
References $post, gravityview_get_directory_fields(), and gravityview_is_admin_page().
render_view_configuration_metabox ($post)
Render html for 'View Configuration' metabox.
public
Parameters
mixed $post
Returns
void
Definition at line 250 of file class-gravityview-admin-metaboxes.php.
References $curr_form, $post, gravityview_get_form_id(), and gravityview_get_template_id().
render_view_settings_metabox ($post)
Render html View General Settings.
public
Parameters
object $post
Returns
void
Definition at line 273 of file class-gravityview-admin-metaboxes.php.
References $current_settings, $post, and gravityview_get_template_settings().
settings_metabox_render ($post)
Render the View Settings metabox.
Since
1.8
Parameters
WP_Post $post
Parameters
WP_Post $post
WP_Post $post
Definition at line 87 of file class-gravityview-admin-metaboxes.php.
References $post, and GravityView_Metabox_Tabs\get_all().
Field Documentation
$metaboxes_dir static
Definition at line 8 of file class-gravityview-admin-metaboxes.php.
The documentation for this class was generated from the following file:
class-gravityview-admin-metaboxes.php