GravityView: class-api.php File Reference
class-api.php File Reference
Data Structures
class GravityView_API
Namespaces
GravityView
GPL2+
Functions
_gravityview_strip_subdomain ($string_maybe_has_subdomain)
Do a very basic match for second-level TLD domains, like .co.uk
gravityview_after ()
gravityview_back_link ()
Generate HTML for the back link from single entry view.
gravityview_before ()
gravityview_convert_value_to_term_list ($value, $taxonomy= 'post_tag')
Take a passed CSV of terms and generate a linked list of terms.
gravityview_field_output ($passed_args)
Output field based on a certain html markup.
gravityview_footer ()
gravityview_format_link ($value=null)
Convert a whole link into a shorter link for display.
gravityview_get_context ()
GravityView_View $gravityview_view
gravityview_get_current_view_data ($view_id=0)
Get data for a specific view.
gravityview_get_current_views ()
Get all views processed so far for the current page load.
gravityview_get_field_value ($entry, $field_id, $display_value)
Handle getting values for complex Gravity Forms fields.
gravityview_get_files_array ($value, $gv_class= '')
Return an array of files prepared for output.
gravityview_get_map_link ($address)
Generate a mapping link from an address.
gravityview_get_the_term_list ($post_id, $link=true, $taxonomy= 'post_tag')
Get the links for post_tags and post_category output based on post ID.
gravityview_get_view_id ()
Get the current View ID being rendered.
gravityview_header ()
gv_class ($field, $form=NULL, $entry=array())
gv_container_class ($class= '')
gv_directory_link ($post=NULL, $add_pagination=true)
gv_entry_link ($entry, $post_id=NULL)
gv_label ($field, $entry=NULL)
gv_no_results ($wpautop=true)
gv_selected ($value, $current, $echo=true, $type= 'selected')
Similar to the WordPress selected(), checked(), and disabled() functions, except it allows arrays to be passed as current value.
gv_value ($entry, $field)
Function Documentation
_gravityview_strip_subdomain ($string_maybe_has_subdomain)
Do a very basic match for second-level TLD domains, like .co.uk
Ideally, we'd use https://github.com/jeremykendall/php-domain-parser to check for this, but it's too much work for such a basic functionality. Maybe if it's needed more in the future. So instead, we use Basic matching regex.
Parameters
string $domain Domain to check if it's a TLD or subdomain
Returns
string Extracted domain if it has a subdomain
Definition at line 884 of file class-api.php.
Referenced by gravityview_format_link().
gravityview_after ()
Runs Actions:
gravityview_after Append content to the View container <div>
Parameters
int $view_id The ID of the View being displayed
Definition at line 1071 of file class-api.php.
References gravityview_get_view_id().
gravityview_back_link ()
Generate HTML for the back link from single entry view.
Since
1.0.1
Returns
string|null If no GV post exists, null. Otherwise, HTML string of back link.
Runs Filter:
gravityview_go_back_label Modify the back link text
Since
1.0.9
Parameters
string $label Existing label text
Definition at line 751 of file class-api.php.
References $gravityview_view, $href, $label, GravityView_View\getInstance(), gravityview_get_link(), and gv_directory_link().
gravityview_before ()
Runs Actions:
gravityview_before Display content before a View. Used to render widget areas. Rendered outside the View container <div>
Parameters
int $view_id The ID of the View being displayed
Definition at line 1047 of file class-api.php.
References gravityview_get_view_id().
gravityview_convert_value_to_term_list ($value, $taxonomy = 'post_tag')
Take a passed CSV of terms and generate a linked list of terms.
Gravity Forms passes categories as "Name:ID" so we handle that using the ID, which is more accurate than checking the name, which is more likely to change.
Parameters
string $value Existing value
string $taxonomy Type of term (post_tag or category)
Returns
string CSV of linked terms
Definition at line 814 of file class-api.php.
References $output, $value, and gravityview_get_link().
gravityview_field_output ($passed_args)
Output field based on a certain html markup.
markup - string to be used on a sprintf statement. Use: {{label}} - field label {{value}} - entry field value {{class}} - field class
wpautop - true will filter the value using wpautop function
Since
1.1.5
Parameters
array $passed_args Associative array with field data. field and form are required.
Returns
string Field output. If empty value and hide empty is true, return empty.
Runs Filter:
gravityview/field_output/args Modify the args before generation begins
Since
1.7
Parameters
array $args Associative array; field and form is required.
array $passed_args Original associative array with field data. field and form are required.
Create the Context for replacing.
Since
1.11
Runs Filter:
gravityview/field_output/pre_html Allow Pre filtering of the HTML
Since
1.11
Parameters
string $markup The HTML for the markup
array $args All args for the field output
Runs Filter:
gravityview/field_output/open_tag Modify the opening tags for the template content placeholders
Since
1.11
Parameters
string $open_tag Open tag for template content placeholders. Default: {{
Runs Filter:
gravityview/field_output/close_tag Modify the closing tags for the template content placeholders
Since
1.11
Parameters
string $close_tag Close tag for template content placeholders. Default: }}
Loop through each of the tags to replace and replace both {{tag}} and {{ tag }} with the values
Since
1.11
gravityview/field_output/context/{$tag} Allow users to filter content on context
Since
1.11
Parameters
string $value The content to be shown instead of the {{tag}} placeholder
array $args Arguments passed to the function
Todo:
Depricate gravityview_field_output
Runs Filter:
gravityview/field_output/html Modify field HTML output
Parameters
string $html Existing HTML output
array $args Arguments passed to the function
Definition at line 1195 of file class-api.php.
References $html, $value, GravityView_API\field_html_attr_id(), GravityView_API\field_width(), gv_class(), gv_label(), and gv_value().
gravityview_footer ()
Runs Actions:
gravityview_after Display content after a View. Used to render footer widget areas. Rendered outside the View container <div>
Parameters
int $view_id The ID of the View being displayed
Definition at line 1063 of file class-api.php.
References gravityview_get_view_id().
gravityview_format_link ($value = null)
Convert a whole link into a shorter link for display.
Since
1.1
Parameters
string $value Existing URL
Returns
string If parse_url doesn't find a 'host', returns original value. Otherwise, returns formatted link.
Runs Filter:
gravityview_anchor_text_striphttp Strip scheme from the displayed URL?
Since
1.5.1
Parameters
boolean $enable Whether to strip the scheme. Return false to show scheme. (default: true)
If true: http://example.com => example.com
Runs Filter:
gravityview_anchor_text_stripwww Strip www from the domain?
Since
1.5.1
Parameters
boolean $enable Whether to strip www. Return false to show www. (default: true)
If true: www.example.com => example.com
Runs Filter:
gravityview_anchor_text_nosubdomain Strip subdomains from the domain?
Since
1.5.1
Parameters
boolean $enable Whether to strip subdomains. Return false to show subdomains. (default: true)
If true: http://demo.example.com => example.com
If false: http://demo.example.com => demo.example.com
Runs Filter:
gravityview_anchor_text_rootonly Display link path going only to the base directory, not a sub-directory or file?
Since
1.5.1
Parameters
boolean $enable Whether to enable "root only". Return false to show full path. (default: true)
If true: http://example.com/sub/directory/page.html => example.com
If false: http://example.com/sub/directory/page.html => example.com/sub/directory/page.html
Runs Filter:
gravityview_anchor_text_noquerystring Strip the query string from the end of the URL?
Since
1.5.1
Parameters
boolean $enable Whether to enable "root only". Return false to show full path. (default: true)
If true: http://example.com/?query=example => example.com
Definition at line 902 of file class-api.php.
References $value, and _gravityview_strip_subdomain().
Referenced by GravityView_API_Test\test_gravityview_format_link_DEFAULT(), GravityView_API_Test\test_gravityview_format_link_WHEN_FILTER_NOQUERYSTRING_FALSE(), GravityView_API_Test\test_gravityview_format_link_WHEN_FILTER_NOSUBDOMAIN_FALSE(), and GravityView_API_Test\test_gravityview_format_link_WHEN_FILTER_ROOTONLY_FALSE().
gravityview_get_context ()
GravityView_View $gravityview_view
Returns
string View context "directory", "single", or "edit"
Runs Filter:
gravityview_is_edit_entry Whether we're currently on the Edit Entry screen
The Edit Entry functionality overrides this value.
Parameters
boolean $is_edit_entry
Definition at line 1093 of file class-api.php.
References GravityView_View\getInstance(), and GravityView_frontend\is_single_entry().
Referenced by GravityView_Field_FileUpload\get_files_array(), GVCommon\matches_operation(), GravityView_frontend\render_view(), and GravityView_View\render_widget_hooks().
gravityview_get_current_view_data ($view_id = 0)
Get data for a specific view.
See also
GravityView_View_Data::get_view()
Returns
array View data with id, view_id, form_id, template_id, atts, fields, widgets, form keys.
Definition at line 1032 of file class-api.php.
References $view_id, and GravityView_frontend\getInstance().
Referenced by GravityView_Delete_Entry\check_user_cap_delete_entry(), and GravityView_View\render_widget_hooks().
gravityview_get_current_views ()
Get all views processed so far for the current page load.
See also
GravityView_View_Data::add_view()
Returns
array Array of View data, each View data with id, view_id, form_id, template_id, atts, fields, widgets, form keys.
Definition at line 1003 of file class-api.php.
References GravityView_frontend\getInstance().
Referenced by GravityView_API_Test\test_gravityview_get_current_views().
gravityview_get_field_value ($entry, $field_id, $display_value)
Handle getting values for complex Gravity Forms fields.
If the field is complex, like a product, the field ID, for example, 11, won't exist. Instead, it will be 11.1, 11.2, and 11.3. This handles being passed 11 and 11.2 with the same function.
Since
1.0.4
Parameters
array $entry GF entry array
string $field_id [description]
string $display_value The value generated by Gravity Forms
Returns
string Value
Definition at line 788 of file class-api.php.
gravityview_get_files_array ($value, $gv_class = '')
Return an array of files prepared for output.
Wrapper for GravityView_Field_FileUpload::get_files_array()
Processes files by file type and generates unique output for each.
Returns array for each file, with the following keys:
file_path => The file path of the file, with a line break html => The file output HTML formatted
See also
GravityView_Field_FileUpload::get_files_array()
Since
1.2
Parameters
string $value Field value passed by Gravity Forms. String of file URL, or serialized string of file URL array
string $gv_class Field class to add to the output HTML
Returns
array Array of file output, with file_path and html keys (see comments above)
Definition at line 1133 of file class-api.php.
References $value, GravityView_Field_FileUpload\get_files_array(), and GRAVITYVIEW_DIR.
gravityview_get_map_link ($address)
Generate a mapping link from an address.
The address should be plain text with new line (\n) or <br /> line breaks separating sections
Todo:
use GF's field get_export_value() instead
Read how to modify the link string $address Address string URL of link to map of address
Runs Filter:
gravityview_map_link Modify the map link generated. You can use a different mapping service, for example.
Parameters
[in,out] string $link Map link
[in] string $address Address to generate link for
[in] string $url URL generated by the function
Definition at line 1157 of file class-api.php.
References $link_text, $url, and gravityview_get_link().
gravityview_get_the_term_list ($post_id, $link = true, $taxonomy = 'post_tag')
Get the links for post_tags and post_category output based on post ID.
Parameters
int $post_id The ID of the post
boolean $link Add links or no?
string $taxonomy Taxonomy of term to fetch.
Returns
string String with terms
Definition at line 865 of file class-api.php.
References $output.
gravityview_get_view_id ()
Get the current View ID being rendered.
GravityView_View $gravityview_view
Returns
string View context "directory" or "single"
Definition at line 1085 of file class-api.php.
References GravityView_View\getInstance().
Referenced by GravityView_API\entry_link(), GravityView_Delete_Entry\get_delete_link(), gravityview_after(), gravityview_before(), gravityview_footer(), and gravityview_header().
gravityview_header ()
Runs Actions:
gravityview_header Prepend content to the View container <div>
Parameters
int $view_id The ID of the View being displayed
Definition at line 1055 of file class-api.php.
References gravityview_get_view_id().
gv_class ($field, $form = NULL, $entry = array())
Definition at line 700 of file class-api.php.
References $field, and GravityView_API\field_class().
Referenced by gravityview_field_output().
gv_container_class ($class = '')
Definition at line 704 of file class-api.php.
References $class, GravityView_View\getInstance(), and gravityview_sanitize_html_class().
gv_directory_link ($post = NULL, $add_pagination = true)
Definition at line 734 of file class-api.php.
References $post, and GravityView_API\directory_link().
Referenced by gravityview_back_link(), and GravityView_Widget_Page_Links\render_frontend().
gv_entry_link ($entry, $post_id = NULL)
Definition at line 738 of file class-api.php.
References GravityView_API\entry_link().
Referenced by GravityView_Edit_Entry\get_edit_link().
gv_label ($field, $entry = NULL)
Definition at line 696 of file class-api.php.
References $field, and GravityView_API\field_label().
Referenced by gravityview_field_output().
gv_no_results ($wpautop = true)
Definition at line 742 of file class-api.php.
References GravityView_API\no_results().
Referenced by GravityView_Entry_List\__construct().
gv_selected ($value, $current, $echo = true, $type = 'selected')
Similar to the WordPress selected(), checked(), and disabled() functions, except it allows arrays to be passed as current value.
Todo:
Move to helper-functions.php
See also
selected() WordPress core function
Parameters
string $value One of the values to compare
mixed $current (true) The other value to compare if not just true
bool $echo Whether to echo or just return the string
string $type The type of checked|selected|disabled we are doing
Returns
string html attribute or empty string
Definition at line 1346 of file class-api.php.
References $output, and $value.
gv_value ($entry, $field)
Runs Filter:
gravityview_empty_value What to display when a field is empty
Parameters
string $value (empty string)
Definition at line 719 of file class-api.php.
References $field, $value, and GravityView_API\field_value().
Referenced by gravityview_field_output().