GravityView: GravityView_Widget_Search Class Reference
GravityView_Widget_Search Class Reference
Public Member Functions
__construct ()
add_datepicker_js_dependency ($js_dependencies)
Require the datepicker script for the frontend GV script.
add_no_permalink_fields ($search_fields, $object, $widget_args=array())
Display hidden fields to add support for sites using Default permalink structure.
add_template_path ($file_paths)
Include this extension templates path.
enqueue_datepicker ()
Enqueue the datepicker script.
filter_entries ($search_criteria)
— Frontend —
prepare_field_filter ($key, $value)
Prepare the field filters to GFAPI.
register_no_conflict ($required)
Add admin script to the whitelist.
Public Member Functions inherited from GravityView_Widget
add_shortcode ($run_on_singular=true)
Add $this->shortcode_name shortcode to output self::render_frontend()
assign_widget_options ($options=array(), $template= '', $widget= '')
Assign template specific field options.
get_setting ($key)
Get a setting by the setting key.
get_settings ()
Get the widget settings.
get_widget_id ()
maybe_do_shortcode ($text, $widget=NULL)
Do shortcode if the Widget's shortcode exists.
pre_render_frontend ()
General validations when rendering the widget.
register_widget ($widgets)
Register widget to become available in admin.
render_frontend ($widget_args, $content= '', $context= '')
Frontend logic.
render_shortcode ($atts, $content= '', $context= '')
Static Public Member Functions
static get_date_field_format (GF_Field_Date $field)
Get the Field Format form GravityForms.
static get_formatted_date ($value= '', $format= 'Y-m-d')
Format a date value.
static get_search_class ($custom_class= '')
Get the search class for a search form.
static get_search_form_action ()
Calculate the search form action.
static get_search_input_types ($id= '', $field_type=null)
Assign an input type according to the form field type.
static get_searchable_fields ()
Ajax Returns the form fields (only the searchable ones)
static getInstance ()
static render_searchable_fields ($form_id=null, $current= '')
Generates html for the available Search Fields dropdown.
static the_clear_search_button ()
Output the Clear Search Results button.
Static Public Attributes
static $file
static $instance
Private Member Functions
get_field_label ($field, $form_field)
Get the label for a search form field.
get_search_filter_details ($field)
Prepare search fields to frontend render with other details (label, field type, searched values)
Static Private Member Functions
static get_created_by_choices ()
Calculate the search choices for the users.
static get_post_categories_choices ()
Private Attributes
$search_filters = array()
Additional Inherited Members
Protected Member Functions inherited from GravityView_Widget
get_default_settings ()
Define general widget settings.
Protected Attributes inherited from GravityView_Widget
$defaults = array()
$settings = array()
$shortcode_name
$widget_description = ''
$widget_id = ''
$widget_label = ''
$widget_subtitle = ''
Detailed Description
Definition at line 16 of file class-search-widget.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 23 of file class-search-widget.php.
References GravityView_Widget\$settings.
Member Function Documentation
add_datepicker_js_dependency ($js_dependencies)
Require the datepicker script for the frontend GV script.
Parameters
array $js_dependencies Array of existing required scripts for the fe-views.js script
Definition at line 930 of file class-search-widget.php.
add_no_permalink_fields ($search_fields, $object, $widget_args = array())
Display hidden fields to add support for sites using Default permalink structure.
Since
1.8
Returns
array Search fields, modified if not using permalinks
WP_Rewrite $wp_rewrite
Definition at line 285 of file class-search-widget.php.
References $value, and gravityview_get_permalink_query_args().
add_template_path ($file_paths)
Include this extension templates path.
Parameters
array $file_paths List of template paths ordered
Definition at line 606 of file class-search-widget.php.
enqueue_datepicker ()
Enqueue the datepicker script.
It sets the $gravityview->datepicker_class parameter
Todo:
Use own datepicker javascript instead of GF datepicker.js - that way, we can localize the settings and not require the changeMonth and changeYear pickers.
Returns
void
Runs Filter:
gravityview_search_datepicker_class
Modify the CSS class for the datepicker, used by the CSS class is used by Gravity Forms' javascript to determine the format for the date picker. The gv-datepicker class is required by the GravityView datepicker javascript.
Parameters
string $css_class CSS class to use. Default: gv-datepicker datepicker mdy
Options are:
mdy (mm/dd/yyyy)
dmy (dd/mm/yyyy)
dmy_dash (dd-mm-yyyy)
dmy_dot (dd.mm.yyyy)
ymp_slash (yyyy/mm/dd)
ymd_dash (yyyy-mm-dd)
ymp_dot (yyyy.mm.dd)
Definition at line 983 of file class-search-widget.php.
References $gravityview_view, and GravityView_View\getInstance().
filter_entries ($search_criteria)
— Frontend —
Calculate the search criteria to filter entries
Parameters
array $search_criteria
Returns
array
Runs Filter:
gravityview_date_created_adjust_timezone Whether to adjust the timezone for entries.
date_created is stored in UTC format. Convert search date into UTC (also used on templates/fields/date_created.php)
Since
1.12
Parameters
[in,out] boolean $adjust_tz Default: true
[in] string $context Where the filter is being called from. search in this case.
Runs Filter:
gravityview/search/mode Set the Search Mode (all or any)
Since
1.5.1
Parameters
[in,out] string $mode Search mode (any vs all)
Definition at line 327 of file class-search-widget.php.
References $value, and prepare_field_filter().
static get_created_by_choices () static private
Calculate the search choices for the users.
Since
1.8
Returns
array Array of user choices (value = ID, text = display name)
filter gravityview/get_users/search_widget
See also
::get_users
Definition at line 862 of file class-search-widget.php.
References GVCommon\get_users().
static get_date_field_format (GF_Field_Date $field) static
Get the Field Format form GravityForms.
Parameters
GF_Field_Date $field The field object
Since
1.10
Returns
string Format of the date in the database
Definition at line 566 of file class-search-widget.php.
References $format.
get_field_label ($field, $form_field) private
Get the label for a search form field.
Parameters
array $field Field setting as sent by the GV configuration - has field and input (input type) keys
array $form_field Form field data, as fetched by gravityview_get_field()
Returns
string Label for the search form
Modify the label for a search field
Parameters
string $label Existing label text
array $form_field Gravity Forms field array, as returned by GFFormsModel::get_field()
Definition at line 768 of file class-search-widget.php.
References $field, $label, and $value.
Referenced by get_search_filter_details().
static get_formatted_date ($value = '', $format = 'Y-m-d') static
Format a date value.
Parameters
string $value Date value input
string $format Wanted formatted date
Returns
string
Definition at line 592 of file class-search-widget.php.
References $format, and $value.
static get_post_categories_choices () static private
Definition at line 882 of file class-search-widget.php.
static get_search_class ($custom_class = '') static
Get the search class for a search form.
Since
1.5.4
Returns
string Sanitized CSS class for the search form
Modify the CSS class for the search form
Parameters
string $search_class The CSS class for the search form
Definition at line 723 of file class-search-widget.php.
References $gravityview_view, GravityView_frontend\getInstance(), GravityView_View\getInstance(), and gravityview_sanitize_html_class().
get_search_filter_details ($field) private
Prepare search fields to frontend render with other details (label, field type, searched values)
Parameters
type $field
Returns
type
Definition at line 806 of file class-search-widget.php.
References $field, $gravityview_view, $name, $value, get_field_label(), GravityView_View\getInstance(), and gravityview_get_field().
static get_search_form_action () static
Calculate the search form action.
Since
1.6
Returns
string
Definition at line 752 of file class-search-widget.php.
References $gravityview_view, $url, and GravityView_View\getInstance().
static get_search_input_types ($id = '', $field_type = null) static
Assign an input type according to the form field type.
See also
admin-search-widget.js
Parameters
int $id Gravity Forms field ID
string $field_type Gravity Forms field type
Returns
string GV field search input type ('multi', 'boolean', 'select', 'date', 'text')
Runs Filter:
gravityview/extension/search/input_type Modify the search form input type based on field type
Parameters
string $input_type Assign an input type according to the form field type
string $field_type Gravity Forms field type
Since
1.2
Definition at line 246 of file class-search-widget.php.
Referenced by GravityView_Migrate\get_search_fields().
static get_searchable_fields () static
Ajax Returns the form fields (only the searchable ones)
public
Returns
void
Definition at line 162 of file class-search-widget.php.
References gravityview_get_form_id(), and GravityView_Ajax\pre_get_form_fields().
static getInstance () static
Returns
GravityView_Widget_Search
Definition at line 78 of file class-search-widget.php.
References GravityView_Widget_Search.
Referenced by GravityView_Search_WP_Widget\__construct(), and GravityView_Search_WP_Widget\widget().
prepare_field_filter ($key, $value)
Prepare the field filters to GFAPI.
The type post_category, multiselect and checkbox support multi-select search - each value needs to be separated in an independent filter so we could apply the ANY search mode.
Format searched values
Parameters
string $key $_GET search key
string $value $_GET search value
Returns
array 1 or 2 deph levels
Definition at line 434 of file class-search-widget.php.
References $gravityview_view, $value, GravityView_View\getInstance(), and gravityview_get_field().
Referenced by filter_entries().
register_no_conflict ($required)
Add admin script to the whitelist.
Definition at line 150 of file class-search-widget.php.
static render_searchable_fields ($form_id = null, $current = '') static
Generates html for the available Search Fields dropdown.
Parameters
string $form_id
string $current (for future use)
Returns
string
Definition at line 196 of file class-search-widget.php.
References $field, $form_id, $output, and gravityview_get_form_fields().
static the_clear_search_button () static
Output the Clear Search Results button.
Since
1.5.4
Definition at line 912 of file class-search-widget.php.
References $gravityview_view, $url, GravityView_View\getInstance(), and gravityview_get_link().
Field Documentation
$file static
Definition at line 18 of file class-search-widget.php.
$instance static
Definition at line 19 of file class-search-widget.php.
$search_filters = array() private
Definition at line 21 of file class-search-widget.php.
The documentation for this class was generated from the following file:
class-search-widget.php