GravityView: GravityView_View Class Reference
GravityView_View Class Reference
If this file is called directly, abort.
Public Member Functions
__construct ($atts=array())
Construct the view object.
__get ($name)
Magic Method: Instead of throwing an error when a variable isn't set, return null.
add_id_specific_templates ($templates, $slug, $name)
Enable overrides of GravityView templates on a granular basis.
clearCurrentEntry ()
Clear the current entry after all entries in the loop have been displayed.
getAtts ($key=NULL)
getBackLinkLabel ()
getContext ()
getCurrentEntry ()
Return the current entry.
getCurrentField ($key=NULL)
getCurrentFieldSetting ($key)
getEntries ()
getField ($key)
getFields ($key=null)
getForm ()
getFormId ()
getPaging ()
getPostId ()
getSorting ()
getTemplatePartName ()
getTemplatePartSlug ()
getTotalEntries ()
getViewId ()
isHideUntilSearched ()
locate_template ($template_names, $load=false, $require_once=true)
In order to improve lookup times, we store located templates in a local array.
render ($slug, $name, $require_once=true)
render_widget_hooks ($view_id)
setAtts ($atts)
setBackLinkLabel ($back_link_label)
setContext ($context)
setCurrentEntry ($current_entry)
setCurrentField ($passed_field)
setCurrentFieldSetting ($key, $value)
setEntries ($entries)
setField ($key, $value)
setFields ($fields)
setForm ($form)
setFormId ($form_id)
setHideUntilSearched ($hide_until_searched)
setPaging ($paging)
setPostId ($post_id)
setSorting ($sorting)
setTemplatePartName ($template_part_name)
setTemplatePartSlug ($template_part_slug)
setTotalEntries ($total_entries)
setViewId ($view_id)
Public Member Functions inherited from Gamajo_Template_Loader
get_template_part ($slug, $name=null, $load=true)
Retrieve a template part.
locate_template ($template_names, $load=false, $require_once=true)
Retrieve the name of the highest priority template file that exists.
Static Public Member Functions
static getInstance ($passed_post=NULL)
Data Fields
$view_id = NULL
Static Public Attributes
static $instance = NULL
Protected Attributes
$_current_entry = array()
$_current_field = array()
$atts = array()
$back_link_label = ''
$context = 'directory'
$entries = array()
$fields = array()
$filter_prefix = 'gravityview'
$form = NULL
$form_id = NULL
$hide_until_searched = false
$located_templates = array()
$paging = array()
$plugin_directory = GRAVITYVIEW_DIR
$post_id = NULL
$sorting = array()
$template_part_name = ''
$template_part_slug = ''
$theme_template_directory = 'gravityview'
$total_entries = 0
Protected Attributes inherited from Gamajo_Template_Loader
$filter_prefix = 'your_plugin'
Prefix for filter names.
$plugin_directory = YOUR_PLUGIN_DIR
Reference to the root directory path of this plugin.
$plugin_template_directory = 'templates'
Directory name where templates are found in this plugin.
$theme_template_directory = 'your-plugin'
Directory name where custom templates for this plugin should be found in the theme.
Additional Inherited Members
Protected Member Functions inherited from Gamajo_Template_Loader
get_template_file_names ($slug, $name)
Given a slug and optional name, create the file names of templates.
get_template_paths ()
Return a list of paths to check for template locations.
get_templates_dir ()
Return the path to the templates directory in this plugin.
Detailed Description
If this file is called directly, abort.
Definition at line 23 of file class-template.php.
Constructor & Destructor Documentation
__construct ($atts = array())
Construct the view object.
Parameters
array $atts Associative array to set the data of
Clear the current entry after the loop is done
Since
1.7.3
Definition at line 148 of file class-template.php.
References $atts, and $value.
Member Function Documentation
__get ($name)
Magic Method: Instead of throwing an error when a variable isn't set, return null.
Parameters
string $name Key for the data retrieval.
Returns
mixed|null The stored data.
Definition at line 692 of file class-template.php.
References $name.
add_id_specific_templates ($templates, $slug, $name)
Enable overrides of GravityView templates on a granular basis.
The loading order is:
view-[View ID]-table-footer.php
form-[Form ID]-table-footer.php
page-[ID of post or page where view is embedded]-table-footer.php
table-footer.php
See also
Gamajo_Template_Loader::get_template_file_names() Where the filter is
Parameters
array $templates Existing list of templates.
[type] $slug [description]
[type] $name [description]
Definition at line 715 of file class-template.php.
References $name, $templates, getFormId(), getPostId(), and getViewId().
clearCurrentEntry ()
Clear the current entry after all entries in the loop have been displayed.
Since
1.7.3
Returns
void
Definition at line 575 of file class-template.php.
getAtts ($key = NULL)
Parameters
string | null $key The key to a specific field in the fields array
Returns
array|mixed|null If $key is set and field exists at $key, return that. If not set, return NULL. Otherwise, return array of fields.
Definition at line 255 of file class-template.php.
References $atts.
getBackLinkLabel ()
Returns
string
Definition at line 489 of file class-template.php.
References $back_link_label, getCurrentEntry(), getForm(), and GravityView_API\replace_variables().
getContext ()
Returns
string
Definition at line 305 of file class-template.php.
References $context.
Referenced by getCurrentEntry().
getCurrentEntry ()
Return the current entry.
If in the loop, the current entry. If single entry, the currently viewed entry.
Returns
array
Definition at line 551 of file class-template.php.
References $_current_entry, $entries, getContext(), and getEntries().
Referenced by getBackLinkLabel().
getCurrentField ($key = NULL)
Parameters
string | null $key The key to a specific attribute of the current field
Returns
array|mixed|null If $key is set and attribute exists at $key, return that. If not set, return NULL. Otherwise, return current field array
Definition at line 203 of file class-template.php.
References $_current_field.
Referenced by getCurrentFieldSetting(), and setCurrentField().
getCurrentFieldSetting ($key)
Definition at line 223 of file class-template.php.
References getCurrentField().
getEntries ()
Returns
array
Definition at line 392 of file class-template.php.
References $entries.
Referenced by getCurrentEntry().
getField ($key)
Parameters
string $key The key to a specific field in the fields array
Returns
array|mixed|null If $key is set and field exists at $key, return that. If not set, return NULL. Otherwise, return array of fields.
Definition at line 342 of file class-template.php.
getFields ($key = null)
Parameters
string | null $key The key to a specific field in the fields array
Returns
array|mixed|null If $key is set and field exists at $key, return that. If not set, return NULL. Otherwise, return array of fields.
Definition at line 320 of file class-template.php.
References $fields.
getForm ()
Returns
array
Definition at line 277 of file class-template.php.
References $form.
Referenced by getBackLinkLabel().
getFormId ()
Returns
int
Definition at line 378 of file class-template.php.
References $form_id.
Referenced by add_id_specific_templates().
static getInstance ($passed_post = NULL) static
Parameters
null $passed_post
Returns
GravityView_View
Definition at line 190 of file class-template.php.
Referenced by GravityView_frontend\add_columns_sort_links(), GravityView_Delete_Entry\check_user_cap_delete_entry(), GravityView_Edit_Entry\check_user_cap_edit_entry(), GravityView_API\directory_link(), GravityView_Widget_Search\enqueue_datepicker(), GravityView_API\field_class(), GravityView_API\field_html_attr_id(), GravityView_API\field_label(), GravityView_API\field_value(), GravityView_Field_FileUpload\get_files_array(), GravityView_Entry_List\get_output(), GravityView_Widget_Search\get_search_class(), GravityView_Widget_Search\get_search_filter_details(), GravityView_Widget_Search\get_search_form_action(), GravityView_Shortcode\get_view_detail(), gravityview_back_link(), gravityview_get_context(), gravityview_get_view_id(), gv_container_class(), GravityView_API\no_results(), GravityView_Widget_Poll\pre_render_frontend(), GravityView_Widget\pre_render_frontend(), GravityView_Widget_Search\prepare_field_filter(), GravityView_Edit_Entry_Render\print_scripts(), GravityView_Widget_Page_Links\render_frontend(), GravityView_Widget_Pagination_Info\render_frontend(), GravityView_Widget_Poll\render_frontend(), GravityView_Delete_Entry\set_entry(), GravityView_Edit_Entry_Render\setup_vars(), GravityView_Delete_Entry_Shortcode\shortcode(), GravityView_Edit_Entry_Shortcode\shortcode(), GravityView_Widget_Search\the_clear_search_button(), GravityView_frontend\updateViewSorting(), and GravityView_Search_WP_Widget\widget().
getPaging ()
Returns
array
Definition at line 420 of file class-template.php.
References $paging.
getPostId ()
Returns
int|null
Definition at line 291 of file class-template.php.
References $post_id.
Referenced by add_id_specific_templates().
getSorting ()
Returns
array
Definition at line 475 of file class-template.php.
References $sorting.
getTemplatePartName ()
Returns
string
Definition at line 536 of file class-template.php.
References $template_part_name.
getTemplatePartSlug ()
Returns
string
Definition at line 522 of file class-template.php.
References $template_part_slug.
getTotalEntries ()
Returns
int
Definition at line 406 of file class-template.php.
References $total_entries.
getViewId ()
Returns
int
Definition at line 364 of file class-template.php.
References $view_id.
Referenced by add_id_specific_templates().
isHideUntilSearched ()
Returns
boolean
Definition at line 508 of file class-template.php.
References $hide_until_searched.
locate_template ($template_names, $load = false, $require_once = true)
In order to improve lookup times, we store located templates in a local array.
This improves performance by up to 1/2 second on a 250 entry View with 7 columns showing
See also
Gamajo_Template_Loader::locate_template()
Returns
null|string NULL: Template not found; String: path to template
Definition at line 664 of file class-template.php.
render ($slug, $name, $require_once = true)
Definition at line 740 of file class-template.php.
References $name, Gamajo_Template_Loader\get_template_part(), setTemplatePartName(), and setTemplatePartSlug().
render_widget_hooks ($view_id)
Parameters
$view_id
Definition at line 765 of file class-template.php.
References $view_id, GravityView_Plugin\get_default_widget_areas(), gravityview_get_context(), and gravityview_get_current_view_data().
setAtts ($atts)
Parameters
array $atts
Definition at line 270 of file class-template.php.
References $atts.
setBackLinkLabel ($back_link_label)
Parameters
string $back_link_label
Definition at line 501 of file class-template.php.
References $back_link_label.
setContext ($context)
Parameters
string $context
Definition at line 312 of file class-template.php.
References $context.
setCurrentEntry ($current_entry)
Parameters
array $current_entry
Returns
void
Definition at line 565 of file class-template.php.
setCurrentField ($passed_field)
Parameters
array $passed_field
Backward compatibility
Deprecated:
1.6.2
Definition at line 236 of file class-template.php.
References getCurrentField().
setCurrentFieldSetting ($key, $value)
Definition at line 215 of file class-template.php.
References $value.
setEntries ($entries)
Parameters
array $entries
Definition at line 399 of file class-template.php.
References $entries.
setField ($key, $value)
Parameters
string $key The key to a specific field in the fields array
mixed $value The value to set for the field
Definition at line 357 of file class-template.php.
References $value.
setFields ($fields)
Parameters
array $fields
Definition at line 334 of file class-template.php.
References $fields.
setForm ($form)
Parameters
array $form
Definition at line 284 of file class-template.php.
References $form.
setFormId ($form_id)
Parameters
int $form_id
Definition at line 385 of file class-template.php.
References $form_id.
setHideUntilSearched ($hide_until_searched)
Parameters
boolean $hide_until_searched
Definition at line 515 of file class-template.php.
References $hide_until_searched.
setPaging ($paging)
Parameters
array $paging
Definition at line 427 of file class-template.php.
References $paging.
setPostId ($post_id)
Parameters
int | null $post_id
Definition at line 298 of file class-template.php.
References $post_id.
setSorting ($sorting)
Parameters
array $sorting
Definition at line 482 of file class-template.php.
References $sorting.
setTemplatePartName ($template_part_name)
Parameters
string $template_part_name
Definition at line 543 of file class-template.php.
References $template_part_name.
Referenced by render().
setTemplatePartSlug ($template_part_slug)
Parameters
string $template_part_slug
Definition at line 529 of file class-template.php.
References $template_part_slug.
Referenced by render().
setTotalEntries ($total_entries)
Parameters
int $total_entries
Definition at line 413 of file class-template.php.
References $total_entries.
setViewId ($view_id)
Parameters
int $view_id
Definition at line 371 of file class-template.php.
References $view_id.
Field Documentation
$_current_entry = array() protected
Definition at line 132 of file class-template.php.
Referenced by getCurrentEntry().
$_current_field = array() protected
Definition at line 137 of file class-template.php.
Referenced by getCurrentField().
$atts = array() protected
Definition at line 95 of file class-template.php.
Referenced by __construct(), getAtts(), and setAtts().
$back_link_label = '' protected
Definition at line 110 of file class-template.php.
Referenced by getBackLinkLabel(), and setBackLinkLabel().
$context = 'directory' protected
Definition at line 80 of file class-template.php.
Referenced by getContext(), and setContext().
$entries = array() protected
Definition at line 100 of file class-template.php.
Referenced by getCurrentEntry(), getEntries(), and setEntries().
$fields = array() protected
Definition at line 75 of file class-template.php.
Referenced by getFields(), and setFields().
$filter_prefix = 'gravityview' protected
Definition at line 29 of file class-template.php.
$form = NULL protected
Definition at line 90 of file class-template.php.
Referenced by getForm(), and setForm().
array Gravity Forms form array at ID $form_id = NULL protected
Definition at line 64 of file class-template.php.
Referenced by getFormId(), and setFormId().
$hide_until_searched = false protected
Definition at line 126 of file class-template.php.
Referenced by isHideUntilSearched(), and setHideUntilSearched().
$instance = NULL static
Definition at line 142 of file class-template.php.
$located_templates = array() protected
Definition at line 47 of file class-template.php.
$paging = array() protected
Definition at line 115 of file class-template.php.
Referenced by getPaging(), and setPaging().
$plugin_directory = GRAVITYVIEW_DIR protected
Definition at line 41 of file class-template.php.
$post_id = NULL protected
Definition at line 85 of file class-template.php.
Referenced by getPostId(), and setPostId().
$sorting = array() protected
Definition at line 120 of file class-template.php.
Referenced by getSorting(), and setSorting().
$template_part_name = '' protected
Definition at line 59 of file class-template.php.
Referenced by getTemplatePartName(), and setTemplatePartName().
$template_part_slug = '' protected
Definition at line 53 of file class-template.php.
Referenced by getTemplatePartSlug(), and setTemplatePartSlug().
$theme_template_directory = 'gravityview' protected
Definition at line 35 of file class-template.php.
$total_entries = 0 protected
Definition at line 105 of file class-template.php.
Referenced by getTotalEntries(), and setTotalEntries().
$view_id = NULL
Definition at line 70 of file class-template.php.
Referenced by getViewId(), render_widget_hooks(), and setViewId().
The documentation for this class was generated from the following file:
class-template.php