GravityView: WXR_Parser_XML Class Reference
WXR_Parser_XML Class Reference
WXR Parser that makes use of the XML Parser PHP extension.
Public Member Functions
cdata ($parser, $cdata)
parse ($file)
tag_close ($parser, $tag)
tag_open ($parse, $tag, $attr)
Data Fields
$wp_sub_tags
$wp_tags
Detailed Description
WXR Parser that makes use of the XML Parser PHP extension.
Definition at line 243 of file parsers.php.
Member Function Documentation
cdata ($parser, $cdata)
Definition at line 323 of file parsers.php.
Referenced by parse(), and tag_close().
parse ($file)
Definition at line 258 of file parsers.php.
References cdata().
Referenced by WXR_Parser\parse().
tag_close ($parser, $tag)
Definition at line 330 of file parsers.php.
References cdata().
tag_open ($parse, $tag, $attr)
Definition at line 292 of file parsers.php.
Field Documentation
$wp_sub_tags
Initial value:
= array(
        'wp:comment_id', 'wp:comment_author', 'wp:comment_author_email', 'wp:comment_author_url',
        'wp:comment_author_IP', 'wp:comment_date', 'wp:comment_date_gmt', 'wp:comment_content',
        'wp:comment_approved', 'wp:comment_type', 'wp:comment_parent', 'wp:comment_user_id',
    )
Definition at line 252 of file parsers.php.
$wp_tags
Initial value:
= array(
        'wp:post_id', 'wp:post_date', 'wp:post_date_gmt', 'wp:comment_status', 'wp:ping_status', 'wp:attachment_url',
        'wp:status', 'wp:post_name', 'wp:post_parent', 'wp:menu_order', 'wp:post_type', 'wp:post_password',
        'wp:is_sticky', 'wp:term_id', 'wp:category_nicename', 'wp:category_parent', 'wp:cat_name', 'wp:category_description',
        'wp:tag_slug', 'wp:tag_name', 'wp:tag_description', 'wp:term_taxonomy', 'wp:term_parent',
        'wp:term_name', 'wp:term_description', 'wp:author_id', 'wp:author_login', 'wp:author_email', 'wp:author_display_name',
        'wp:author_first_name', 'wp:author_last_name',
    )
Definition at line 244 of file parsers.php.
The documentation for this class was generated from the following file:
parsers.php