GravityView: GV_License_Handler Class Reference
GV_License_Handler Class Reference
Public Member Functions
_get_edd_settings ($action= '', $license= '')
Generate the array of settings passed to the EDD license call.
get_license_message ($license_data)
Generate the status message displayed in the license field.
license_call ($array=array())
Perform the call to EDD based on the AJAX call or passed data.
settings_edd_license_activation ($field, $echo)
strings ($status=NULL)
Override the text used in the Redux Framework EDD field extension.
validate_license_key ($value, $field)
Static Public Member Functions
static get_instance (GravityView_Settings $GFAddOn)
Data Fields
const author = 'Katz Web Services, Inc.'
const name = 'GravityView'
const url = 'https://gravityview.co'
const version = GravityView_Plugin::version
Static Public Attributes
static $instance
Private Member Functions
__construct (GravityView_Settings $GFAddOn)
_license_get_remote_response ($data, $license= '')
Perform the call.
add_hooks ()
generate_license_box ($message, $class= '')
Generate the status message box HTML based on the current status.
license_call_update_settings ($license_data, $data)
Update the license after fetching it.
setup_edd ()
Include the EDD plugin updater class, if not exists.
Private Attributes
$Addon
$EDD_SL_Plugin_Updater
Detailed Description
Definition at line 3 of file class-gv-license-handler.php.
Constructor & Destructor Documentation
__construct (GravityView_Settings $GFAddOn) private
Definition at line 37 of file class-gv-license-handler.php.
References add_hooks(), and setup_edd().
Member Function Documentation
_get_edd_settings ($action = '', $license = '')
Generate the array of settings passed to the EDD license call.
Since
1.7.4
Parameters
string $action The action to send to edd, such as check_license
string $license The license key to have passed to EDD
Returns
array
Definition at line 139 of file class-gv-license-handler.php.
Referenced by _license_get_remote_response(), and setup_edd().
_license_get_remote_response ($data, $license = '') private
Perform the call.
Returns
array|WP_Error
Definition at line 165 of file class-gv-license-handler.php.
References $url, and _get_edd_settings().
Referenced by license_call().
add_hooks () private
Definition at line 46 of file class-gv-license-handler.php.
Referenced by __construct().
generate_license_box ($message, $class = '') private
Generate the status message box HTML based on the current status.
Since
1.7.4
Parameters
$message
string $class
Returns
string
Definition at line 229 of file class-gv-license-handler.php.
References $class, and $output.
Referenced by get_license_message().
static get_instance (GravityView_Settings $GFAddOn) static
Parameters
GravityView_Settings $GFAddOn
Returns
GV_License_Handler
Definition at line 30 of file class-gv-license-handler.php.
Referenced by GravityView_Settings\_load_license_handler().
get_license_message ($license_data)
Generate the status message displayed in the license field.
Since
1.7.4
Parameters
$license_data
Returns
string
Definition at line 205 of file class-gv-license-handler.php.
References $class, generate_license_box(), and strings().
Referenced by license_call(), and settings_edd_license_activation().
license_call ($array = array())
Perform the call to EDD based on the AJAX call or passed data.
Since
1.7.4
Parameters
array $array { string $license The license key string $edd_action The EDD action to perform, like check_license string $field_id The ID of the field to check boolean $update Whether to update plugin settings. Prevent updating the data by setting an update key to false string $format If object, return the object of the license data. Else, return the JSON-encoded object }
Returns
mixed|string|void
Definition at line 253 of file class-gv-license-handler.php.
References _license_get_remote_response(), get_license_message(), and license_call_update_settings().
Referenced by validate_license_key().
license_call_update_settings ($license_data, $data) private
Update the license after fetching it.
Parameters
object $license_data
Returns
void
Definition at line 308 of file class-gv-license-handler.php.
Referenced by license_call().
settings_edd_license_activation ($field, $echo)
Definition at line 50 of file class-gv-license-handler.php.
References $class, $field, get_license_message(), and GRAVITYVIEW_URL.
setup_edd () private
Include the EDD plugin updater class, if not exists.
Since
1.7.4
Returns
void
Definition at line 114 of file class-gv-license-handler.php.
References _get_edd_settings(), GRAVITYVIEW_DIR, and GRAVITYVIEW_FILE.
Referenced by __construct().
strings ($status = NULL)
Override the text used in the Redux Framework EDD field extension.
Parameters
array | null $status Status to get. If empty, get all strings.
Returns
array Modified array of content
Definition at line 325 of file class-gv-license-handler.php.
Referenced by get_license_message().
validate_license_key ($value, $field)
Definition at line 357 of file class-gv-license-handler.php.
References $field, $value, and license_call().
Field Documentation
$Addon private
Definition at line 8 of file class-gv-license-handler.php.
$EDD_SL_Plugin_Updater private
Definition at line 18 of file class-gv-license-handler.php.
$instance static
Definition at line 23 of file class-gv-license-handler.php.
const author = 'Katz Web Services, Inc.'
Definition at line 12 of file class-gv-license-handler.php.
const name = 'GravityView'
Definition at line 10 of file class-gv-license-handler.php.
const url = 'https://gravityview.co'
Definition at line 14 of file class-gv-license-handler.php.
const version = GravityView_Plugin::version
Definition at line 16 of file class-gv-license-handler.php.
The documentation for this class was generated from the following file:
class-gv-license-handler.php