GravityView: GravityView_Admin Class Reference
GravityView_Admin Class Reference
Public Member Functions
__construct ()
add_hooks ()
backend_actions ()
Function to launch admin objects.
no_conflict_scripts ()
Callback to eliminate any non-registered script.
no_conflict_styles ()
Callback to eliminate any non-registered style.
Static Public Member Functions
static add_notice ($notice=array())
Add a notice to be displayed in the admin.
static check_gravityforms ()
Check if Gravity Forms plugin is active and show notice if not.
static get_floaty ()
Get an image of our intrepid explorer friend.
static get_notices ()
Get admin notices.
static get_plugin_status ($location= '')
Check if specified plugin is active, inactive or not installed.
static is_admin_page ($hook= '', $page=NULL)
static plugin_action_links ($links)
Modify plugin action links at plugins screen.
Private Member Functions
add_script_dependencies ($registered, $scripts)
Add dependencies.
remove_conflicts (&$wp_objects, $required_objects, $type= 'scripts')
Remove any style or script non-registered in the no conflict mode.
Detailed Description
Definition at line 3 of file class-admin.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 5 of file class-admin.php.
References add_hooks().
Member Function Documentation
add_hooks ()
Since
1.7.5
Since
1.6
Definition at line 15 of file class-admin.php.
References GRAVITYVIEW_DIR, GRAVITYVIEW_FILE, and GravityView_Compatibility\is_valid().
Referenced by __construct().
static add_notice ($notice = array()) static
Add a notice to be displayed in the admin.
Deprecated:
since 1.12
Parameters
array $notice Array with class and message keys. The message is not escaped.
Definition at line 412 of file class-admin.php.
References GravityView_Admin_Notices\add_notice().
Referenced by GravityView_Settings\license_key_notice().
add_script_dependencies ($registered, $scripts) private
Add dependencies.
Parameters
[type] $registered [description]
[type] $scripts [description]
Definition at line 378 of file class-admin.php.
Referenced by remove_conflicts().
backend_actions ()
Function to launch admin objects.
public
Returns
void
Runs Actions:
gravityview_include_backend_actions Triggered after all GravityView admin files are loaded
Nice place to insert extensions' backend stuff
Definition at line 62 of file class-admin.php.
References GRAVITYVIEW_DIR.
static check_gravityforms () static
Check if Gravity Forms plugin is active and show notice if not.
Deprecated:
since 1.12
See also
GravityView_Compatibility::get_plugin_status()
Returns
boolean True: checks have been passed; GV is fine to run; False: checks have failed, don't continue loading
Definition at line 423 of file class-admin.php.
References GravityView_Compatibility\check_gravityforms().
static get_floaty () static
Get an image of our intrepid explorer friend.
Returns
string HTML image tag with floaty's cute mug on it
Definition at line 99 of file class-admin.php.
References gravityview_get_floaty().
Referenced by GravityView_Search_WP_Widget\form(), GravityView_oEmbed\generate_preview_notice(), GravityView_Post_Types\no_views_text(), and GravityView_oEmbed\render_admin().
static get_notices () static
Get admin notices.
Deprecated:
since 1.12
Returns
array
Definition at line 403 of file class-admin.php.
References GravityView_Admin_Notices\get_notices().
static get_plugin_status ($location = '') static
Check if specified plugin is active, inactive or not installed.
Deprecated:
since 1.12
See also
GravityView_Compatibility::get_plugin_status()
Returns
boolean|string True: plugin is active; False: plugin file doesn't exist at path; 'inactive' it's inactive
Definition at line 435 of file class-admin.php.
References GravityView_Compatibility\get_plugin_status().
static is_admin_page ($hook = '', $page = NULL) static
Runs Filter:
gravityview_is_admin_page Is the current admin page a GravityView-related page?
Parameters
[in,out] string | bool $is_page If false, no. If string, the name of the page (single, settings, or views)
[in] string $hook The name of the page to check against. Is passed to the method.
Definition at line 439 of file class-admin.php.
References $post.
Referenced by gravityview_is_admin_page().
no_conflict_scripts ()
Callback to eliminate any non-registered script.
Returns
void
Definition at line 182 of file class-admin.php.
References GravityView_Settings\getSetting(), gravityview_is_admin_page(), and remove_conflicts().
no_conflict_styles ()
Callback to eliminate any non-registered style.
Returns
void
Runs Actions:
gravityview_remove_conflicts_after Runs after no-conflict styles are removed. You can re-add styles here.
Definition at line 269 of file class-admin.php.
References GravityView_Settings\getSetting(), gravityview_is_admin_page(), and remove_conflicts().
static plugin_action_links ($links) static
Modify plugin action links at plugins screen.
public
Parameters
mixed $links
Returns
array Action links with Support included
Definition at line 88 of file class-admin.php.
remove_conflicts (& $wp_objects, $required_objects, $type = 'scripts') private
Remove any style or script non-registered in the no conflict mode.
Todo:
Move this to GravityView_Admin_Views
Parameters
WP_Dependencies $wp_objects Object of WP_Styles or WP_Scripts
array $required_objects List of registered script/style handles
string $type Either 'styles' or 'scripts'
Returns
void
Definition at line 346 of file class-admin.php.
References add_script_dependencies().
Referenced by no_conflict_scripts(), and no_conflict_styles().
The documentation for this class was generated from the following file:
class-admin.php