GravityView: GravityView_Edit_Entry_Shortcode Class Reference
GravityView_Edit_Entry_Shortcode Class Reference
Add [gv_edit_entry_link] shortcode.
Public Member Functions
__construct (GravityView_Edit_Entry $loader)
get_entry ($entry_id=0, $form_id=0)
Fetch the entry for the View.
load ()
shortcode ($atts=array(), $content= '', $context= 'gv_edit_entry')
Data Fields
$is_valid = NULL
Protected Attributes
$loader
Private Member Functions
get_edit_url ($entry, $view_id, $post_id, $settings=array())
Get the URL for the Edit Entry link.
Detailed Description
Add [gv_edit_entry_link] shortcode.
Definition at line 20 of file class-edit-entry-shortcode.php.
Constructor & Destructor Documentation
__construct (GravityView_Edit_Entry $loader)
Definition at line 34 of file class-edit-entry-shortcode.php.
References $loader.
Member Function Documentation
get_edit_url ($entry, $view_id, $post_id, $settings = array()) private
Get the URL for the Edit Entry link.
Parameters
array $entry GF Entry array
int $view_id View ID
int $post_id Optional: alternative base URL for embedded Views
Definition at line 85 of file class-edit-entry-shortcode.php.
References $href, $view_id, and GravityView_Edit_Entry\get_edit_link().
Referenced by shortcode().
get_entry ($entry_id = 0, $form_id = 0)
Fetch the entry for the View.
We need to use this instead of GFAPI::get_entry() because we want to also pass the Form ID to the get_entries() method.
Parameters
int $entry_id
int $form_id
Returns
array|bool False if no entry exists; Entry array if exists.
Definition at line 55 of file class-edit-entry-shortcode.php.
References $entries, and $form_id.
Referenced by shortcode().
load ()
Definition at line 38 of file class-edit-entry-shortcode.php.
shortcode ($atts = array(), $content = '', $context = 'gv_edit_entry')
Parameters
array $atts { string $view_id Define the ID for the View where the entry will string $entry_id ID of the entry to edit. If undefined, uses the current entry ID string $post_id ID of the base post or page to use for an embedded View string $link_atts Whether to open Edit Entry link in a new window or the same window string $return What should the shortcode return: link HTML (html) or the URL (url). Default: html string $field_values Parameters to pass in to the Edit Entry form to prefill data. Uses the same format as Gravity Forms "Allow field to be populated dynamically" {
See also
https://www.gravityhelp.com/documentation/article/allow-field-to-be-populated-dynamically/ } }
Parameters
string $content
string $context
Returns
string|void
Definition at line 114 of file class-edit-entry-shortcode.php.
References $content, $form_id, $href, $link_text, $view_id, GravityView_Edit_Entry\check_user_cap_edit_entry(), get_edit_url(), get_entry(), GravityView_frontend\getInstance(), GravityView_View\getInstance(), gravityview_get_form_id(), and gravityview_get_link().
Field Documentation
$is_valid = NULL
Definition at line 32 of file class-edit-entry-shortcode.php.
$loader protected
Definition at line 25 of file class-edit-entry-shortcode.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
class-edit-entry-shortcode.php