GravityView: GravityView_FieldType_textarea Class Reference
GravityView_FieldType_textarea Class Reference
textarea input type
Public Member Functions
render_input ($override_input=null)
render_option ()
Public Member Functions inherited from GravityView_FieldType
__construct ($name= '', $field=array(), $curr_value=NULL)
get_field_desc ()
Retrieve field description.
get_field_id ()
Build input id based on the name.
get_field_label ()
Retrieve field label.
get_field_left_label ()
Retrieve field left label.
get_label_class ()
Retrieve field label class.
get_tooltip ()
render_input ($override_input)
important! Override this class outputs the input html part
render_option ()
important! Override this class outputs the field option html
render_setting ($override_input=NULL)
important! Override this class if needed outputs the field setting html
show_merge_tags ()
Verify if field should have merge tags.
Additional Inherited Members
Static Public Member Functions inherited from GravityView_FieldType
static get_field_defaults ()
Returns the default details for a field option.
Protected Attributes inherited from GravityView_FieldType
$field
$name
$value
Detailed Description
textarea input type
Definition at line 5 of file type_textarea.php.
Member Function Documentation
render_input ($override_input = null)
Definition at line 21 of file type_textarea.php.
References $class, and GravityView_FieldType\show_merge_tags().
Referenced by render_option().
render_option ()
Definition at line 7 of file type_textarea.php.
References GravityView_FieldType\get_field_desc(), GravityView_FieldType\get_tooltip(), and render_input().
The documentation for this class was generated from the following file:
type_textarea.php