GravityView: class-admin.php File Reference
class-admin.php File Reference
Data Structures
class GravityView_Admin
Functions
gravityview_is_admin_page ($hook= '', $page=NULL)
Variables
new GravityView_Admin
Function Documentation
gravityview_is_admin_page ($hook = '', $page = NULL)
Definition at line 488 of file class-admin.php.
References GravityView_Admin\is_admin_page().
Referenced by GravityView_Admin_Metaboxes\add_other_metaboxes(), GravityView_Admin_Views\add_scripts_and_styles(), GravityView_Settings\license_key_notice(), GravityView_Admin\no_conflict_scripts(), GravityView_Admin\no_conflict_styles(), GravityView_Admin_Metaboxes\remove_other_metaboxes(), and GravityView_Admin_Metaboxes\render_shortcode_hint().
Variable Documentation
new GravityView_Admin
Definition at line 486 of file class-admin.php.