GravityView: GravityView_frontend Class Reference
GravityView_frontend Class Reference
Public Member Functions
add_columns_sort_links ($label= '', $field, $form)
Inject the sorting links on the table columns.
add_scripts_and_styles ()
Register styles and scripts.
comments_open ($open, $post_id)
Disable comments on GravityView post types.
get_context_view_id ()
Returns the the view_id context when page contains multiple embedded views or displaying single entry view.
getEntry ()
getGvOutputData ()
getPostId ()
getSingleEntry ()
is_field_sortable ($field_id= '', $form)
Checks if field (column) is sortable.
is_searching ()
Checks if the current View is presenting search results.
isGravityviewPostType ()
isPostHasShortcode ()
isSearch ()
parse_content ($wp=array())
Read the $post and process the View data inside.
set_context_view_id ($view_id=null)
Set the context view ID used when page contains multiple embedded views or displaying the single entry view.
set_entry_data ()
Set the entry.
setEntry ($entry)
Set the current entry.
setGvOutputData ($gv_output_data)
setIsGravityviewPostType ($is_gravityview_post_type)
setIsSearch ($is_search)
setPostHasShortcode ($post_has_shortcode)
setPostId ($post_id)
setSingleEntry ($single_entry)
Sets the single entry ID and also the entry.
single_entry_title ($title, $passed_post_id=null)
Filter the title for the single entry view.
Static Public Member Functions
static add_style ($template_id)
Add template extra style if exists.
static get_search_criteria ($args, $form_id)
Parse search criteria for a entries search.
static getInstance ()
Get the one true instantiated self.
insert_view_in_content ($content)
In case View post is called directly, insert the view in the post content.
static is_entry_approved ($entry, $args=array())
Check if a certain entry is approved.
static is_single_entry ()
Verify if user requested a single entry view.
static process_search_dates ($args, $search_criteria)
Process the start and end dates for a view - overrides values defined in shortcode (if needed)
static process_search_only_approved ($args, $search_criteria)
Process the approved only search criteria according to the View settings.
render_view ($passed_args)
Core function to render a View based on a set of arguments.
static updateViewSorting ($args, $form_id)
Updates the View sorting criteria.
Data Fields
$context_view_id = null
$entry = false
$gv_output_data = null
$is_gravityview_post_type = false
$is_search = false
$post_has_shortcode = false
$post_id = null
$single_entry = false
Static Public Attributes
static $instance
Private Member Functions
__construct ()
Class constructor, enforce Singleton pattern.
initialize ()
Static Private Member Functions
static _override_sorting_id_by_field_type ($sort_field_id, $form_id)
Override sorting per field.
Static Private Attributes
static $search_parameters = array('gv_search', 'gv_start', 'gv_end', 'gv_id', 'filter_*')
Detailed Description
Definition at line 15 of file class-frontend-views.php.
Constructor & Destructor Documentation
__construct () private
Class constructor, enforce Singleton pattern.
Definition at line 85 of file class-frontend-views.php.
Member Function Documentation
static _override_sorting_id_by_field_type ($sort_field_id, $form_id) static private
Override sorting per field.
Currently only modifies sorting ID when sorting by the full name. Sorts by first name. Use the gravityview/sorting/full-name filter to override.
Since
1.7.4
Parameters
int | string $sort_field_id Field used for sorting (id or 1.2)
int $form_id GF Form ID
Returns
string Possibly modified sorting ID
Override how to sort when sorting address
Since
1.8
Parameters
string $address_part street, street2, city, state, zip, or country (default: city)
string $sort_field_id Field used for sorting
int $form_id GF Form ID
Override how to sort when sorting full name.
Since
1.7.4
Parameters
string $name_part first or last (default: first)
string $sort_field_id Field used for sorting
int $form_id GF Form ID
Definition at line 1007 of file class-frontend-views.php.
References $form_id.
add_columns_sort_links ($label = '', $field, $form)
Inject the sorting links on the table columns.
Callback function for hook 'gravityview/template/field_label'
See also
GravityView_API::field_label() (in includes/class-api.php)
Since
1.7
Parameters
string $label Field label
array $field Field settings
Returns
string Field Label
Not a table-based template; don't add sort icons
Since
1.12
Definition at line 1209 of file class-frontend-views.php.
References $class, $field, $label, $url, GravityView_View\getInstance(), and is_field_sortable().
add_scripts_and_styles ()
Register styles and scripts.
public
Returns
void
Runs Filter:
gravity_view_lightbox_script Override the lightbox script to enqueue. Default: thickbox
Parameters
string $script_slug If you want to use a different lightbox script, return the name of it here.
Runs Filter:
gravity_view_lightbox_style Modify the lightbox CSS slug. Default: thickbox
Parameters
string $script_slug If you want to use a different lightbox script, return the name of its CSS file here.
Runs Filter:
gravityview_js_localization Modify the array passed to wp_localize_script()
Parameters
array $js_localization The data padded to the Javascript file
array $data View data array with View settings
Definition at line 1112 of file class-frontend-views.php.
References $post, $view_id, getGvOutputData(), GRAVITYVIEW_FILE, and GravityView_Plugin\version.
static add_style ($template_id) static
Add template extra style if exists.
Parameters
string $template_id
Definition at line 1182 of file class-frontend-views.php.
comments_open ($open, $post_id)
Disable comments on GravityView post types.
Parameters
boolean $open existing status
int $post_id Post ID
Returns
boolean
Runs Filter:
gravityview/comments_open Whether to set comments to open or closed.
Since
1.5.4
Parameters
boolean $open Open or closed status
int $post_id Post ID to set comment status for
Definition at line 462 of file class-frontend-views.php.
References isGravityviewPostType().
get_context_view_id ()
Returns the the view_id context when page contains multiple embedded views or displaying single entry view.
Since
1.5.4
Returns
string
Definition at line 259 of file class-frontend-views.php.
References $context_view_id.
Referenced by render_view(), and single_entry_title().
static get_search_criteria ($args, $form_id) static
Parse search criteria for a entries search.
array('search_field' => 1, // ID of the field 'search_value' => '', // Value of the field to search 'search_operator' => 'contains', // 'is', 'isnot', '>', '<', 'contains' 'show_only_approved' => 0 or 1 // Boolean)
Parameters
array $args Array of args
int $form_id Gravity Forms form ID
Returns
array Array of search parameters, formatted in Gravity Forms mode, using status key set to "active" by default, field_filters array with key, value and operator keys.
Definition at line 819 of file class-frontend-views.php.
References $form_id.
Referenced by GravityView_Admin_ApproveEntries\process_bulk_action().
getEntry ()
Returns
array
Definition at line 164 of file class-frontend-views.php.
References $entry.
Referenced by render_view(), and single_entry_title().
getGvOutputData ()
Returns
GravityView_View_Data
Definition at line 119 of file class-frontend-views.php.
References $gv_output_data.
Referenced by add_scripts_and_styles(), insert_view_in_content(), render_view(), set_context_view_id(), and single_entry_title().
static getInstance () static
Get the one true instantiated self.
Returns
GravityView_frontend
Definition at line 106 of file class-frontend-views.php.
Referenced by GravityView_Admin_Bar\__construct(), GVCommon\calculate_get_entries_criteria(), GravityView_API\directory_link(), GravityView_API\entry_link(), get_gravityview(), GravityView_Widget_Search\get_search_class(), gravityview_get_current_view_data(), gravityview_get_current_views(), GravityView_View_Data\parse_post_content(), GravityView_Shortcode\shortcode(), GravityView_Delete_Entry_Shortcode\shortcode(), GravityView_Edit_Entry_Shortcode\shortcode(), GravityView_API_Test\test_directory_link(), and GravityView_API_Test\test_gravityview_get_current_views().
getPostId ()
Returns
int
Definition at line 184 of file class-frontend-views.php.
References $post_id.
Referenced by parse_content(), and render_view().
getSingleEntry ()
Returns
bool|int
Definition at line 147 of file class-frontend-views.php.
References $single_entry.
Referenced by is_searching(), render_view(), and single_entry_title().
initialize () private
Definition at line 87 of file class-frontend-views.php.
insert_view_in_content ($content) static
In case View post is called directly, insert the view in the post content.
public
Parameters
mixed $content
Returns
string Add the View output into View CPT content
Since
1.7.4
Definition at line 420 of file class-frontend-views.php.
References $content, $view_id, getGvOutputData(), gravityview_get_form_id(), isGravityviewPostType(), and render_view().
static is_entry_approved ($entry, $args = array()) static
Check if a certain entry is approved.
If we pass the View settings ($args) it will check the 'show_only_approved' setting before checking the entry approved field, returning true if show_only_approved = false.
Since
1.7
Parameters
array $entry Entry object
array $args View settings (optional)
Returns
bool
Definition at line 789 of file class-frontend-views.php.
is_field_sortable ($field_id = '', $form)
Checks if field (column) is sortable.
Parameters
string $field Field settings
$form Gravity Forms form object
Since
1.7
Returns
bool True: Yes, field is sortable; False: not sortable
Modify what fields should never be sortable.
Since
1.7
Definition at line 1263 of file class-frontend-views.php.
Referenced by add_columns_sort_links().
is_searching ()
Checks if the current View is presenting search results.
Since
1.5.4
Returns
boolean True: Yes, it's a search; False: No, not a search.
Definition at line 311 of file class-frontend-views.php.
References getSingleEntry().
Referenced by parse_content().
static is_single_entry () static
Verify if user requested a single entry view.
Returns
boolean|string false if not, single entry slug if true
Modify the entry that is being displayed.
Definition at line 1084 of file class-frontend-views.php.
References $single_entry, and GravityView_Post_Types\get_entry_var_name().
Referenced by GravityView_Widget\add_shortcode(), GravityView_Edit_Entry_Render\get_entry(), gravityview_get_context(), and gravityview_is_single_entry().
isGravityviewPostType ()
Returns
boolean
Definition at line 212 of file class-frontend-views.php.
References $is_gravityview_post_type.
Referenced by comments_open(), insert_view_in_content(), parse_content(), and render_view().
isPostHasShortcode ()
Returns
boolean
Definition at line 198 of file class-frontend-views.php.
References $post_has_shortcode.
Referenced by render_view().
isSearch ()
Returns
boolean
Definition at line 133 of file class-frontend-views.php.
References $is_search.
Referenced by render_view().
parse_content ($wp = array())
Read the $post and process the View data inside.
Parameters
array $wp Passed in the wp hook. Not used.
Returns
void
Definition at line 268 of file class-frontend-views.php.
References $post, GravityView_View_Data\getInstance(), getPostId(), gravityview_has_shortcode_r(), GravityView_Plugin\is_admin(), is_searching(), isGravityviewPostType(), set_context_view_id(), setGvOutputData(), setIsGravityviewPostType(), setIsSearch(), setPostHasShortcode(), and setPostId().
Referenced by render_view().
static process_search_dates ($args, $search_criteria) static
Process the start and end dates for a view - overrides values defined in shortcode (if needed)
The start_date and end_date keys need to be in a format processable by GFFormsModel::get_date_range_where(), which uses () format.
You can set the start_date or end_date to any value allowed by strtotime(), including strings like "now" or "-1 year" or "-3 days".
Todo:
Compress into one
Parameters
array $args View settings
array $search_criteria Search being performed, if any
Returns
array Modified $search_criteria array
Definition at line 716 of file class-frontend-views.php.
static process_search_only_approved ($args, $search_criteria) static
Process the approved only search criteria according to the View settings.
Parameters
array $args View settings
array $search_criteria Search being performed, if any
Returns
array Modified $search_criteria array
Definition at line 763 of file class-frontend-views.php.
Referenced by GravityView_Recent_Entries_Widget\get_entries().
render_view ($passed_args) static
Core function to render a View based on a set of arguments.
public
Parameters
array $passed_args {
 Settings for rendering the View
 @type int $id View id
 @type int $page_size Number of entries to show per page
 @type string $sort_field Form field id to sort
 @type string $sort_direction Sorting direction ('ASC' or 'DESC')
 @type string $start_date - Ymd
 @type string $end_date - Ymd
 @type string $class - assign a html class to the view
 @type string $offset (optional) - This is the start point in the current data set (0 index based).
}
Returns
string|null HTML output of a View, NULL if View isn't found
Set globals for templating
Deprecated:
1.6.2
Disable fetching initial entries for views that don't need it (DataTables)
Hide View data until search is performed
Since
1.5.4
1.6
Definition at line 501 of file class-frontend-views.php.
References $entry, $gravityview_view, $output, $view_id, get_context_view_id(), getEntry(), getGvOutputData(), getPostId(), getSingleEntry(), gravityview_get_context(), isGravityviewPostType(), isPostHasShortcode(), isSearch(), and parse_content().
Referenced by insert_view_in_content().
set_context_view_id ($view_id = null)
Set the context view ID used when page contains multiple embedded views or displaying the single entry view.
Parameters
null $view_id
used on a has_multiple_views context
See also
GravityView_API::entry_link
GravityView_View_Data::getInstance()->has_multiple_views()
Definition at line 230 of file class-frontend-views.php.
References $view_id, and getGvOutputData().
Referenced by parse_content().
set_entry_data ()
Set the entry.
Definition at line 298 of file class-frontend-views.php.
References setEntry(), and setSingleEntry().
setEntry ($entry)
Set the current entry.
Parameters
array | int $entry Entry array or entry ID
Definition at line 172 of file class-frontend-views.php.
References $entry, and GVCommon\get_entry().
Referenced by set_entry_data().
setGvOutputData ($gv_output_data)
Parameters
GravityView_View_Data $gv_output_data
Definition at line 126 of file class-frontend-views.php.
References $gv_output_data.
Referenced by parse_content().
setIsGravityviewPostType ($is_gravityview_post_type)
Parameters
boolean $is_gravityview_post_type
Definition at line 219 of file class-frontend-views.php.
References $is_gravityview_post_type.
Referenced by parse_content().
setIsSearch ($is_search)
Parameters
boolean $is_search
Definition at line 140 of file class-frontend-views.php.
References $is_search.
Referenced by parse_content().
setPostHasShortcode ($post_has_shortcode)
Parameters
boolean $post_has_shortcode
Definition at line 205 of file class-frontend-views.php.
References $post_has_shortcode.
Referenced by parse_content().
setPostId ($post_id)
Parameters
int $post_id
Definition at line 191 of file class-frontend-views.php.
References $post_id.
Referenced by parse_content().
setSingleEntry ($single_entry)
Sets the single entry ID and also the entry.
Parameters
bool | int $single_entry
Definition at line 155 of file class-frontend-views.php.
References $single_entry.
Referenced by set_entry_data().
single_entry_title ($title, $passed_post_id = null)
Filter the title for the single entry view.
Parameters
string $title current title
int $passed_post_id Post ID
Returns
string (modified) title
Runs Filter:
gravityview/single/title/out_loop Apply the Single Entry Title filter outside the WordPress loop?
Parameters
boolean $in_the_loop Whether to apply the filter to the menu title and the meta tag <title> - outside the loop
array $entry Current entry
Definition at line 353 of file class-frontend-views.php.
References $post, $title, $view_id, get_context_view_id(), getEntry(), getGvOutputData(), getSingleEntry(), and GravityView_API\replace_variables().
static updateViewSorting ($args, $form_id) static
Updates the View sorting criteria.
Since
1.7
Parameters
$args View settings. Required to have sort_field and sort_direction keys
int $form_id The ID of the form used to sort
Returns
array $sorting Array with key, direction and is_numeric keys
Definition at line 971 of file class-frontend-views.php.
References $form_id, GravityView_View\getInstance(), and GVCommon\is_field_numeric().
Field Documentation
$context_view_id = null
Definition at line 60 of file class-frontend-views.php.
Referenced by get_context_view_id().
$entry = false
Definition at line 54 of file class-frontend-views.php.
Referenced by getEntry(), render_view(), and setEntry().
$gv_output_data = null
Definition at line 75 of file class-frontend-views.php.
Referenced by getGvOutputData(), and setGvOutputData().
$instance static
Definition at line 80 of file class-frontend-views.php.
$is_gravityview_post_type = false
Definition at line 29 of file class-frontend-views.php.
Referenced by isGravityviewPostType(), and setIsGravityviewPostType().
$is_search = false
Definition at line 67 of file class-frontend-views.php.
Referenced by isSearch(), and setIsSearch().
$post_has_shortcode = false
Definition at line 35 of file class-frontend-views.php.
Referenced by isPostHasShortcode(), and setPostHasShortcode().
$post_id = null
Definition at line 41 of file class-frontend-views.php.
Referenced by getPostId(), and setPostId().
$search_parameters = array('gv_search', 'gv_start', 'gv_end', 'gv_id', 'filter_*') static private
Definition at line 23 of file class-frontend-views.php.
$single_entry = false
Definition at line 48 of file class-frontend-views.php.
Referenced by getSingleEntry(), is_single_entry(), and setSingleEntry().
The documentation for this class was generated from the following file:
class-frontend-views.php