GravityView: GravityView_Render_Settings Class Reference
GravityView_Render_Settings Class Reference
Static Public Member Functions
static get_cap_choices ($template_id= '', $field_id= '', $context= '', $input_type= '')
Get capabilities options for GravityView.
static get_default_field_options ($field_type, $template_id, $field_id, $context, $input_type)
Get the default options for a standard field.
static load_type_class ($field=NULL)
Given a field type calculates the php class.
static render_checkbox_option ($name= '', $id= '', $current= '')
static render_field_option ($name= '', $option, $curr_value=NULL)
Handle rendering a field option form element.
static render_field_options ($field_type, $template_id, $field_id, $field_label, $area, $input_type=NULL, $uniqid= '', $current= '', $context= 'single', $item=array())
Render Field Options html (shown through a dialog box)
static render_select_option ($name= '', $id= '', $choices, $current= '')
Render the HTML for a select box to be used on the field & widgets options.
static render_setting_row ($key= '', $current_settings=array(), $override_input=null, $name= 'template_settings[%s]', $id= 'gravityview_se_%s')
Output a table row for view settings.
static render_text_option ($name= '', $id= '', $current= '', $add_merge_tags=NULL, $args=array())
static render_textarea_option ($name= '', $id= '', $current= '', $add_merge_tags=NULL, $args=array())
Detailed Description
Definition at line 14 of file class.render.settings.php.
Member Function Documentation
static get_cap_choices ($template_id = '', $field_id = '', $context = '', $input_type = '') static
Get capabilities options for GravityView.
Parameters are only to pass to the filter.
Parameters
string $template_id Optional. View slug
string $field_id Optional. GF Field ID - Example: 3, 5.2, entry_link, created_by
string $context Optional. What context are we in? Example: single or directory
string $input_type Optional. (textarea, list, select, etc.)
Returns
array Associative array, with the key being the capability and the value being the label shown.
Modify the capabilities shown in the field dropdown 1.0.1
Definition at line 114 of file class.render.settings.php.
Referenced by GravityView_Delete_Entry\delete_link_field_options(), and GravityView_Edit_Entry_Admin\field_options().
static get_default_field_options ($field_type, $template_id, $field_id, $context, $input_type) static
Get the default options for a standard field.
Parameters
string $field_type Type of field options to render (field or widget)
string $template_id Table slug
float $field_id GF Field ID - Example: 3, 5.2, entry_link, created_by
string $context What context are we in? Example: single or directory
string $input_type (textarea, list, select, etc.)
Returns
array Array of field options with label, value, type, default keys
Runs Filter:
gravityview_template_{$field_type}_options Filter the field options by field type. Filter names: gravityview_template_field_options and gravityview_template_widget_options
Parameters
[in,out] array Array of field options with label, value, type, default keys
[in] string $template_id Table slug
[in] float $field_id GF Field ID - Example: 3, 5.2, entry_link, created_by
[in] string $context What context are we in? Example: single or directory
[in] string $input_type (textarea, list, select, etc.)
Runs Filter:
gravityview_template_{$input_type}_options Filter the field options by input type ($input_type examples: textarea, list, select, etc.)
Parameters
[in,out] array Array of field options with label, value, type, default keys
[in] string $template_id Table slug
[in] float $field_id GF Field ID - Example: 3, 5.2, entry_link, created_by
[in] string $context What context are we in? Example: single or directory
[in] string $input_type (textarea, list, select, etc.)
Definition at line 26 of file class.render.settings.php.
static load_type_class ($field = NULL) static
Given a field type calculates the php class.
If not found try to load it.
Parameters
array $field
Returns
string type class name
Runs Filter:
gravityview/setting/class/{field_type}
Parameters
string $class_suffix field class suffix; GravityView_FieldType_{$class_suffix}
array $field field data
Runs Filter:
gravityview/setting/class_file/{field_type}
Parameters
string $field_type_include_path field class file path
array $field field data
Definition at line 354 of file class.render.settings.php.
References $field, and GRAVITYVIEW_DIR.
static render_checkbox_option ($name = '', $id = '', $current = '') static
Deprecated:
1.2 Render the HTML for a checkbox input to be used on the field & widgets options
Parameters
string $name,name attribute
string $current current value
Returns
string html tags
Definition at line 398 of file class.render.settings.php.
References $name, and $output.
static render_field_option ($name = '', $option, $curr_value = NULL) static
Handle rendering a field option form element.
Parameters
string $name Input name attribute
array $option Associative array of options. See the $defaults variable for available keys.
mixed $curr_value Current value of option
Returns
string HTML output of option
Deprecated:
setting index 'default' was replaced by 'value'
See also
GravityView_FieldType::get_field_defaults
Runs Filter:
gravityview/option/output/{option_type} Modify the output for a GravityView setting.
$option_type is the type of setting (radio, text, etc.)
Parameters
[in,out] string $output field class name
[in] array $option option field data
Definition at line 233 of file class.render.settings.php.
References $name, and $output.
Referenced by GravityView_Admin_Views\render_field_option().
static render_field_options ($field_type, $template_id, $field_id, $field_label, $area, $input_type = NULL, $uniqid = '', $current = '', $context = 'single', $item = array()) static
Render Field Options html (shown through a dialog box)
See also
GravityView_Ajax::get_field_options
GravityView_Admin_Views::render_active_areas
public
Parameters
string $field_type field / widget
string $template_id
string $field_id
string $field_label
string $area
string $uniqid (default: '')
string $current (default: '')
string $context (default: 'single')
array $item Field or widget array that's being rendered
Returns
string HTML of dialog box
Since
1.8
Definition at line 159 of file class.render.settings.php.
References $output, and $value.
Referenced by GravityView_Ajax\get_field_options(), and GravityView_Admin_Views\render_active_areas().
static render_select_option ($name = '', $id = '', $choices, $current = '') static
Render the HTML for a select box to be used on the field & widgets options.
Deprecated:
1.2
Parameters
string $name [name attribute]
array $choices [select options]
string $current [current value]
Returns
string [html tags]
Definition at line 476 of file class.render.settings.php.
References $label, $name, $output, and $value.
static render_setting_row ($key = '', $current_settings = array(), $override_input = null, $name = 'template_settings[%s]', $id = 'gravityview_se_%s') static
Output a table row for view settings.
Parameters
string $key The key of the input
array $current_settings Associative array of current settings to use as input values, if set. If not set, the defaults are used.
[type] $override_input [description]
string $name [description]
string $id [description]
Returns
[type] [description]
Deprecated:
setting index 'name' was replaced by 'label'
See also
GravityView_FieldType::get_field_defaults
Definition at line 289 of file class.render.settings.php.
References $current_settings, $name, $output, and GravityView_View_Data\get_default_arg().
Referenced by GravityView_Admin_Add_Shortcode\add_shortcode_popup(), and GravityView_Admin_Views\render_setting_row().
static render_text_option ($name = '', $id = '', $current = '', $add_merge_tags = NULL, $args = array()) static
Deprecated:
1.2 Render the HTML for an input text to be used on the field & widgets options
Parameters
string $name Unique name of the field. Exampe: fields[directory_list-title][5374ff6ab128b][custom_label]
string $current [current value]
string $desc Option description
string $add_merge_tags Add merge tags to the input?
Returns
string [html tags]
Definition at line 416 of file class.render.settings.php.
References $class, and $name.
static render_textarea_option ($name = '', $id = '', $current = '', $add_merge_tags = NULL, $args = array()) static
Deprecated:
1.2 Render the HTML for an textarea input to be used on the field & widgets options
Parameters
string $name Unique name of the field. Exampe: fields[directory_list-title][5374ff6ab128b][custom_label]
string $current [current value]
string $desc Option description
string $add_merge_tags Add merge tags to the input?
Returns
string [html tags]
Definition at line 446 of file class.render.settings.php.
References $class, and $name.
The documentation for this class was generated from the following file:
class.render.settings.php