GravityView: GravityView_Debug_Bar Class Reference
GravityView_Debug_Bar Class Reference
Public Member Functions
esc_html_recursive ($item)
Apply esc_html() to an array.
get_notices ()
get_warnings ()
init ()
Only show if WP_DEBUG is running.
prerender ()
render ()
Render the panel HTML.
render_item ($notice, $anchor= '')
Render each log item.
set_visible ($visible= '')
Should the panel be shown? If there are notices or warnings, yes.
Data Fields
$_visible = true
$notices = NULL
$warnings = NULL
Detailed Description
Definition at line 9 of file class-debug-bar.php.
Member Function Documentation
esc_html_recursive ($item)
Apply esc_html() to an array.
Parameters
string | array $item Unescaped
Returns
string Escaped HTML
Definition at line 135 of file class-debug-bar.php.
References $value.
get_notices ()
Definition at line 36 of file class-debug-bar.php.
References $notices, and GravityView_Logging\get_notices().
Referenced by render(), and set_visible().
get_warnings ()
Definition at line 27 of file class-debug-bar.php.
References $warnings, and GravityView_Logging\get_errors().
Referenced by render(), and set_visible().
init ()
Only show if WP_DEBUG is running.
Set the title of the panel.
Returns
[type] [description]
Definition at line 21 of file class-debug-bar.php.
prerender ()
Definition at line 45 of file class-debug-bar.php.
References set_visible().
render ()
Render the panel HTML.
Returns
string Panel output
Definition at line 61 of file class-debug-bar.php.
References $output, get_notices(), get_warnings(), GRAVITYVIEW_FILE, and render_item().
render_item ($notice, $anchor = '')
Render each log item.
Parameters
array $notice message, description, content
string $anchor The anchor ID for the item
Returns
string HTML output
Definition at line 157 of file class-debug-bar.php.
References $output.
Referenced by render().
set_visible ($visible = '')
Should the panel be shown? If there are notices or warnings, yes.
Returns
boolean true: show panel; false: hide panel
Definition at line 53 of file class-debug-bar.php.
References get_notices(), and get_warnings().
Referenced by prerender().
Field Documentation
$_visible = true
Definition at line 15 of file class-debug-bar.php.
$notices = NULL
Definition at line 13 of file class-debug-bar.php.
Referenced by get_notices().
$warnings = NULL
Definition at line 11 of file class-debug-bar.php.
Referenced by get_warnings().
The documentation for this class was generated from the following file:
class-debug-bar.php