GravityView: GravityView_API Class Reference
GravityView_API Class Reference
Static Public Member Functions
static directory_link ($post_id=NULL, $add_query_args=true)
Generate a link to the Directory view.
static entry_create_custom_slug ($entry, $form)
If using the entry custom slug feature, make sure the new entries have the custom slug created and saved as meta.
static entry_link ($entry, $post_id=NULL, $add_directory_args=true)
return href for single entry
static entry_link_html ($entry=array(), $anchor_text= '', $passed_tag_atts=array(), $field_settings=array())
Generate an anchor tag that links to an entry.
static field_class ($field, $form=NULL, $entry=NULL)
Fetch Field class.
static field_html_attr_id ($field, $form=array(), $entry=array())
Fetch Field HTML ID.
static field_label ($field, $entry=array(), $force_show_label=false)
Fetch Field Label.
static field_value ($entry, $field_settings, $format= 'html')
Given an entry and a form field id, calculate the entry value for that field.
static field_width ($field, $format= '%d%%')
Get column width from the field setting.
static get_entry_slug ($id_or_string, $entry=array())
Get the entry slug for the entry.
static no_results ($wpautop=true)
Get the "No Results" text depending on whether there were results.
static replace_variables ($text, $form, $entry)
Alias for GravityView_Merge_Tags::replace_variables()
Static Private Member Functions
static get_custom_entry_slug ($id, $entry=array())
Calculate an unique hash for an entry based on the entry ID.
Detailed Description
Definition at line 16 of file class-api.php.
Member Function Documentation
static directory_link ($post_id = NULL, $add_query_args = true) static
Generate a link to the Directory view.
Uses wp_cache_get and wp_cache_get (since 1.3) to speed up repeated requests to get permalink, which improves load time. Since we may be doing this hundreds of times per request, it adds up!
Parameters
int $post_id Post ID
boolean $add_query_args Add pagination and sorting arguments
Returns
string Permalink to multiple entries view
Definition at line 418 of file class-api.php.
References $gravityview_view, $post, GravityView_frontend\getInstance(), and GravityView_View\getInstance().
Referenced by GravityView_Delete_Entry\get_delete_link(), gv_directory_link(), and GravityView_API_Test\test_directory_link().
static entry_create_custom_slug ($entry, $form) static
If using the entry custom slug feature, make sure the new entries have the custom slug created and saved as meta.
Triggered by add_action('gform_entry_created', array('GravityView_API', 'entry_create_custom_slug'), 10, 2);
Parameters
$entry array Gravity Forms entry object
$form array Gravity Forms form object
Runs Filter:
gravityview_custom_entry_slug On entry creation, check if we are using the custom entry slug feature and update the meta
Parameters
boolean $custom Should we process the custom entry slug?
Definition at line 596 of file class-api.php.
static entry_link ($entry, $post_id = NULL, $add_directory_args = true) static
return href for single entry
Parameters
array | int $entry Entry array or entry ID
int | null $post_id If wanting to define the parent post, pass a post ID
boolean $add_directory_args True: Add args to help return to directory; False: only include args required to get to entry {
Since
1.7.3}
Returns
string Link to the entry with the directory parent slug
Since
1.7.3
1.7
Check if we have multiple views embedded in the same page and in that case make sure the single entry link has the view id so that Advanced Filters can be applied correctly when rendering the single view
See also
GravityView_frontend::get_context_view_id()
Definition at line 622 of file class-api.php.
References GVCommon\get_entry(), GravityView_Post_Types\get_entry_var_name(), GravityView_frontend\getInstance(), GravityView_View_Data\getInstance(), and gravityview_get_view_id().
Referenced by GravityView_Field_FileUpload\get_files_array(), GravityView_Entry_List\get_item_output(), and gv_entry_link().
static entry_link_html ($entry = array(), $anchor_text = '', $passed_tag_atts = array(), $field_settings = array()) static
Generate an anchor tag that links to an entry.
Since
1.6
Parameters
string $anchor_text The text or HTML inside the link
array $entry Gravity Forms entry array
array $field_settings Array of field settings. Optional, but passed to the gravityview_field_entry_link filter
Runs Filter:
gravityview_field_entry_link Modify the link HTML
Parameters
string $link HTML output of the link
string $href URL of the link
array $entry The GF entry array
array $field_settings Settings for the particular GV field
Definition at line 354 of file class-api.php.
References $field_settings, $href, $output, and gravityview_get_link().
static field_class ($field, $form = NULL, $entry = NULL) static
Fetch Field class.
public
Parameters
mixed $field
Returns
string
Definition at line 138 of file class-api.php.
References $field, $form_id, $gravityview_view, GravityView_View\getInstance(), and gravityview_sanitize_html_class().
Referenced by gv_class(), and GravityView_API_Test\test_field_class().
static field_html_attr_id ($field, $form = array(), $entry = array()) static
Fetch Field HTML ID.
Since
1.11
public
Parameters
array $field GravityView field array passed to gravityview_field_output()
array $form Gravity Forms form array, if set.
array $entry Gravity Forms entry array
Returns
string Sanitized unique HTML id attribute for the field
Definition at line 190 of file class-api.php.
References $field, $form_id, $gravityview_view, and GravityView_View\getInstance().
Referenced by gravityview_field_output().
static field_label ($field, $entry = array(), $force_show_label = false) static
Fetch Field Label.
public
Parameters
array $field GravityView field array
array $entry Gravity Forms entry array
boolean $force_show_label Whether to always show the label, regardless of field settings
Returns
string
Runs Filter:
gravityview_render_after_label Append content to a field label
Parameters
[in,out] string $appended_content Content you can add after a label. Empty by default.
[in] array $field GravityView field array
Runs Filter:
gravityview/template/field_label Modify field label output
Since
1.7
Parameters
[in,out] string $label Field label HTML
[in] array $field GravityView field array
[in] array $form Gravity Forms form array
[in] array $entry Gravity Forms entry array
Definition at line 28 of file class-api.php.
References $field, $gravityview_view, $label, and GravityView_View\getInstance().
Referenced by gv_label().
static field_value ($entry, $field_settings, $format = 'html') static
Given an entry and a form field id, calculate the entry value for that field.
public
Parameters
array $entry
integer $field
Returns
null|string
Gravity Forms' GFCache function was thrashing the database, causing double the amount of time for the field_value() method to run.
The reason is that the cache was checking against a field value stored in a transient every time GFFormsModel::get_lead_field_value() is called.
What we're doing here is telling the GFCache that it's already checked the transient and the value is false, forcing it to just use the non-cached data, which is actually faster.
Since
1.3
Parameters
string $cache_key Field Value transient key used by Gravity Forms
mixed false Setting the value of the cache to false so that it's not used by Gravity Forms' GFFormsModel::get_lead_field_value() method
boolean false Tell Gravity Forms not to store this as a transient
int 0 Time to store the value. 0 is maximum amount of time possible.
{
Since
1.6}
Link to the single entry by wrapping the output in an anchor tag
Fields can override this by modifying the field data variable inside the field. See /templates/fields/post_image.php for an example.
Runs Filter:
gravityview_field_entry_value_{$field_type} Modify the field value output for a field type. Example: gravityview_field_entry_value_number
Since
1.6
Parameters
string $output HTML value output
array $entry The GF entry array
array $field_settings Settings for the particular GV field
Runs Filter:
gravityview_field_entry_value Modify the field value output for all field types
Parameters
string $output HTML value output
array $entry The GF entry array
array $field_settings Settings for the particular GV field
array $field_data {
Since
1.6}
Definition at line 216 of file class-api.php.
References $field, $field_settings, $format, $gravityview_view, $output, $value, GravityView_View\getInstance(), and gravityview_get_field().
Referenced by gv_value().
static field_width ($field, $format = '%d%%') static
Get column width from the field setting.
Since
1.9
Parameters
array $field_setting Array of settings for the field
string $format Format for width. "%" (default) will return
Returns
string|null If not empty, string in $format format. Otherwise, null.
Definition at line 118 of file class-api.php.
References $field, and $format.
Referenced by gravityview_field_output().
static get_custom_entry_slug ($id, $entry = array()) static private
Calculate an unique hash for an entry based on the entry ID.
This allows you to be more discrete as to the number of the entry - if you don't want users to know that you have made a certain number of sales, for example, or that their entry in the giveaway is entry #3.
The hashed value MUST be unique, otherwise multiple entries will share the same URL, which leads to obvious problems.
Parameters
int | string $id Entry ID to generate the hash for.
array $entry Entry data passed to provide additional information when generating the hash. Optional - don't rely on it being available.
Returns
string Hashed unique value for entry
Runs Filter:
gravityview_entry_slug Modify the unique hash ID generated, if you want to improve usability or change the format. This will allow for custom URLs, such as {entryid}-{first-name} or even, if unique, {first-name}-{last-name}
Parameters
string $hash Existing hash generated by GravityView
string $id The entry ID
array $entry Entry data array. May be empty.
Definition at line 517 of file class-api.php.
static get_entry_slug ($id_or_string, $entry = array()) static
Get the entry slug for the entry.
By default, it is the entry ID.
See also
gravityview_get_entry() GravityView_API::get_custom_entry_slug() If using custom slug, gets the custom slug value
Since
1.4
Parameters
int | string $id_or_string ID of the entry, or custom slug string
array $entry Gravity Forms Entry array, optional. Used only to provide data to customize the gravityview_entry_slug filter
Returns
string Unique slug ID, passed through sanitize_title()
Default: use the entry ID as the unique identifier
Runs Filter:
gravityview_custom_entry_slug Whether to enable and use custom entry slugs.
Parameters
boolean True: Allow for slugs based on entry values. False: always use entry IDs (default)
Definition at line 549 of file class-api.php.
References $value.
Referenced by GravityView_Delete_Entry\get_delete_link().
static no_results ($wpautop = true) static
Get the "No Results" text depending on whether there were results.
Parameters
boolean $wpautop Apply wpautop() to the output?
Returns
string HTML of "no results" text
Runs Filter:
gravitview_no_entries_text Modify the text displayed when there are no entries.
Parameters
string $output The existing "No Entries" text
boolean $is_search Is the current page a search result, or just a multiple entries screen?
Definition at line 384 of file class-api.php.
References $gravityview_view, $output, and GravityView_View\getInstance().
Referenced by gv_no_results(), and GravityView_API_Test\test_no_results().
static replace_variables ($text, $form, $entry) static
Alias for GravityView_Merge_Tags::replace_variables()
See also
GravityView_Merge_Tags::replace_variables() Moved in 1.8.4
Parameters
string $text Text to replace variables in
array $form GF Form array
array $entry GF Entry array
Returns
string Text with variables maybe replaced
Definition at line 104 of file class-api.php.
References GravityView_Merge_Tags\replace_variables().
Referenced by GravityView_Entry_List\get_item_output(), GravityView_View\getBackLinkLabel(), GravityView_frontend\single_entry_title(), and GravityView_API_Test\test_replace_variables().
The documentation for this class was generated from the following file:
class-api.php