GravityView: GravityView_Admin_View_Item Class Reference
GravityView_Admin_View_Item Class Reference
A field or widget in GravityView view configuration.
Public Member Functions
__construct ($title= '', $field_id, $item=array(), $settings=array())
__toString ()
When echoing this class, print the HTML output.
getOutput ()
Generate HTML for field or a widget modal.
Protected Member Functions
additional_info ()
Overridden by child classes.
get_item_info ($html=true)
Generate the output for a field based on the additional_info() output.
Protected Attributes
$id
$item
$settings_html
$subtitle
$title
Private Attributes
$label_type
Detailed Description
A field or widget in GravityView view configuration.
Definition at line 71 of file class-admin-label.php.
Constructor & Destructor Documentation
__construct ($title = '', $field_id, $item = array(), $settings = array())
Definition at line 80 of file class-admin-label.php.
References $item, and $title.
Member Function Documentation
__toString ()
When echoing this class, print the HTML output.
Returns
string HTML output of the class
Definition at line 112 of file class-admin-label.php.
References getOutput().
additional_info () protected
Overridden by child classes.
Returns
array Array of content with arrays for each item. Those arrays have value, label and (optional) class keys
Definition at line 121 of file class-admin-label.php.
Referenced by get_item_info().
get_item_info ($html = true) protected
Generate the output for a field based on the additional_info() output.
See also
GravityView_Admin_View_Item::additional_info()
Parameters
boolean $html Display HTML output? If yes, output is wrapped in spans. If no, plaintext.
Returns
string|null If empty, return null. Otherwise, return output HTML/text.
Runs Filter:
gravityview_admin_label_item_info Tap in to modify the field information displayed next to an item
Parameters
array $field_info_items Additional information to display in a field
GravityView_Admin_View_Field $this Field shown in the admin
Definition at line 132 of file class-admin-label.php.
References $class, $html, $item, $output, and additional_info().
Referenced by getOutput().
getOutput ()
Generate HTML for field or a widget modal.
Returns
string
Definition at line 171 of file class-admin-label.php.
References $label, $output, $title, and get_item_info().
Referenced by __toString().
Field Documentation
$id protected
Definition at line 74 of file class-admin-label.php.
$item protected
Definition at line 78 of file class-admin-label.php.
Referenced by __construct(), and get_item_info().
$label_type private
Definition at line 77 of file class-admin-label.php.
$settings_html protected
Definition at line 76 of file class-admin-label.php.
$subtitle protected
Definition at line 75 of file class-admin-label.php.
$title protected
Definition at line 73 of file class-admin-label.php.
Referenced by __construct(), and getOutput().
The documentation for this class was generated from the following file:
class-admin-label.php