GravityView: GravityView_Plugin Class Reference
GravityView_Plugin Class Reference
Load common & connector functions.
Public Member Functions
add_hooks ()
Add hooks to set up the plugin.
frontend_actions ()
Function to launch frontend objects.
include_files ()
Include global plugin files.
load_plugin_textdomain ()
Loads the plugin's translated strings.
register_default_templates ()
Registers the default templates.
Static Public Member Functions
static activate ($network_wide=false)
Plugin activate function.
static deactivate ($network_wide)
Plugin deactivate function.
static get_default_widget_areas ()
helper function to define the default widget areas
static getInstance ()
Singleton instance.
static include_extension_framework ()
Include the extension class.
static include_widget_class ()
Load GravityView_Widget class.
static is_admin ()
Check if is_admin(), and make sure not DOING_AJAX.
static is_network_activated ()
Check whether GravityView is network activated.
static log_debug ($message, $data=null)
DEBUG.
static log_error ($message, $data=null)
Logs messages using Gravity Forms logging add-on.
Data Fields
const version = '1.13'
Private Member Functions
__construct ()
Static Private Attributes
static $instance
Detailed Description
Load common & connector functions.
Register Post Types and Rewrite Rules Add Cache Class Register hooks that are fired when the plugin is activated and deactivated. GravityView_Plugin main class.
Definition at line 90 of file gravityview.php.
Constructor & Destructor Documentation
__construct () private
Definition at line 110 of file gravityview.php.
References add_hooks(), GRAVITYVIEW_DIR, include_files(), and GravityView_Compatibility\is_valid().
Member Function Documentation
static activate ($network_wide = false) static
Plugin activate function.
public
Parameters
mixed $network_wide
Returns
void
Definition at line 203 of file gravityview.php.
References GravityView_Post_Types\init_post_types(), and GravityView_Post_Types\init_rewrite().
add_hooks ()
Add hooks to set up the plugin.
Since
1.12
Definition at line 128 of file gravityview.php.
Referenced by __construct().
static deactivate ($network_wide) static
Plugin deactivate function.
public
Parameters
mixed $network_wide
Returns
void
Definition at line 232 of file gravityview.php.
frontend_actions ()
Function to launch frontend objects.
public
Returns
void
When an entry is created, check if we need to update the custom slug meta todo: move this to its own class..
Runs Actions:
gravityview_include_frontend_actions Triggered after all GravityView frontend files are loaded
Nice place to insert extensions' frontend stuff
Definition at line 301 of file gravityview.php.
References GRAVITYVIEW_DIR.
static get_default_widget_areas () static
helper function to define the default widget areas
Todo:
Move somewhere logical
Returns
array definition for default widget areas
Runs Filter:
gravityview_widget_active_areas Array of zones available for widgets to be dropped into
Parameters
array $default_areas Definition for default widget areas
Definition at line 340 of file gravityview.php.
Referenced by GravityView_Ajax\get_preset_fields_config(), GravityView_View\render_widget_hooks(), and GravityView_Admin_Views\render_widgets_active_areas().
static getInstance () static
Singleton instance.
Returns
GravityView_Plugin GravityView_Plugin object
Definition at line 101 of file gravityview.php.
Referenced by GravityView_API_Test\setUp(), and GravityView_Connector_Functions_Test\setUp().
static include_extension_framework () static
Include the extension class.
Since
1.5.1
Returns
void
Definition at line 244 of file gravityview.php.
References GRAVITYVIEW_DIR.
include_files ()
Include global plugin files.
Since
1.12
Since
1.8.4
Definition at line 144 of file gravityview.php.
References GRAVITYVIEW_DIR.
Referenced by __construct().
static include_widget_class () static
Load GravityView_Widget class.
Since
1.7.5.1
Definition at line 255 of file gravityview.php.
References GRAVITYVIEW_DIR.
static is_admin () static
Check if is_admin(), and make sure not DOING_AJAX.
Since
1.7.5
Returns
bool
Definition at line 288 of file gravityview.php.
Referenced by GravityView_frontend\parse_content(), GravityView_Extension\settings(), and GVLogic_Shortcode\shortcode().
static is_network_activated () static
Check whether GravityView is network activated.
Since
1.7.6
Returns
bool
Definition at line 190 of file gravityview.php.
Referenced by GravityView_Settings\add_network_menu(), GravityView_Admin_Notices\check_show_multisite_notices(), and GravityView_Settings\create_app_menu().
load_plugin_textdomain ()
Loads the plugin's translated strings.
public
Returns
void
Definition at line 266 of file gravityview.php.
static log_debug ($message, $data = null) static
DEBUG.
Logs messages using Gravity Forms logging add-on
Parameters
string $message log message
mixed $data Additional data to display
Returns
void
Runs Actions:
gravityview_log_debug Log a debug message that shows up in the Gravity Forms Logging Addon and also the Debug Bar plugin output
Parameters
string $message Message to display
mixed $data Supporting data to print alongside it
Definition at line 362 of file gravityview.php.
static log_error ($message, $data = null) static
Logs messages using Gravity Forms logging add-on.
Parameters
string $message log message
Returns
void
Runs Actions:
gravityview_log_error Log an error message that shows up in the Gravity Forms Logging Addon and also the Debug Bar plugin output
Parameters
string $message Error message to display
mixed $data Supporting data to print alongside it
Definition at line 376 of file gravityview.php.
register_default_templates ()
Registers the default templates.
Todo:
Move somehere logical
Returns
void
Definition at line 331 of file gravityview.php.
References GRAVITYVIEW_DIR.
Field Documentation
$instance static private
Definition at line 94 of file gravityview.php.
const version = '1.13'
Definition at line 92 of file gravityview.php.
Referenced by GravityView_Admin_Add_Shortcode\add_scripts_and_styles(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_Admin_Views\add_scripts_and_styles(), GravityView_frontend\add_scripts_and_styles(), GravityView_Recent_Entries_Widget\admin_enqueue_scripts(), GravityView_Settings\app_settings_fields(), GravityView_Admin_Views\enqueue_feedback_widget(), GravityView_Extension\is_extension_supported(), GravityView_Template\register_styles(), GravityView_Settings\styles(), and GravityView_Welcome\tabs().
The documentation for this class was generated from the following file:
gravityview.php