GravityView: GravityView_Metabox_Tabs Class Reference
GravityView_Metabox_Tabs Class Reference
Stores each GravityView_Metabox_Tab instance.
Static Public Member Functions
static add (GravityView_Metabox_Tab $meta_box)
Add a tab.
static get ($id)
Get a tab by ID.
static get_all ()
Get array of all registered metaboxes.
static remove ($meta_box_id)
Remove a tab by tab ID.
Static Protected Attributes
static $meta_boxes = array()
Detailed Description
Stores each GravityView_Metabox_Tab instance.
Since
1.8
See also
https://gist.github.com/zackkatz/6cc381bcf54849f2ed41 For example of adding a metabox
https://github.com/WebDevStudios/CMB2/blob/master/includes/CMB2_Boxes.php Thanks for the inspiration
Definition at line 9 of file class-gravityview-metabox-tabs.php.
Member Function Documentation
static add (GravityView_Metabox_Tab $meta_box) static
Add a tab.
Since
1.8
Parameters
GravityView_Metabox_Tab $meta_box
Returns
void
Definition at line 27 of file class-gravityview-metabox-tabs.php.
Referenced by GravityView_Extension\add_metabox_tab(), and GravityView_Admin_Metaboxes\add_settings_metabox_tabs().
static get ($id) static
Get a tab by ID.
Since
1.8
Parameters
string $id
Returns
bool|GravityView_Metabox_Tab False if none exist at the key $id; GravityView_Metabox_Tab if exists.
Definition at line 55 of file class-gravityview-metabox-tabs.php.
static get_all () static
Get array of all registered metaboxes.
Returns
array|GravityView_Metabox_Tab[] Empty array if no tabs, otherwise array of GravityView_Metabox_Tabs
Definition at line 68 of file class-gravityview-metabox-tabs.php.
Referenced by GravityView_Admin_Metaboxes\settings_metabox_render().
static remove ($meta_box_id) static
Remove a tab by tab ID.
Since
1.8
Parameters
string $meta_box_id
Returns
void
Definition at line 40 of file class-gravityview-metabox-tabs.php.
Field Documentation
$meta_boxes = array() static protected
Definition at line 16 of file class-gravityview-metabox-tabs.php.
The documentation for this class was generated from the following file:
class-gravityview-metabox-tabs.php