GravityView: GravityView_Extension Class Reference
GravityView_Extension Class Reference
Extend this class to create a GravityView extension that gets updates from GravityView.co.
Public Member Functions
__construct ()
add_hooks ()
Extensions should override this hook to add their hooks instead of.
add_metabox_tab ()
If Extension overrides tab_settings() and passes its own tab, add it to the tabbed settings metabox.
admin_notice ()
Outputs the admin notices generated by the plugin.
load_plugin_textdomain ()
Load translations for the extension.
save_post ($post_id)
Store the filter settings in the _gravityview_filters post meta.
settings ()
Register the updater for the Extension using GravityView license information.
tooltips ($tooltips=array())
Add tooltips for the extension.
Static Public Member Functions
static add_notice ($notice=array())
Add a notice to be displayed in the admin.
Static Public Attributes
static $is_compatible = true
Protected Member Functions
get_license ()
Get license information from GravityView.
is_extension_supported ()
Check whether the extension is supported:
tab_settings ()
Add a tab to GravityView Edit View tabbed metabox.
Protected Attributes
$_author = 'Katz Web Services, Inc.'
$_min_gravityview_version = '1.1.5'
$_min_php_version = '5.2.4'
$_remote_update_url = 'https://gravityview.co'
$_text_domain = 'gravityview'
$_title = NULL
$_version = NULL
Static Private Attributes
static $admin_notices = array()
Detailed Description
Extend this class to create a GravityView extension that gets updates from GravityView.co.
Since
1.1
Version
1.1
Definition at line 17 of file class-gravityview-extension.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 64 of file class-gravityview-extension.php.
References add_hooks(), and is_extension_supported().
Member Function Documentation
add_hooks ()
Extensions should override this hook to add their hooks instead of.
Definition at line 292 of file class-gravityview-extension.php.
Referenced by __construct().
add_metabox_tab ()
If Extension overrides tab_settings() and passes its own tab, add it to the tabbed settings metabox.
Since
1.8 (Extension version 1.0.7)
Returns
void
Definition at line 115 of file class-gravityview-extension.php.
References GravityView_Metabox_Tabs\add(), and tab_settings().
static add_notice ($notice = array()) static
Add a notice to be displayed in the admin.
Parameters
array $notice Array with class and message keys. The message is not escaped.
Definition at line 275 of file class-gravityview-extension.php.
admin_notice ()
Outputs the admin notices generated by the plugin.
Returns
void
Definition at line 253 of file class-gravityview-extension.php.
get_license () protected
Get license information from GravityView.
Since
1.8 (Extension version 1.0.7)
Returns
bool|array False: GravityView_Settings class does not exist. Array: array of GV license data.
Definition at line 204 of file class-gravityview-extension.php.
References GravityView_Settings\getSetting().
Referenced by settings().
is_extension_supported () protected
Check whether the extension is supported:
Checks if GravityView and Gravity Forms exist
Checks GravityView and Gravity Forms version numbers
Checks PHP version numbers
Sets self::$is_compatible to boolean value
GravityView_Admin::check_gravityforms()
Returns
boolean Is the extension supported?
Definition at line 335 of file class-gravityview-extension.php.
References GravityView_Compatibility\is_valid(), and GravityView_Plugin\version.
Referenced by __construct().
load_plugin_textdomain ()
Load translations for the extension.
Check wp-content/languages/gravityview/ folder and load using load_textdomain()
Check wp-content/plugins/gravityview/languages/ folder for gravityview-[locale].mo file and load using load_textdomain()
Load default file using load_plugin_textdomain() from wp-content/plugins/gravityview/languages/
Returns
void
Definition at line 162 of file class-gravityview-extension.php.
References $path.
save_post ($post_id)
Store the filter settings in the _gravityview_filters post meta.
Parameters
int $post_id Post ID
Returns
void
Definition at line 299 of file class-gravityview-extension.php.
settings ()
Register the updater for the Extension using GravityView license information.
Returns
void
Definition at line 220 of file class-gravityview-extension.php.
References get_license(), and GravityView_Plugin\is_admin().
tab_settings () protected
Add a tab to GravityView Edit View tabbed metabox.
By overriding this method, you will add a tab to View settings
Since
1.8 (Extension version 1.0.7)
See also
https://gist.github.com/zackkatz/6cc381bcf54849f2ed41 For example of adding a metabox
Returns
array { string $id Metabox HTML ID, without gravityview_ prefix string $title Name of the metabox. Shown in the tab. string $file The file name of a file stored in the /gravityview/includes/admin/metaboxes/views/ directory to render the metabox output, or the full path to a file. If defined, callback is not used. string $icon_class_name Icon class used in vertical tabs. Supports non-dashicon. If dashicons, no need for dashicons prefix string $callback Function to render the metabox, if $file is not defined. null $callback_args Arguments passed to the callback }
Definition at line 103 of file class-gravityview-extension.php.
Referenced by add_metabox_tab().
tooltips ($tooltips = array())
Add tooltips for the extension.
Add a tooltip with an array using the title and value keys. The title key is the H6 tag value of the tooltip; it's the headline. The value is the tooltip content, and can contain any HTML.
The tooltip key must be gv_{name_of_setting}. If the name of the setting is "example_extension_setting", the code would be:
$tooltips['gv_example_extension_setting'] = array('title' => 'About Example Extension Setting', 'value' => 'When you do [x] with [y], [z] happens.');
Parameters
array $tooltips Existing GV tooltips, with title and value keys
Returns
array Modified tooltips
Definition at line 318 of file class-gravityview-extension.php.
Field Documentation
$_author = 'Katz Web Services, Inc.' protected
Definition at line 52 of file class-gravityview-extension.php.
$_min_gravityview_version = '1.1.5' protected
Definition at line 37 of file class-gravityview-extension.php.
$_min_php_version = '5.2.4' protected
Definition at line 42 of file class-gravityview-extension.php.
$_remote_update_url = 'https://gravityview.co' protected
Definition at line 47 of file class-gravityview-extension.php.
$_text_domain = 'gravityview' protected
Definition at line 32 of file class-gravityview-extension.php.
$_title = NULL protected
Definition at line 22 of file class-gravityview-extension.php.
$_version = NULL protected
Definition at line 27 of file class-gravityview-extension.php.
$admin_notices = array() static private
Definition at line 57 of file class-gravityview-extension.php.
$is_compatible = true static
Definition at line 62 of file class-gravityview-extension.php.
The documentation for this class was generated from the following file:
class-gravityview-extension.php