GravityView: GravityView_Delete_Entry Class Reference
GravityView_Delete_Entry Class Reference
Public Member Functions
__construct ()
add_available_field ($available_fields=array())
Add Delete Entry Link to the Add Field dialog.
add_default_field ($entry_default_fields, $form=array(), $zone= '')
Add Edit Link as a default field, outside those set in the Gravity Form form.
add_delete_button ($form=array(), $entry=array(), $view_id=NULL)
Add a Delete button to the #publishing-action section of the Delete Entry form.
add_template_path ($file_paths)
Include this extension templates path.
delete_link_field_options ($field_options, $template_id, $field_id, $context, $input_type)
Add "Delete Link Text" setting to the edit_link field settings.
display_message ()
After processing delete entry, the user will be redirected to the referring View or embedded post/page.
modify_visibility_caps ($visibility_caps=array(), $template_id= '', $field_id= '', $context= '', $input_type= '')
Change wording for the Edit context to read Entry Creator.
process_delete ()
Handle the deletion request, if $_GET['action'] is set to "delete".
set_entry ($entry=null)
Make sure there's an entry.
user_can_delete_entry ($entry=array())
Check if the user can edit the entry.
verify_nonce ()
Is the current nonce valid for editing the entry?
Static Public Member Functions
static check_user_cap_delete_entry ($entry, $field=array())
checks if user has permissions to view the link or delete a specific entry
static get_delete_link ($entry, $view_id=0, $post_id=null)
Generate a nonce link with the base URL of the current View embed.
static get_nonce_key ($entry_id)
Generate a consistent nonce key based on the Entry ID.
static getInstance ()
Return the instantiated class object.
Data Fields
$entry
$form
$is_valid = NULL
$view_id
Static Public Attributes
static $file
static $instance
Private Member Functions
add_hooks ()
include_files ()
Detailed Description
Since
1.5.1
Definition at line 22 of file class-delete-entry.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 31 of file class-delete-entry.php.
References add_hooks(), and include_files().
Member Function Documentation
add_available_field ($available_fields = array())
Add Delete Entry Link to the Add Field dialog.
Since
1.5.1
Parameters
array $available_fields
Definition at line 164 of file class-delete-entry.php.
add_default_field ($entry_default_fields, $form = array(), $zone = '')
Add Edit Link as a default field, outside those set in the Gravity Form form.
Since
1.5.1
Parameters
array $entry_default_fields Existing fields
string | array $form form_ID or form object
string $zone Either 'single', 'directory', 'header', 'footer'
Definition at line 148 of file class-delete-entry.php.
add_delete_button ($form = array(), $entry = array(), $view_id = NULL)
Add a Delete button to the #publishing-action section of the Delete Entry form.
Since
1.5.1
Parameters
array $form Gravity Forms form array
array $entry Gravity Forms entry array
int $view_id GravityView View ID
Show or hide the delete button in the Edit Entry screen
Parameters
boolean $show_entry Default: true
Definition at line 272 of file class-delete-entry.php.
References $attributes, and gravityview_get_link().
add_hooks () private
Since
1.9.2
Definition at line 50 of file class-delete-entry.php.
Referenced by __construct().
add_template_path ($file_paths)
Include this extension templates path.
Since
1.5.1
Parameters
array $file_paths List of template paths ordered
Definition at line 90 of file class-delete-entry.php.
static check_user_cap_delete_entry ($entry, $field = array()) static
checks if user has permissions to view the link or delete a specific entry
Since
1.5.1
Parameters
array $entry Gravity Forms entry array
array $field Field settings (optional)
Returns
bool
Definition at line 474 of file class-delete-entry.php.
References $field, $gravityview_view, GravityView_View\getInstance(), and gravityview_get_current_view_data().
delete_link_field_options ($field_options, $template_id, $field_id, $context, $input_type)
Add "Delete Link Text" setting to the edit_link field settings.
Since
1.5.1
Parameters
[type] $field_options [description]
[type] $template_id [description]
[type] $field_id [description]
[type] $context [description]
[type] $input_type [description]
Returns
[type] [description]
Definition at line 110 of file class-delete-entry.php.
References GravityView_Render_Settings\get_cap_choices().
display_message ()
After processing delete entry, the user will be redirected to the referring View or embedded post/page.
Display a message on redirection.
If success, there will be status URL parameters status=>success If an error, there will be status and message URL parameters status=>error&message=example
Since
1.5.1
Returns
void
Definition at line 557 of file class-delete-entry.php.
References $class.
static get_delete_link ($entry, $view_id = 0, $post_id = null) static
Generate a nonce link with the base URL of the current View embed.
We don't want to link to the single entry, because when deleted, there would be nothing to return to.
Since
1.5.1
Parameters
array $entry Gravity Forms entry array
Returns
string|null If directory link is valid, the URL to process the delete request. Otherwise, NULL.
Definition at line 236 of file class-delete-entry.php.
References $url, $view_id, GravityView_API\directory_link(), GravityView_API\get_entry_slug(), and gravityview_get_view_id().
Referenced by GravityView_Delete_Entry_Shortcode\shortcode().
static get_nonce_key ($entry_id) static
Generate a consistent nonce key based on the Entry ID.
Since
1.5.1
Parameters
int $entry_id Entry ID
Returns
string Key used to validate request
Definition at line 222 of file class-delete-entry.php.
static getInstance () static
Return the instantiated class object.
Since
1.5.1
Returns
GravityView_Delete_Entry
Definition at line 75 of file class-delete-entry.php.
include_files () private
Since
1.9.2
Definition at line 43 of file class-delete-entry.php.
Referenced by __construct().
modify_visibility_caps ($visibility_caps = array(), $template_id = '', $field_id = '', $context = '', $input_type = '')
Change wording for the Edit context to read Entry Creator.
Since
1.5.1
Parameters
array $visibility_caps Array of capabilities to display in field dropdown.
string $field_type Type of field options to render (field or widget)
string $template_id Table slug
float $field_id GF Field ID - Example: 3, 5.2, entry_link, created_by
string $context What context are we in? Example: single or directory
string $input_type (textarea, list, select, etc.)
Returns
array Array of field options with label, value, type, default keys
Definition at line 189 of file class-delete-entry.php.
process_delete ()
Handle the deletion request, if $_GET['action'] is set to "delete".
Check referrer validity
Make sure there's an entry with the slug of $_GET['entry_id']
If so, attempt to delete the entry. If not, set the error status
Remove action=delete from the URL
Redirect to the page using wp_safe_redirect()
Since
1.5.1 GFAPI::delete_entry() wp_safe_redirect()
Returns
void
Definition at line 314 of file class-delete-entry.php.
References gravityview_get_entry(), and user_can_delete_entry().
set_entry ($entry = null)
Make sure there's an entry.
Since
1.5.1
Parameters
[type] $entry [description]
Definition at line 211 of file class-delete-entry.php.
References $entry, and GravityView_View\getInstance().
user_can_delete_entry ($entry = array())
Check if the user can edit the entry.
Is the nonce valid?
Does the user have the right caps for the entry
Is the entry in the trash?
Since
1.5.1
Parameters
array $entry Gravity Forms entry array
Returns
boolean|WP_Error True: can edit form. WP_Error: nope.
Definition at line 439 of file class-delete-entry.php.
Referenced by process_delete().
verify_nonce ()
Is the current nonce valid for editing the entry?
Since
1.5.1
Returns
boolean
Definition at line 396 of file class-delete-entry.php.
Field Documentation
$entry
Definition at line 26 of file class-delete-entry.php.
Referenced by set_entry().
$file static
Definition at line 24 of file class-delete-entry.php.
$form
Definition at line 27 of file class-delete-entry.php.
$instance static
Definition at line 25 of file class-delete-entry.php.
$is_valid = NULL
Definition at line 29 of file class-delete-entry.php.
$view_id
Definition at line 28 of file class-delete-entry.php.
Referenced by get_delete_link().
The documentation for this class was generated from the following file:
class-delete-entry.php