GravityView: GravityView_Admin_Views Class Reference
GravityView_Admin_Views Class Reference
If this file is called directly, abort.
Public Member Functions
__construct ()
add_post_type_columns ($columns)
Add the Data Source column to the Views page.
default_field_blacklist ($array=array(), $context=NULL)
List the field types without presentation properties (on a View context)
get_available_fields ($form= '', $zone=NULL)
Calculate the available fields.
get_entry_default_fields ($form, $zone)
Retrieve the default fields id, label and type.
register_no_conflict ($registered)
render_active_areas ($template_id, $type, $zone, $rows, $values)
Generic function to render rows and columns of active areas for widgets & fields.
render_additional_fields ($form, $context)
render_available_fields ($form= '', $context= 'single')
Render html for displaying available fields based on a Form ID $blacklist_field_types - contains the field types which are not proper to be shown in a directory.
render_available_widgets ()
Render html for displaying available widgets.
render_directory_active_areas ($template_id= '', $context= 'single', $post_id= '', $echo=false)
Render the Template Active Areas and configured active fields for a given template id and post id.
render_label ()
render_widgets_active_areas ($template_id= '', $zone, $post_id= '')
Render the widget active areas.
save_postdata ($post_id)
Save View configuration.
tooltips ($tooltips=array())
Add tooltip text for use throughout the UI.
Static Public Member Functions
static add_connected_form_column_content ($column_name=NULL, $post_id)
Add the Data Source information.
static add_scripts_and_styles ($hook)
Enqueue scripts and styles at Views editor.
static enqueue_feedback_widget ()
Chatlio.com customer support widget.
static enqueue_gravity_forms_scripts ()
static get_connected_form_links ($form, $include_form_link=true)
Get HTML links relating to a connected form, like Edit, Entries, Settings, Preview.
static gform_toolbar_menu ($menu_items=array(), $id=NULL)
Add a GravityView menu to the Form Toolbar with connected views.
static render_field_option ($name= '', $option, $curr_value=NULL)
static render_setting_row ($key= '', $current_settings=array(), $override_input=null, $name= 'template_settings[%s]', $id= 'gravityview_se_%s')
Detailed Description
If this file is called directly, abort.
Definition at line 19 of file class-admin-views.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 23 of file class-admin-views.php.
Member Function Documentation
static add_connected_form_column_content ($column_name = NULL, $post_id) static
Add the Data Source information.
Parameters
null $column_name
$post_id
Returns
void
Definition at line 213 of file class-admin-views.php.
References $form_id, gravityview_get_form(), and gravityview_get_form_id().
add_post_type_columns ($columns)
Add the Data Source column to the Views page.
Parameters
array $columns Columns array
Definition at line 306 of file class-admin-views.php.
static add_scripts_and_styles ($hook) static
Enqueue scripts and styles at Views editor.
public
Parameters
mixed $hook
Returns
void
Definition at line 921 of file class-admin-views.php.
References GRAVITYVIEW_FILE, gravityview_is_admin_page(), and GravityView_Plugin\version.
default_field_blacklist ($array = array(), $context = NULL)
List the field types without presentation properties (on a View context)
Parameters
array $array Existing field types to add to a blacklist
string | null $context Context for the blacklist. Default: NULL. public
Returns
array Default blacklist fields merged with existing blacklist fields
Definition at line 136 of file class-admin-views.php.
static enqueue_feedback_widget () static
Chatlio.com customer support widget.
Definition at line 850 of file class-admin-views.php.
References GravityView_Settings\getSetting(), GRAVITYVIEW_FILE, and GravityView_Plugin\version.
static enqueue_gravity_forms_scripts () static
Definition at line 975 of file class-admin-views.php.
Referenced by GravityView_Recent_Entries_Widget\admin_enqueue_scripts().
get_available_fields ($form = '', $zone = NULL)
Calculate the available fields.
Parameters
string | array $form form_ID or form object
string $zone Either 'single', 'directory', 'header', 'footer'
Returns
array fields
Definition at line 612 of file class-admin-views.php.
References get_entry_default_fields(), gravityview_get_entry_meta(), and gravityview_get_form_fields().
Referenced by render_active_areas(), and render_available_fields().
static get_connected_form_links ($form, $include_form_link = true) static
Get HTML links relating to a connected form, like Edit, Entries, Settings, Preview.
Parameters
array | int $form_id Gravity Forms forms array, or the form ID
boolean $include_form_link Whether to include the bold name of the form in the output
Returns
string HTML links
Modify the links shown in the Connected Form links
Since
1.6
Parameters
array $links Links to show
array $form Gravity Forms form array
Definition at line 244 of file class-admin-views.php.
References $form_id, $output, and gravityview_get_form().
Referenced by GravityView_Admin_Metaboxes\get_data_source_header().
get_entry_default_fields ($form, $zone)
Retrieve the default fields id, label and type.
Parameters
string | array $form form_ID or form object
string $zone Either 'single', 'directory', 'header', 'footer'
Returns
array
Since
1.2
1.7.2
Definition at line 538 of file class-admin-views.php.
Referenced by get_available_fields().
static gform_toolbar_menu ($menu_items = array(), $id = NULL) static
Add a GravityView menu to the Form Toolbar with connected views.
Parameters
array $menu_items Menu items, as set in GFForms::top_toolbar()
int $id ID of the current Gravity form
Returns
array Modified array
Definition at line 84 of file class-admin-views.php.
References $label, and gravityview_get_connected_views().
register_no_conflict ($registered)
Definition at line 994 of file class-admin-views.php.
render_active_areas ($template_id, $type, $zone, $rows, $values)
Generic function to render rows and columns of active areas for widgets & fields.
Parameters
string $type Either 'widget' or 'field'
string $zone Either 'single', 'directory', 'header', 'footer'
array $rows The layout structure: rows, columns and areas
array $values Saved objects
Returns
void
Definition at line 667 of file class-admin-views.php.
References $field, $post, endforeach, get_available_fields(), gravityview_get_form_id(), GravityView_Ajax\pre_get_form_fields(), and GravityView_Render_Settings\render_field_options().
Referenced by render_directory_active_areas(), and render_widgets_active_areas().
render_additional_fields ($form, $context)
Definition at line 491 of file class-admin-views.php.
Referenced by render_available_fields().
render_available_fields ($form = '', $context = 'single')
Render html for displaying available fields based on a Form ID $blacklist_field_types - contains the field types which are not proper to be shown in a directory.
public
Parameters
int $form_id Gravity Forms Form ID (default: '')
string $context (default: 'single')
Returns
void
Runs Filter:
gravityview_blacklist_field_types Modify the types of fields that shouldn't be shown in a View.
Parameters
[in,out] array $blacklist_field_types Array of field types to block for this context.
[in] string $context View context ('single', 'directory', or 'edit')
Definition at line 450 of file class-admin-views.php.
References $output, get_available_fields(), and render_additional_fields().
render_available_widgets ()
Render html for displaying available widgets.
Returns
string html
Definition at line 643 of file class-admin-views.php.
render_directory_active_areas ($template_id = '', $context = 'single', $post_id = '', $echo = false)
Render the Template Active Areas and configured active fields for a given template id and post id.
public
Parameters
string $template_id (default: '')
string $post_id (default: '')
string $context (default: 'single')
Returns
string HTML of the active areas
Definition at line 811 of file class-admin-views.php.
References $output, gravityview_get_directory_fields(), and render_active_areas().
static render_field_option ($name = '', $option, $curr_value = NULL) static
Deprecated:
since 1.2 Start using GravityView_Render_Settings::render_field_option
Definition at line 72 of file class-admin-views.php.
References $name, and GravityView_Render_Settings\render_field_option().
render_label ()
Deprecated:
1.1.6
Definition at line 437 of file class-admin-views.php.
static render_setting_row ($key = '', $current_settings = array(), $override_input = null, $name = 'template_settings[%s]', $id = 'gravityview_se_%s') static
Deprecated:
since 1.2 Start using GravityView_Render_Settings::render_setting_row
Definition at line 63 of file class-admin-views.php.
References $current_settings, $name, and GravityView_Render_Settings\render_setting_row().
render_widgets_active_areas ($template_id = '', $zone, $post_id = '')
Render the widget active areas.
Parameters
string $zone Either 'header' or 'footer'
string $post_id Current Post ID (view)
Returns
string html
Definition at line 777 of file class-admin-views.php.
References $output, GravityView_Plugin\get_default_widget_areas(), and render_active_areas().
save_postdata ($post_id)
Save View configuration.
public
Parameters
mixed $post_id
Returns
void
Definition at line 329 of file class-admin-views.php.
References $form_id, and GVCommon\gv_parse_str().
tooltips ($tooltips = array())
Add tooltip text for use throughout the UI.
Parameters
array $tooltips Array of Gravity Forms tooltips
Returns
array Modified tooltips array
Definition at line 155 of file class-admin-views.php.
References $title, and GravityView_View_Data\get_default_args().
The documentation for this class was generated from the following file:
class-admin-views.php