GravityView: GravityView_API_Test Class Reference
GravityView_API_Test Class Reference
Public Member Functions
_get_new_view_id ()
_override_no_entries_text_output ($previous, $is_search=false)
setUp ()
test_directory_link ()
test_field_class ()
GravityView_API::field_class()
test_gravityview_format_link_DEFAULT ()
api
test_gravityview_format_link_WHEN_FILTER_NOQUERYSTRING_FALSE ()
api
test_gravityview_format_link_WHEN_FILTER_NOSUBDOMAIN_FALSE ()
api gravityview_format_link()
test_gravityview_format_link_WHEN_FILTER_ROOTONLY_FALSE ()
api
test_gravityview_get_current_views ()
test_gravityview_sanitize_html_class ()
gravityview_sanitize_html_class()
test_no_results ()
$this->_override_no_entries_text_output() GravityView_API::no_results()
test_replace_variables ()
GravityView_API::replace_variables()
Detailed Description
Definition at line 3 of file connector-API_Test.php.
Member Function Documentation
_get_new_view_id ()
Definition at line 170 of file connector-API_Test.php.
References GravityView_View_Data\get_default_args().
Referenced by test_directory_link(), and test_gravityview_get_current_views().
_override_no_entries_text_output ($previous, $is_search = false)
Definition at line 160 of file connector-API_Test.php.
setUp ()
Definition at line 5 of file connector-API_Test.php.
References GravityView_Plugin\getInstance().
test_directory_link ()
Definition at line 191 of file connector-API_Test.php.
References $gravityview_view, $post, _get_new_view_id(), GravityView_API\directory_link(), and GravityView_frontend\getInstance().
test_field_class ()
GravityView_API::field_class()
Definition at line 74 of file connector-API_Test.php.
References $field, and GravityView_API\field_class().
test_gravityview_format_link_DEFAULT ()
api
Definition at line 321 of file connector-API_Test.php.
References gravityview_format_link().
test_gravityview_format_link_WHEN_FILTER_NOQUERYSTRING_FALSE ()
api
Definition at line 493 of file connector-API_Test.php.
References gravityview_format_link().
test_gravityview_format_link_WHEN_FILTER_NOSUBDOMAIN_FALSE ()
api gravityview_format_link()
Definition at line 446 of file connector-API_Test.php.
References gravityview_format_link().
test_gravityview_format_link_WHEN_FILTER_ROOTONLY_FALSE ()
api
Definition at line 415 of file connector-API_Test.php.
References gravityview_format_link().
test_gravityview_get_current_views ()
Definition at line 250 of file connector-API_Test.php.
References $post, _get_new_view_id(), GravityView_frontend\getInstance(), and gravityview_get_current_views().
test_gravityview_sanitize_html_class ()
gravityview_sanitize_html_class()
Definition at line 286 of file connector-API_Test.php.
References gravityview_sanitize_html_class().
test_no_results ()
$this->_override_no_entries_text_output() GravityView_API::no_results()
Definition at line 123 of file connector-API_Test.php.
References $gravityview_view, and GravityView_API\no_results().
test_replace_variables ()
GravityView_API::replace_variables()
Definition at line 18 of file connector-API_Test.php.
References GravityView_API\replace_variables().
The documentation for this class was generated from the following file:
connector-API_Test.php