GravityView: GravityView_Settings Class Reference
GravityView_Settings Class Reference
GravityView Settings class (get/set/license validation) using the Gravity Forms App framework.
Public Member Functions
__construct ($prevent_multiple_instances= '')
We're not able to set the __construct() method to private because we're extending the GFAddon class, so we fake it.
add_network_menu ()
Add global Settings page for Multisite.
app_settings_fields ()
Specify the settings fields to be rendered on the plugin settings page.
app_settings_icon ()
Prevent displaying of any icon.
app_settings_title ()
The Settings title.
create_app_menu ()
Add Settings link to GravityView menu.
current_user_can_any ($caps)
Prevent uninstall tab from being shown by returning false for the uninstall capability check.
get_app_setting ($setting_name)
Make protected public public.
get_app_settings ()
Returns the currently saved plugin settings.
get_license_handler ()
Allow public access to the GV_License_Handler class.
get_posted_settings ()
When the settings are saved, make sure the license key matches the previously activated key.
get_required_indicator ($field)
Gets the required indicator Gets the markup of the required indicator symbol to highlight fields that are required.
init_admin ()
Run actions when initializing admin.
init_ajax ()
Load license handler in admin-ajax.php.
license_key_notice ()
Display a notice if the plugin is inactive.
modify_app_settings_menu_title ($setting_tabs)
Change the settings page header title to "GravityView".
set_field_error ($field, $error_message= '')
Make protected public public.
settings_save ($field, $echo=true)
Allow customizing the Save field parameters.
settings_submit ($field, $echo=true)
single_setting_label ($field)
The same as the parent, except added support for field descriptions .
styles ()
Register styles in the app admin page.
update_app_settings ($settings)
Updates app settings with the provided settings.
Static Public Member Functions
static get_instance ()
static getSetting ($key)
Get the setting for GravityView by name.
Data Fields
$app_hook_suffix = 'gravityview'
Protected Member Functions
settings_edd_license ($field, $echo=true)
Register the settings field for the EDD License field type.
Protected Attributes
$_capabilities_uninstall = 'gravityview_gfaddon_uninstall'
$_min_gravityforms_version = GV_MIN_GF_VERSION
$_short_title = 'GravityView'
$_slug = 'gravityview'
$_title = 'GravityView'
$_version = GravityView_Plugin::version
Private Member Functions
_load_license_handler ()
Make sure the license handler is available.
get_default_settings ()
Get the default settings for the plugin.
Private Attributes
$License_Handler
Static Private Attributes
static $instance
Detailed Description
GravityView Settings class (get/set/license validation) using the Gravity Forms App framework.
Since
1.7.4 (Before, used the Redux Framework)
Definition at line 7 of file class-settings.php.
Constructor & Destructor Documentation
__construct ($prevent_multiple_instances = '')
We're not able to set the __construct() method to private because we're extending the GFAddon class, so we fake it.
When called using new GravityView_Settings, it will return get_instance() instead. We pass 'get_instance' as a test string.
See also
get_instance()
Parameters
string $prevent_multiple_instances
Definition at line 62 of file class-settings.php.
Member Function Documentation
_load_license_handler () private
Make sure the license handler is available.
Definition at line 153 of file class-settings.php.
References GV_License_Handler\get_instance(), and GRAVITYVIEW_DIR.
Referenced by init_admin(), and init_ajax().
add_network_menu ()
Add global Settings page for Multisite.
Since
1.7.6
Returns
void
Definition at line 235 of file class-settings.php.
References GravityView_Plugin\is_network_activated().
app_settings_fields ()
Specify the settings fields to be rendered on the plugin settings page.
Returns
array
Redux backward compatibility
Since
1.7.4
Extensions can tap in here to insert their own section and settings.
$sections[] = array('title' => __('GravityView My Extension Settings', 'gravityview'), 'fields' => $settings,);
Definition at line 521 of file class-settings.php.
References $field, get_app_setting(), get_default_settings(), and GravityView_Plugin\version.
app_settings_icon ()
Prevent displaying of any icon.
Returns
string
Definition at line 279 of file class-settings.php.
app_settings_title ()
The Settings title.
Returns
string
Definition at line 271 of file class-settings.php.
create_app_menu ()
Add Settings link to GravityView menu.
Returns
void
If not multisite, always show. If multisite and the plugin is network activated, show; we need to register the submenu page for the Network Admin settings to work. If multisite and not network admin, we don't want the settings to show.
Since
1.7.6
Override whether to show the Settings menu on a per-blog basis.
Since
1.7.6
Parameters
bool $hide_if_network_activated Default: true
Definition at line 245 of file class-settings.php.
References GravityView_Plugin\is_network_activated().
current_user_can_any ($caps)
Prevent uninstall tab from being shown by returning false for the uninstall capability check.
Otherwise:
Parameters
array | string $caps
Returns
bool
Don't show uninstall tab
Definition at line 93 of file class-settings.php.
get_app_setting ($setting_name)
Make protected public public.
Backward compatibility with Redux
Definition at line 288 of file class-settings.php.
Referenced by app_settings_fields().
get_app_settings ()
Returns the currently saved plugin settings.
Different from GFAddon in two ways:
Makes protected method public
Use default settings if the original settings don't exist
public
Returns
array
Definition at line 315 of file class-settings.php.
References get_default_settings().
get_default_settings () private
Get the default settings for the plugin.
Merges previous settings created when using the Redux Framework
Returns
array Settings with defaults set
Definition at line 471 of file class-settings.php.
Referenced by app_settings_fields(), and get_app_settings().
static get_instance () static
Returns
GravityView_Settings
Definition at line 74 of file class-settings.php.
Referenced by GravityView_Migrate\get_redux_license_status(), and GravityView_Migrate\migrate_redux_settings().
get_license_handler ()
Allow public access to the GV_License_Handler class.
Since
1.7.4
Returns
GV_License_Handler
Definition at line 370 of file class-settings.php.
References $License_Handler.
get_posted_settings ()
When the settings are saved, make sure the license key matches the previously activated key.
Returns
array settings from parent::get_posted_settings(), with license_key_response and license_key_status potentially unset
Definition at line 490 of file class-settings.php.
get_required_indicator ($field)
Gets the required indicator Gets the markup of the required indicator symbol to highlight fields that are required.
Parameters
$field - The field meta.
Returns
string - Returns markup of the required indicator symbol
Definition at line 513 of file class-settings.php.
Referenced by single_setting_label().
static getSetting ($key) static
Get the setting for GravityView by name.
Parameters
string $key Option key to fetch
Returns
mixed
Definition at line 633 of file class-settings.php.
Referenced by GravityView_Admin_Views\enqueue_feedback_widget(), GravityView_Extension\get_license(), GravityView_Admin\no_conflict_scripts(), and GravityView_Admin\no_conflict_styles().
init_admin ()
Run actions when initializing admin.
Triggers the license key notice
Returns
void
Since
1.7.6
Definition at line 113 of file class-settings.php.
References _load_license_handler(), and license_key_notice().
init_ajax ()
Load license handler in admin-ajax.php.
Definition at line 146 of file class-settings.php.
References _load_license_handler().
license_key_notice ()
Display a notice if the plugin is inactive.
Returns
void
Definition at line 168 of file class-settings.php.
References $title, GravityView_Admin\add_notice(), and gravityview_is_admin_page().
Referenced by init_admin().
modify_app_settings_menu_title ($setting_tabs)
Change the settings page header title to "GravityView".
Parameters
$setting_tabs
Returns
array
Definition at line 136 of file class-settings.php.
set_field_error ($field, $error_message = '')
Make protected public public.
Definition at line 338 of file class-settings.php.
References $field.
settings_edd_license ($field, $echo = true) protected
Register the settings field for the EDD License field type.
Parameters
array $field
bool $echo Whether to echo the
Returns
string
Definition at line 349 of file class-settings.php.
References $field.
settings_save ($field, $echo = true)
Allow customizing the Save field parameters.
Parameters
array $field
bool $echo
Returns
string
Definition at line 422 of file class-settings.php.
References $field, $output, and settings_submit().
settings_submit ($field, $echo = true)
Definition at line 382 of file class-settings.php.
References $attributes, $field, $html, $name, and $value.
Referenced by settings_save().
single_setting_label ($field)
The same as the parent, except added support for field descriptions .
Parameters
$field array
Definition at line 444 of file class-settings.php.
References $field, and get_required_indicator().
styles ()
Register styles in the app admin page.
Returns
array
Definition at line 209 of file class-settings.php.
References GRAVITYVIEW_FILE, and GravityView_Plugin\version.
update_app_settings ($settings)
Updates app settings with the provided settings.
Same as the GVAddon, except it returns the value from update_option()
Parameters
array $settings - App settings to be saved
Returns
boolean False if value was not updated and true if value was updated.
Definition at line 329 of file class-settings.php.
Field Documentation
$_capabilities_uninstall = 'gravityview_gfaddon_uninstall' protected
Definition at line 36 of file class-settings.php.
$_min_gravityforms_version = GV_MIN_GF_VERSION protected
Definition at line 16 of file class-settings.php.
$_short_title = 'GravityView' protected
Definition at line 26 of file class-settings.php.
$_slug = 'gravityview' protected
Definition at line 31 of file class-settings.php.
$_title = 'GravityView' protected
Definition at line 21 of file class-settings.php.
$_version = GravityView_Plugin::version protected
Definition at line 12 of file class-settings.php.
$app_hook_suffix = 'gravityview'
Definition at line 41 of file class-settings.php.
$instance static private
Definition at line 51 of file class-settings.php.
$License_Handler private
Definition at line 46 of file class-settings.php.
Referenced by get_license_handler().
The documentation for this class was generated from the following file:
class-settings.php