GravityView: GVCommon Class Reference
GVCommon Class Reference
If this file is called directly, abort.
Static Public Member Functions
static array_merge_recursive_distinct (array &$array1, array &$array2)
array_merge_recursive does indeed merge arrays, but it converts values with duplicate keys to arrays rather than overwriting the value in the first array with the duplicate value in the second array, as array_merge does.
static calculate_get_entries_criteria ($passed_criteria=null, $form_ids=null)
Calculates the Search Criteria used on the self::get_entries / self::get_entry methods.
static check_entry_display ($entry)
Checks if a certain entry is valid according to the View search filters (specially the Adv Filters)
static generate_notice ($notice, $class= '')
Display updated/error notice.
static get_all_views ()
Get all existing Views.
static get_connected_views ($form_id)
Get the views for a particular form.
static get_directory_fields ($post_id)
Get the field configuration for the View.
static get_entries ($form_ids=null, $passed_criteria=null, &$total=null)
Retrieve entries given search, sort, paging criteria.
static get_entry ($entry_slug, $force_allow_ids=false)
Return a single entry object.
static get_entry_id_from_slug ($slug)
Get the entry ID from the entry slug, which may or may not be the entry ID.
static get_entry_ids ($form_id, $search_criteria=array())
Wrapper for the Gravity Forms GFFormsModel::search_lead_ids() method.
static get_entry_meta ($form_id, $only_default_column=true)
get extra fields from entry meta
static get_field ($form, $field_id)
Returns the field details array of a specific form given the field id.
static get_field_array ($field)
Return a Gravity Forms field array, whether using GF 1.9 or not.
static get_field_label ($form, $field_id)
Retrieve the label of a given field id (for a specific form)
static get_field_type ($form=null, $field_id= '')
Returns the GF Form field type for a certain field(id) of a form.
static get_form ($form_id)
Returns the form object for a given Form ID.
static get_form_fields ($form= '', $add_default_properties=false, $include_parent_field=true)
Return array of fields' id and label, for a given Form ID.
static get_form_from_entry_id ($entry_slug)
Get the form array for an entry based only on the entry ID.
static get_forms ()
Returns the list of available forms.
static get_link_html ($href= '', $anchor_text= '', $atts=array())
Generate an HTML anchor tag with a list of supported attributes.
static get_meta_form_id ($post_id)
static get_meta_template_id ($post_id)
static get_sortable_fields ($formid, $current= '')
Render dropdown (select) with the list of sortable fields from a form ID.
static get_sortable_fields_array ($formid, $blacklist=array('list', 'textarea'))
static get_template_setting ($post_id, $key)
Get the setting for a View.
static get_template_settings ($post_id)
Get all the settings for a View.
static get_users ($context= 'change_entry_creator')
Get WordPress users, by default limited to 750 users for performance reasons.
static gv_parse_str ($string, &$result)
Do the same than parse_str without max_input_vars limitation: Parses $string as if it were the query string passed via a URL and sets variables in the current scope.
static has_gravityview_shortcode ($post=null)
Check whether the post is GravityView.
static has_shortcode_r ($content, $tag= 'gravityview')
Placeholder until the recursive has_shortcode() patch is merged https://core.trac.wordpress.org/ticket/26343#comment:10.
static is_field_numeric ($form=null, $field= '')
Checks if the field type is a 'numeric' field type (e.g.
static js_encrypt ($content, $message= '')
Encrypt content using Javascript so that it's hidden when JS is disabled.
static matches_operation ($val1, $val2, $operation)
Wrapper for the GFFormsModel::matches_operation() method that adds additional comparisons, including: 'equals', 'greater_than_or_is', 'greater_than_or_equals', 'less_than_or_is', 'less_than_or_equals', and 'not_contains'.
Detailed Description
If this file is called directly, abort.
Definition at line 19 of file class-common.php.
Member Function Documentation
static array_merge_recursive_distinct (array & $array1, array & $array2) static
array_merge_recursive does indeed merge arrays, but it converts values with duplicate keys to arrays rather than overwriting the value in the first array with the duplicate value in the second array, as array_merge does.
See also
http://php.net/manual/en/function.array-merge-recursive.php
Since
1.5.3
Parameters
array $array1
array $array2
Returns
array
Author
Daniel <daniel (at) danielsmedegaardbuus (dot) dk>
Gabriel Sobrinho <gabriel (dot) sobrinho (at) gmail (dot) com>
Definition at line 1235 of file class-common.php.
References $value.
static calculate_get_entries_criteria ($passed_criteria = null, $form_ids = null) static
Calculates the Search Criteria used on the self::get_entries / self::get_entry methods.
Since
1.7.4
Parameters
null $passed_criteria array Input Criteria (search_criteria, sorting, paging)
null $form_ids array Gravity Forms form IDs
Returns
array|mixed|void
Runs Filter:
gravityview_search_operator Modify the search operator for the field (contains, is, isnot, etc)
Parameters
string $operator Existing search operator
array $filter array with key, value, operator, type keys
Prepare date formats to be in Gravity Forms DB format; $passed_criteria may include date formats incompatible with Gravity Forms.
Runs Filter:
gravityview_search_criteria Apply final criteria filter (Used by the Advanced Filter extension)
Parameters
array $criteria Search criteria used by GravityView
array $form_ids Forms to search
int $view_id ID of the view being used to search
Definition at line 374 of file class-common.php.
References $criteria, GravityView_frontend\getInstance(), and GravityView_View_Data\getInstance().
static check_entry_display ($entry) static
Checks if a certain entry is valid according to the View search filters (specially the Adv Filters)
See also
GFFormsModel::is_value_match()
Since
1.7.4
Parameters
array $entry Gravity Forms Entry object
Returns
bool|array Returns 'false' if entry is not valid according to the view search filters (Adv Filter)
Definition at line 659 of file class-common.php.
References $criteria, and $field.
static generate_notice ($notice, $class = '') static
Display updated/error notice.
Parameters
string $notice text/HTML of notice
string $class CSS class for notice (updated or error)
Returns
string
Definition at line 1276 of file class-common.php.
References $class.
Referenced by GravityView_Edit_Entry_Render\edit_entry_form(), GravityView_Edit_Entry_Render\user_can_edit_entry(), and GravityView_Edit_Entry_Render\user_can_edit_field().
static get_all_views () static
Get all existing Views.
Since
1.5.4
Returns
array Array of Views as WP_Post. Empty array if none found.
Runs Filter:
gravityview/get_all_views/params Modify the parameters sent to get all views.
Parameters
[in,out] array $params Array of parameters to pass to get_posts()
Definition at line 74 of file class-common.php.
Referenced by GravityView_Search_WP_Widget\form().
static get_connected_views ($form_id) static
Get the views for a particular form.
Parameters
int $form_id Gravity Forms form ID
Returns
array Array with view details
Definition at line 845 of file class-common.php.
References $form_id.
Referenced by gravityview_get_connected_views().
static get_directory_fields ($post_id) static
Get the field configuration for the View.
array(
[other zones]
'directory_list-title' => array(
[other fields]
'5372653f25d44' => array(
    'id' => string '9' (length=1)
    'label' => string 'Screenshots' (length=11)
    'show_label' => string '1' (length=1)
    'custom_label' => string '' (length=0)
    'custom_class' => string 'gv-gallery' (length=10)
        'only_loggedin' => string '0' (length=1)
    'only_loggedin_cap' => string 'read' (length=4)
)
    [other fields]
)
[other zones])
Parameters
int $post_id View ID
Returns
array Multi-array of fields with first level being the field zones. See code comment.
Definition at line 938 of file class-common.php.
Referenced by gravityview_get_directory_fields().
static get_entries ($form_ids = null, $passed_criteria = null, & $total = null) static
Retrieve entries given search, sort, paging criteria.
See also
GFAPI::get_entries()
GFFormsModel::get_field_filters_where() public
Parameters
int | array $form_ids The ID of the form or an array IDs of the Forms. Zero for all forms.
mixed $passed_criteria (default: null)
mixed &$total Optional. An output parameter containing the total number of entries. Pass a non-null value to generate the total count. (default: null)
Returns
mixed False: Error fetching entries. Array: Multi-dimensional array of Gravity Forms entry arrays
Runs Filter:
gravityview_entries Modify the array of entries returned to GravityView after it has been fetched from the cache or from GFAPI::get_entries().
Parameters
array | null $entries Array of entries as returned by the cache or by GFAPI::get_entries()
array $criteria The final search criteria used to generate the request to GFAPI::get_entries()
array $passed_criteria The original search criteria passed to GVCommon::get_entries()
int | null $total Optional. An output parameter containing the total number of entries. Pass a non-null value to generate
Definition at line 462 of file class-common.php.
References $criteria, $entries, and GravityView_Cache.
Referenced by GravityView_Recent_Entries_Widget\get_entries(), and gravityview_get_entries().
static get_entry ($entry_slug, $force_allow_ids = false) static
Return a single entry object.
Since 1.4, supports custom entry slugs. The way that GravityView fetches an entry based on the custom slug is by searching gravityview_unique_id meta. The $entry_slug is fetched by getting the current query var set by is_single_entry()
public
Parameters
mixed $entry_id
boolean $force_allow_ids Force the get_entry() method to allow passed entry IDs, even if the gravityview_custom_entry_slug_allow_id filter returns false.
Returns
object or false
Runs Filter:
gravityview_custom_entry_slug Whether to enable and use custom entry slugs.
Parameters
boolean True: Allow for slugs based on entry values. False: always use entry IDs (default)
Runs Filter:
gravityview_custom_entry_slug_allow_id When using a custom slug, allow access to the entry using the original slug (the Entry ID).
If disabled (default), only allow access to an entry using the custom slug value. (example: /entry/custom-slug/ NOT /entry/123/)
If enabled, you could access using the custom slug OR the entry id (example: /entry/custom-slug/ OR /entry/123/)
Parameters
boolean $custom_slug_id_access True: allow accessing the slug by ID; False: only use the slug passed to the method.
If we're using custom entry slugs, we do a meta value search instead of doing a straightup ID search.
Definition at line 529 of file class-common.php.
Referenced by GravityView_API\entry_link(), gravityview_get_entry(), and GravityView_frontend\setEntry().
static get_entry_id_from_slug ($slug) static
Get the entry ID from the entry slug, which may or may not be the entry ID.
Since
1.5.2
Parameters
string $slug The entry slug, as returned by GravityView_API::get_entry_slug()
Returns
int|null The entry ID, if exists; NULL if not
Definition at line 115 of file class-common.php.
static get_entry_ids ($form_id, $search_criteria = array()) static
Wrapper for the Gravity Forms GFFormsModel::search_lead_ids() method.
See also
GFEntryList::leads_page()
Parameters
int $form_id ID of the Gravity Forms form
Since
1.1.6
Returns
array Array of entry IDs
Definition at line 356 of file class-common.php.
References $form_id.
Referenced by gravityview_get_entry_ids().
static get_entry_meta ($form_id, $only_default_column = true) static
get extra fields from entry meta
Parameters
string $form_id (default: '')
Returns
array
Definition at line 332 of file class-common.php.
References $field, and $form_id.
Referenced by gravityview_get_entry_meta().
static get_field ($form, $field_id) static
Returns the field details array of a specific form given the field id.
public
Parameters
mixed $form
mixed $field_id
Returns
array|null Array: Gravity Forms field array; NULL: Gravity Forms GFFormsModel does not exist
Definition at line 772 of file class-common.php.
Referenced by gravityview_get_field().
static get_field_array ($field) static
Return a Gravity Forms field array, whether using GF 1.9 or not.
Since
1.7
Parameters
array | GF_Fields $field Gravity Forms field or array
Returns
array Array version of $field
Definition at line 52 of file class-common.php.
References $field.
Referenced by GravityView_Edit_Entry_Render\maybe_update_post_fields().
static get_field_label ($form, $field_id) static
Retrieve the label of a given field id (for a specific form)
public
Parameters
mixed $form
mixed $field_id
Returns
string
Definition at line 752 of file class-common.php.
References $field.
Referenced by gravityview_get_field_label().
static get_field_type ($form = null, $field_id = '') static
Returns the GF Form field type for a certain field(id) of a form.
Parameters
object $form Gravity Forms form
mixed $field_id Field ID or Field array
Returns
string field type
Definition at line 1027 of file class-common.php.
References $field.
Referenced by gravityview_get_field_type().
static get_form ($form_id) static
Returns the form object for a given Form ID.
public
Parameters
mixed $form_id
Returns
mixed False: no form ID specified or Gravity Forms isn't active. Array: Form returned from Gravity Forms
Definition at line 28 of file class-common.php.
References $form_id.
Referenced by GravityView_Admin_ApproveEntries\get_approved_column(), gravityview_get_form(), and GravityView_Search_WP_Widget\widget().
static get_form_fields ($form = '', $add_default_properties = false, $include_parent_field = true) static
Return array of fields' id and label, for a given Form ID.
public
Parameters
string | array $form_id (default: '') or $form object
Returns
array
In case of email/email confirmation, the input for email has the same id as the parent field
Since
1.8
1.8
Version 1.9
Since
1.7
1.8
Definition at line 168 of file class-common.php.
References $field.
Referenced by gravityview_get_form_fields().
static get_form_from_entry_id ($entry_slug) static
Get the form array for an entry based only on the entry ID.
Parameters
int | string $entry_slug Entry slug
Returns
array Gravity Forms form array
Definition at line 99 of file class-common.php.
Referenced by gravityview_get_form_from_entry_id().
static get_forms () static
Returns the list of available forms.
public
Parameters
mixed $form_id
Returns
array (id, title)
Definition at line 149 of file class-common.php.
References $forms.
Referenced by gravityview_get_forms().
static get_link_html ($href = '', $anchor_text = '', $atts = array()) static
Generate an HTML anchor tag with a list of supported attributes.
Supported attributes defined here 1.6 string $href URL of the link. string $anchor_text The text or HTML inside the anchor. This is not sanitized in the function. array $atts Attributes to be added to the anchor tag string HTML output of anchor link. If empty $href, returns NULL
Runs Filter:
gravityview/get_link/allowed_atts Modify the attributes that are allowed to be used in generating links
Parameters
array $allowed_atts Array of attributes allowed
Definition at line 1156 of file class-common.php.
References $href, $output, and $value.
Referenced by gravityview_get_link().
static get_meta_form_id ($post_id) static
Definition at line 857 of file class-common.php.
Referenced by gravityview_get_form_id(), and GravityView_Search_WP_Widget\widget().
static get_meta_template_id ($post_id) static
Definition at line 861 of file class-common.php.
Referenced by gravityview_get_template_id().
static get_sortable_fields ($formid, $current = '') static
Render dropdown (select) with the list of sortable fields from a form ID.
public
Parameters
int $formid Form ID
Returns
string html
Definition at line 950 of file class-common.php.
References $field, and $output.
Referenced by gravityview_get_sortable_fields().
static get_sortable_fields_array ($formid, $blacklist = array('list', 'textarea')) static
Parameters
int $formid Gravity Forms form ID
array $blacklist Field types to exclude
Since
TODO
Todo:
Get all fields, check if sortable dynamically
Returns
array
Runs Filter:
gravityview/common/sortable_fields Filter the sortable fields
Since
1.12
Parameters
array $fields Sub-set of GF form fields that are sortable
int $formid The Gravity Forms form ID that the fields are from
Definition at line 986 of file class-common.php.
References $field.
static get_template_setting ($post_id, $key) static
Get the setting for a View.
If the setting isn't set by the View, it returns the plugin default.
Parameters
int $post_id View ID
string $key Key for the setting
Returns
mixed|null Setting value, or NULL if not set.
Definition at line 898 of file class-common.php.
Referenced by GravityView_Edit_Entry\check_user_cap_edit_entry(), and gravityview_get_template_setting().
static get_template_settings ($post_id) static
Get all the settings for a View.
GravityView_View_Data::get_default_args() Parses the settings with the plugin defaults as backups.
Parameters
int $post_id View ID
Returns
array Associative array of settings with plugin defaults used if not set by the View
Definition at line 873 of file class-common.php.
References GravityView_View_Data\get_default_args().
Referenced by gravityview_get_template_settings().
static get_users ($context = 'change_entry_creator') static
Get WordPress users, by default limited to 750 users for performance reasons.
Parameters
string $context Where are we using this information (e.g. change_entry_creator, search_widget ..)
Returns
array Array of WP_User objects.
Runs Filter:
gravityview/get_users/{$context} There are issues with too many users using get_users() where it breaks the select. We try to keep it at a reasonable number.
$context is where are we using this information (e.g. change_entry_creator, search_widget ..)
Parameters
array $settings Settings array, with number key defining the # of users to display
Definition at line 1255 of file class-common.php.
Referenced by GravityView_Change_Entry_Creator\add_select(), and GravityView_Widget_Search\get_created_by_choices().
static gv_parse_str ($string, & $result) static
Do the same than parse_str without max_input_vars limitation: Parses $string as if it were the query string passed via a URL and sets variables in the current scope.
Parameters
$string array string to parse (not altered like in the original parse_str(), use the second parameter!)
$result array If the second parameter is present, variables are stored in this variable as array elements
Returns
bool true or false if $string is an empty string
Since
1.5.3
Author
rubo77 at https://gist.github.com/rubo77/6821632
Definition at line 1118 of file class-common.php.
Referenced by GravityView_Admin_Views\save_postdata().
static has_gravityview_shortcode ($post = null) static
Check whether the post is GravityView.
Check post type. Is it gravityview?
Check shortcode
Parameters
WP_Post $post WordPress post object
Returns
boolean True: yep, GravityView; No: not!
Definition at line 790 of file class-common.php.
References $post.
Referenced by has_gravityview_shortcode().
static has_shortcode_r ($content, $tag = 'gravityview') static
Placeholder until the recursive has_shortcode() patch is merged https://core.trac.wordpress.org/ticket/26343#comment:10.
Definition at line 808 of file class-common.php.
References $content.
Referenced by gravityview_has_shortcode_r().
static is_field_numeric ($form = null, $field = '') static
Checks if the field type is a 'numeric' field type (e.g.
to be used when sorting)
Parameters
int | array $form form ID or form array
int | array $field field key or field array
Returns
boolean
Runs Filter:
gravityview/common/numeric_types What types of fields are numeric?
Parameters
array $numeric_types Fields that are numeric. Default: [ number ]
Definition at line 1046 of file class-common.php.
References $field.
Referenced by GravityView_frontend\updateViewSorting().
static js_encrypt ($content, $message = '') static
Encrypt content using Javascript so that it's hidden when JS is disabled.
This is mostly used to hide email addresses from scraper bots.
Parameters
string $content Content to encrypt
string $message Message shown if Javascript is disabled
StandalonePHPEnkoder 1.7 string Content, encrypted
Runs Filter:
gravityview/phpenkoder/msg Modify the message shown when Javascript is disabled and an encrypted email field is displayed
Since
1.7
Parameters
string $message Existing message
string $content Content to encrypt
Definition at line 1079 of file class-common.php.
References $content, $enkoder, $output, and GRAVITYVIEW_DIR.
static matches_operation ($val1, $val2, $operation) static
Wrapper for the GFFormsModel::matches_operation() method that adds additional comparisons, including: 'equals', 'greater_than_or_is', 'greater_than_or_equals', 'less_than_or_is', 'less_than_or_equals', and 'not_contains'.
Since
1.13 You can define context, which displays/hides based on what's being displayed (single, multiple, edit)
GFFormsModel::matches_operation 1.7.5 string $val1 Left side of comparison string $val2 Right side of comparison string $operation Type of comparison bool True: matches, false: not matches
Definition at line 598 of file class-common.php.
References $value, and gravityview_get_context().
Referenced by GVLogic_Shortcode\set_is_match().
The documentation for this class was generated from the following file:
class-common.php