GravityView: GravityView_Admin_Duplicate_View Class Reference
GravityView_Admin_Duplicate_View Class Reference
Public Member Functions
__construct ()
connected_form_links ($links=array(), $form=array())
Add Duplicate View link to the Data Source metabox.
copy_view_meta_info ($new_id, $post)
Copy the meta information of a post to another View.
create_duplicate ($post, $status= '')
Create a duplicate from a View $post.
current_user_can_copy ($post)
Test if the user is allowed to copy Views.
get_clone_view_link ($id=0, $context= 'display', $draft=true)
Retrieve duplicate post link for post.
is_all_views_page ()
Is the current screen the All Views screen?
make_duplicate_link_row ($actions, $post)
Add the link to action list for post_row_actions.
save_as_new_view ($status= '')
This function calls the creation of a new copy of the selected post (by default preserving the original publish status) then redirects to the post list.
save_as_new_view_draft ()
This function calls the creation of a new copy of the selected post (as a draft) then redirects to the edit post screen.
Detailed Description
Definition at line 12 of file class-gravityview-admin-duplicate-view.php.
Constructor & Destructor Documentation
__construct ()
Connect actions to functions
Definition at line 15 of file class-gravityview-admin-duplicate-view.php.
Member Function Documentation
connected_form_links ($links = array(), $form = array())
Add Duplicate View link to the Data Source metabox.
Parameters
array $links Array of link HTML to display in the Data Source metabox
array $form Gravity Forms form array
Returns
array If it's the All Views page, return unedited. Otherwise, add a link to create cloned draft of View
Definition at line 50 of file class-gravityview-admin-duplicate-view.php.
References $post, is_all_views_page(), and make_duplicate_link_row().
copy_view_meta_info ($new_id, $post)
Copy the meta information of a post to another View.
Since
1.6
Definition at line 184 of file class-gravityview-admin-duplicate-view.php.
References $post.
create_duplicate ($post, $status = '')
Create a duplicate from a View $post.
Since
1.6
The default status for a new View. Return empty for the new View to inherit existing View status
Parameters
string|null If string, the status to set for the new View. If empty, use existing View status.
WP_Post $post View being cloned
When copying the View, should the date also be copied?
Parameters
boolean
WP_Post $post View being cloned
Modify View configuration before creating the duplicated View.
Parameters
array $new_view Array of settings to be passed to wp_insert_post()
WP_Post $post View being cloned
Definition at line 100 of file class-gravityview-admin-duplicate-view.php.
References $post.
Referenced by save_as_new_view().
current_user_can_copy ($post)
Test if the user is allowed to copy Views.
Since
1.6
Definition at line 82 of file class-gravityview-admin-duplicate-view.php.
References $post.
Referenced by get_clone_view_link(), and make_duplicate_link_row().
get_clone_view_link ($id = 0, $context = 'display', $draft = true)
Retrieve duplicate post link for post.
Since
1.6
Parameters
int $id Optional. Post ID.
string $context Optional, default to display. How to write the '&', defaults to '&'.
string $draft Optional, default to true
Returns
string
Definition at line 246 of file class-gravityview-admin-duplicate-view.php.
References current_user_can_copy().
Referenced by make_duplicate_link_row().
is_all_views_page ()
Is the current screen the All Views screen?
Returns
bool
Definition at line 71 of file class-gravityview-admin-duplicate-view.php.
Referenced by connected_form_links(), and make_duplicate_link_row().
make_duplicate_link_row ($actions, $post)
Add the link to action list for post_row_actions.
Since
1.6
Definition at line 210 of file class-gravityview-admin-duplicate-view.php.
References $post, current_user_can_copy(), get_clone_view_link(), gravityview_get_link(), and is_all_views_page().
Referenced by connected_form_links().
save_as_new_view ($status = '')
This function calls the creation of a new copy of the selected post (by default preserving the original publish status) then redirects to the post list.
Since
1.6
Definition at line 293 of file class-gravityview-admin-duplicate-view.php.
References $post, and create_duplicate().
Referenced by save_as_new_view_draft().
save_as_new_view_draft ()
This function calls the creation of a new copy of the selected post (as a draft) then redirects to the edit post screen.
Since
1.6
Definition at line 283 of file class-gravityview-admin-duplicate-view.php.
References save_as_new_view().
The documentation for this class was generated from the following file:
class-gravityview-admin-duplicate-view.php