GravityView: GravityView_Field Class Reference
GravityView_Field Class Reference
Modify field settings by extending this class.
Public Member Functions
__construct ()
add_field_support ($key= '', &$field_options)
field_options ($field_options, $template_id, $field_id, $context, $input_type)
Tap in here to modify field options.
Data Fields
$name
Private Member Functions
field_support_options ()
Detailed Description
Modify field settings by extending this class.
Definition at line 6 of file class.field.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 15 of file class.field.php.
Member Function Documentation
add_field_support ($key = '', & $field_options)
Definition at line 65 of file class.field.php.
References field_support_options().
Referenced by GravityView_Field_Date\field_options(), GravityView_Field_Time\field_options(), GravityView_Field_Post_Title\field_options(), GravityView_Field_Post_Tags\field_options(), GravityView_Field_Post_Image\field_options(), GravityView_Field_Entry_Date\field_options(), GravityView_Field_Post_Content\field_options(), GravityView_Field_Post_Category\field_options(), and GravityView_Field_Post_ID\field_options().
field_options ($field_options, $template_id, $field_id, $context, $input_type)
Tap in here to modify field options.
Here's an example:
$field_options['name_display'] = array(
    'type' => 'select',
    'label' => __( 'User Format', 'gravityview' ),
    'desc' => __( 'How should the User information be displayed?', 'gravityview'),
    'choices' => array(
        array(
        'value' => 'display_name',
        'label' => __('Display Name (Example: "Ellen Ripley")', 'gravityview'),
    ),
    array(
        'value' => 'user_login',
        'label' => __('Username (Example: "nostromo")', 'gravityview')
    ),
     'value' => 'display_name'
);
Parameters
[type] $field_options [description]
[type] $template_id [description]
[type] $field_id [description]
[type] $context [description]
[type] $input_type [description]
Returns
[type] [description]
Definition at line 106 of file class.field.php.
field_support_options () private
Runs Filter:
gravityview_date_format Override the date format with a PHP date format
Parameters
[in,out] null | string $date_format Date Format (default: null)
Runs Filter:
gravityview_field_support_options Modify the settings that a field supports
Parameters
array $options Options multidimensional array with each key being the input name, with each array setting having type, label, desc and value (default values) keys
Definition at line 21 of file class.field.php.
Referenced by add_field_support().
Field Documentation
$name
Definition at line 13 of file class.field.php.
The documentation for this class was generated from the following file:
class.field.php