GravityView: connector-functions.php File Reference
connector-functions.php File Reference
Namespaces
GravityView
GPL2+
Functions
get_gravityview ($view_id= '', $atts=array())
Theme function to get a GravityView view.
gravityview_get_connected_views ($form_id)
Get the views for a particular form.
gravityview_get_directory_fields ($post_id)
Get the field configuration for the View.
gravityview_get_entries ($form_ids=null, $passed_criteria=null, &$total=null)
Retrieve entries given search, sort, paging criteria.
gravityview_get_entry ($entry_slug, $force_allow_ids=false)
Return a single entry object.
gravityview_get_entry_ids ($form_id, $search_criteria=array())
Wrapper for the Gravity Forms GFFormsModel::search_lead_ids() method.
gravityview_get_entry_meta ($form_id, $only_default_column=true)
get extra fields from entry meta
gravityview_get_field ($form, $field_id)
Returns the field details array of a specific form given the field id.
gravityview_get_field_label ($form, $field_id)
Retrieve the label of a given field id (for a specific form)
gravityview_get_field_type ($form=null, $field_id= '')
Returns the GF Form field type for a certain field(id) of a form.
gravityview_get_form ($form_id)
Returns the form object for a given Form ID.
gravityview_get_form_fields ($form= '', $add_default_properties=false, $include_parent_field=true)
Return array of fields' id and label, for a given Form ID.
gravityview_get_form_from_entry_id ($entry_slug)
Get the form array for an entry based only on the entry ID.
gravityview_get_form_id ($view_id)
Get the connected form ID from a View ID.
gravityview_get_forms ()
Returns the list of available forms.
gravityview_get_sortable_fields ($formid, $current= '')
Render dropdown (select) with the list of sortable fields from a form ID.
gravityview_get_template_id ($post_id)
gravityview_get_template_setting ($post_id, $key)
Get the setting for a View.
gravityview_get_template_settings ($post_id)
Get all the settings for a View.
gravityview_has_shortcode_r ($content, $tag= 'gravityview')
Placeholder until the recursive has_shortcode() patch is merged https://core.trac.wordpress.org/ticket/26343#comment:10.
gravityview_is_single_entry ()
Theme function to identify if it is a Single Entry View.
has_gravityview_shortcode ($post=NULL)
Check whether the post is GravityView.
the_gravityview ($view_id= '', $atts=array())
Theme function to render a GravityView view.
Function Documentation
get_gravityview ($view_id = '', $atts = array())
Theme function to get a GravityView view.
public
Parameters
string $view_id (default: '')
array $atts (default: array())
Returns
string HTML of the output. Empty string if $view_id is empty.
Definition at line 271 of file connector-functions.php.
References $view_id, GravityView_View_Data\get_default_args(), GravityView_frontend\getInstance(), and GravityView_View_Data\getInstance().
Referenced by the_gravityview().
gravityview_get_connected_views ($form_id)
Get the views for a particular form.
Parameters
int $form_id Gravity Forms form ID
Returns
array Array with view details
Definition at line 163 of file connector-functions.php.
References $form_id, and GVCommon\get_connected_views().
Referenced by GravityView_Admin_Views\gform_toolbar_menu(), and GravityView_Admin_ApproveEntries\show_approve_entry_column().
gravityview_get_directory_fields ($post_id)
Get the field configuration for the View.
array(
[other zones]
'directory_list-title' => array(
[other fields]
'5372653f25d44' => array(
    'id' => string '9' (length=1)
    'label' => string 'Screenshots' (length=11)
    'show_label' => string '1' (length=1)
    'custom_label' => string '' (length=0)
    'custom_class' => string 'gv-gallery' (length=10)
        'only_loggedin' => string '0' (length=1)
    'only_loggedin_cap' => string 'read' (length=4)
)
    [other fields]
)
[other zones])
Parameters
int $post_id View ID
Returns
array Multi-array of fields with first level being the field zones. See code comment.
Definition at line 236 of file connector-functions.php.
References GVCommon\get_directory_fields().
Referenced by GravityView_View_Data\get_fields(), GravityView_Admin_Views\render_directory_active_areas(), and GravityView_Admin_Metaboxes\render_shortcode_hint().
gravityview_get_entries ($form_ids = null, $passed_criteria = null, & $total = null)
Retrieve entries given search, sort, paging criteria.
See also
GFAPI::get_entries()
GFFormsModel::get_field_filters_where() public
Parameters
int | array $form_ids The ID of the form or an array IDs of the Forms. Zero for all forms.
mixed $passed_criteria (default: null)
mixed &$total (default: null)
Returns
mixed False: Error fetching entries. Array: Multi-dimensional array of Gravity Forms entry arrays
Definition at line 93 of file connector-functions.php.
References GVCommon\get_entries().
gravityview_get_entry ($entry_slug, $force_allow_ids = false)
Return a single entry object.
Since 1.4, supports custom entry slugs. The way that GravityView fetches an entry based on the custom slug is by searching gravityview_unique_id meta. The $entry_slug is fetched by getting the current query var set by is_single_entry()
public
Parameters
mixed $entry_id
boolean $force_allow_ids Force the get_entry() method to allow passed entry IDs, even if the gravityview_custom_entry_slug_allow_id filter returns false.
Returns
object or false
Definition at line 107 of file connector-functions.php.
References GVCommon\get_entry().
Referenced by GravityView_Edit_Entry_Render\get_entry(), and GravityView_Delete_Entry\process_delete().
gravityview_get_entry_ids ($form_id, $search_criteria = array())
Wrapper for the Gravity Forms GFFormsModel::search_lead_ids() method.
See also
GFEntryList::leads_page()
Parameters
int $form_id ID of the Gravity Forms form
Since
1.1.6
Returns
array Array of entry IDs
Definition at line 77 of file connector-functions.php.
References $form_id, and GVCommon\get_entry_ids().
Referenced by GravityView_Admin_ApproveEntries\process_bulk_action().
gravityview_get_entry_meta ($form_id, $only_default_column = true)
get extra fields from entry meta
Parameters
string $form_id (default: '')
Returns
array
Definition at line 65 of file connector-functions.php.
References $form_id, and GVCommon\get_entry_meta().
Referenced by GravityView_Admin_Views\get_available_fields().
gravityview_get_field ($form, $field_id)
Returns the field details array of a specific form given the field id.
public
Parameters
mixed $form
mixed $field_id
Returns
array
Definition at line 132 of file connector-functions.php.
References GVCommon\get_field().
Referenced by GravityView_API\field_value(), GravityView_Migrate\get_search_fields(), GravityView_Widget_Search\get_search_filter_details(), and GravityView_Widget_Search\prepare_field_filter().
gravityview_get_field_label ($form, $field_id)
Retrieve the label of a given field id (for a specific form)
public
Parameters
mixed $form
mixed $field_id
Returns
string
Definition at line 119 of file connector-functions.php.
References GVCommon\get_field_label().
gravityview_get_field_type ($form = null, $field_id = '')
Returns the GF Form field type for a certain field(id) of a form.
Parameters
object $form Gravity Forms form
mixed $field_id Field ID or Field array
Returns
string field type
Definition at line 258 of file connector-functions.php.
References GVCommon\get_field_type().
gravityview_get_form ($form_id)
Returns the form object for a given Form ID.
public
Parameters
mixed $form_id
Returns
mixed False: no form ID specified or Gravity Forms isn't active. Array: Form returned from Gravity Forms
Definition at line 24 of file connector-functions.php.
References $form_id, and GVCommon\get_form().
Referenced by GravityView_Admin_Views\add_connected_form_column_content(), GravityView_View_Data\add_view(), GravityView_Admin_Views\get_connected_form_links(), GravityView_Migrate\get_search_fields(), and GravityView_Admin_Metaboxes\render_merge_tags_scripts().
gravityview_get_form_fields ($form = '', $add_default_properties = false, $include_parent_field = true)
Return array of fields' id and label, for a given Form ID.
public
Parameters
string | array $form_id (default: '') or $form object
Returns
array
Definition at line 56 of file connector-functions.php.
References GVCommon\get_form_fields().
Referenced by GravityView_Admin_Views\get_available_fields(), and GravityView_Widget_Search\render_searchable_fields().
gravityview_get_form_from_entry_id ($entry_slug)
Get the form array for an entry based only on the entry ID.
Parameters
int | string $entry_slug Entry slug
Returns
array Gravity Forms form array
Definition at line 34 of file connector-functions.php.
References GVCommon\get_form_from_entry_id().
gravityview_get_form_id ($view_id)
Get the connected form ID from a View ID.
Parameters
int $view_id ID of the View you want the form of
Returns
int
Definition at line 174 of file connector-functions.php.
References $view_id, and GVCommon\get_meta_form_id().
Referenced by GravityView_Admin_Views\add_connected_form_column_content(), GravityView_View_Data\add_view(), GravityView_Recent_Entries_Widget\ajax_get_view_merge_tag_data(), GravityView_Admin_Metaboxes\get_data_source_header(), GravityView_Migrate\get_search_fields(), GravityView_Widget_Search\get_searchable_fields(), GravityView_Admin_Add_Shortcode\get_sortable_fields(), GravityView_frontend\insert_view_in_content(), GravityView_Admin_Views\render_active_areas(), GravityView_Admin_Metaboxes\render_view_configuration_metabox(), GravityView_Delete_Entry_Shortcode\shortcode(), and GravityView_Edit_Entry_Shortcode\shortcode().
gravityview_get_forms ()
Returns the list of available forms.
public
Parameters
mixed $form_id
Returns
array (id, title)
Definition at line 45 of file connector-functions.php.
References GVCommon\get_forms().
Referenced by GravityView_Admin_ApproveEntries\add_scripts_and_styles().
gravityview_get_sortable_fields ($formid, $current = '')
Render dropdown (select) with the list of sortable fields from a form ID.
public
Parameters
int $formid Form ID
Returns
string html
Definition at line 247 of file connector-functions.php.
References GVCommon\get_sortable_fields().
Referenced by GravityView_Admin_Add_Shortcode\get_sortable_fields(), and GravityView_Ajax\get_sortable_fields().
gravityview_get_template_id ($post_id)
Definition at line 178 of file connector-functions.php.
References GVCommon\get_meta_template_id().
Referenced by GravityView_View_Data\add_view(), and GravityView_Admin_Metaboxes\render_view_configuration_metabox().
gravityview_get_template_setting ($post_id, $key)
Get the setting for a View.
If the setting isn't set by the View, it returns the plugin default.
Parameters
int $post_id View ID
string $key Key for the setting
Returns
mixed|null Setting value, or NULL if not set.
Definition at line 202 of file connector-functions.php.
References GVCommon\get_template_setting().
Referenced by GravityView_Admin_Add_Shortcode\get_sortable_fields().
gravityview_get_template_settings ($post_id)
Get all the settings for a View.
GravityView_View_Data::get_default_args() Parses the settings with the plugin defaults as backups.
Parameters
int $post_id View ID
Returns
array Associative array of settings with plugin defaults used if not set by the View
Definition at line 189 of file connector-functions.php.
References GVCommon\get_template_settings().
Referenced by GravityView_View_Data\add_view(), GravityView_Recent_Entries_Widget\get_entries(), and GravityView_Admin_Metaboxes\render_view_settings_metabox().
gravityview_has_shortcode_r ($content, $tag = 'gravityview')
Placeholder until the recursive has_shortcode() patch is merged https://core.trac.wordpress.org/ticket/26343#comment:10.
Definition at line 154 of file connector-functions.php.
References $content, and GVCommon\has_shortcode_r().
Referenced by GravityView_frontend\parse_content(), GravityView_View_Data\parse_post_content(), and GravityView_Connector_Functions_Test\test_gravityview_has_shortcode_r().
gravityview_is_single_entry ()
Theme function to identify if it is a Single Entry View.
Since
1.5.4
Returns
bool|string False if not, single entry slug if true
Definition at line 303 of file connector-functions.php.
References GravityView_frontend\is_single_entry().
has_gravityview_shortcode ($post = NULL)
Check whether the post is GravityView.
Check post type. Is it gravityview?
Check shortcode
Parameters
WP_Post $post WordPress post object
Returns
boolean True: yep, GravityView; No: not!
Definition at line 146 of file connector-functions.php.
References $post, and GVCommon\has_gravityview_shortcode().
Referenced by GravityView_Widget\add_shortcode().
the_gravityview ($view_id = '', $atts = array())
Theme function to render a GravityView view.
public
Parameters
string $view_id (default: '')
array $atts (default: array())
Returns
void
Definition at line 292 of file connector-functions.php.
References $view_id, and get_gravityview().
Referenced by GravityView_oEmbed\generate_entry_output().