GravityView: gquiz_percent.php File Reference
gquiz_percent.php File Reference
Namespaces
GravityView
GPL2+
Variables
$field = GravityView_View::getInstance()->getCurrentField()
if(empty($field['value'])) $format = apply_filters('gravityview/field/quiz_percent/format', '%d%%')
Modify the format of the display of the field.
Variable Documentation
$field = GravityView_View::getInstance()->getCurrentField()
Definition at line 9 of file gquiz_percent.php.
if (empty($field['value'])) $format = apply_filters('gravityview/field/quiz_percent/format', '%d%%')
Modify the format of the display of the field.
Notice the double %%, this prints a literal '' character
See also
http://php.net/manual/en/function.sprintf.php For formatting guide
Parameters
string $format Format passed to printf() function. Default d%%, which prints as "{number}%"
Definition at line 25 of file gquiz_percent.php.
Referenced by GravityView_API\field_value(), GravityView_API\field_width(), GravityView_Widget_Search\get_date_field_format(), and GravityView_Widget_Search\get_formatted_date().