GravityView: helper-functions.php File Reference
helper-functions.php File Reference
Functions
gravityview_get_floaty ()
Get an image of our intrepid explorer friend.
gravityview_get_permalink_query_args ($id=0)
Get get_permalink() without the home_url() prepended to it.
gravityview_is_not_empty_string ($mixed= '')
Functions that don't require GravityView or Gravity Forms API access but are used in the plugin to extend PHP and WP functions.
gravityview_number_format ($number, $decimals= '')
Intelligently format a number.
gravityview_ob_include ($file_path)
Get the contents of a file using include() and ob_start()
gravityview_sanitize_html_class ($classes)
sanitize_html_class doesn't handle spaces (multiple classes).
gravityview_strip_whitespace ($string)
Replace multiple newlines, tabs, and spaces with a single space.
Function Documentation
gravityview_get_floaty ()
Get an image of our intrepid explorer friend.
Since
1.12
Returns
string HTML image tag with floaty's cute mug on it
Definition at line 108 of file helper-functions.php.
References $class, and GRAVITYVIEW_FILE.
Referenced by GravityView_Admin_Notices\admin_notice(), and GravityView_Admin\get_floaty().
gravityview_get_permalink_query_args ($id = 0)
Get get_permalink() without the home_url() prepended to it.
get_permalink() does a lot of good stuff: it gets the correct permalink structure for custom post types, pages, posts, etc. Instead of using ?p={id}, ?page_id={id}, or ?p={id}&post_type={post_type}, by using get_permalink(), we can use ?p=slug or ?gravityview={slug}
We could do this in a cleaner fashion, but this prevents a lot of code duplication, checking for URL structure, etc.
Parameters
int | WP_Post $id Optional. Post ID or post object. Default current post.
Returns
array URL args, if exists. Empty array if not.
Definition at line 35 of file helper-functions.php.
Referenced by GravityView_Widget_Search\add_no_permalink_fields().
gravityview_is_not_empty_string ($mixed = '')
Functions that don't require GravityView or Gravity Forms API access but are used in the plugin to extend PHP and WP functions.
Since
1.12 Check whether a variable is not an empty string
See also
/templates/fields/product.php Used to check whether the product array is empty or not
Since
1.12
Parameters
mixed $mixed Variable to check
Returns
bool true: $mixed is not an empty string; false: $mixed is an empty string
Definition at line 18 of file helper-functions.php.
gravityview_number_format ($number, $decimals = '')
Intelligently format a number.
If you don't define the number of decimal places, then it will use the existing number of decimal places. This is done in a way that respects the localization of the site.
If you do define decimals, it uses number_format_i18n()
See also
number_format_i18n()
Since
1.13
Parameters
int | float | string | double $number A number to format
int | string $decimals Optional. Precision of the number of decimal places. Default '' (use existing number of decimals)
Returns
string Converted number in string format.
Calculate the position of the decimal point in the number
See also
http://stackoverflow.com/a/2430144/480856
Definition at line 138 of file helper-functions.php.
gravityview_ob_include ($file_path)
Get the contents of a file using include() and ob_start()
Since
1.13
Parameters
string $file_path Full path to a file
Returns
string Included file contents
Definition at line 93 of file helper-functions.php.
Referenced by GravityView_Edit_Entry_Render\edit_entry_form().
gravityview_sanitize_html_class ($classes)
sanitize_html_class doesn't handle spaces (multiple classes).
We remedy that. sanitize_html_class
Parameters
string | array $classes Text or arrray of classes to sanitize
Returns
string Sanitized CSS string
Definition at line 56 of file helper-functions.php.
Referenced by GravityView_Admin_Notices\admin_notice(), GravityView_API\field_class(), GravityView_Widget_Search\get_search_class(), gv_container_class(), GravityView_Edit_Entry_Render\merge_field_properties(), GravityView_Widget_Page_Links\render_frontend(), GravityView_Widget_Pagination_Info\render_frontend(), GravityView_Widget_Custom_Content\render_frontend(), and GravityView_API_Test\test_gravityview_sanitize_html_class().
gravityview_strip_whitespace ($string)
Replace multiple newlines, tabs, and spaces with a single space.
Since
1.13
Parameters
string $string String to strip whitespace from
Returns
string Stripped string!
Definition at line 79 of file helper-functions.php.
Referenced by GravityView_Edit_Entry_Render\edit_entry_form().