GravityView: custom.php File Reference
templates/fields/custom.php File Reference
Namespaces
GravityView
GPL2+
Variables
if(empty($field_settings['content'])) $content = GravityView_API::replace_variables($field_settings['content'], $form, $entry)
$field_settings ['content'] = apply_filters('gravityview/fields/custom/content_before', $field_settings['content'])
Allow for custom content behavior before merge tags replacement.
$gravityview_view = GravityView_View::getInstance()
Variable Documentation
if (!empty($field_settings['wpautop'])) $content = GravityView_API::replace_variables($field_settings['content'], $form, $entry)
Since
1.6.2
Definition at line 36 of file templates/fields/custom.php.
Referenced by StandalonePHPEnkoder\enkode(), StandalonePHPEnkoder\enkodeMailto(), GravityView_Field_FileUpload\get_files_array(), gravityview_has_shortcode_r(), GVCommon\has_shortcode_r(), GravityView_frontend\insert_view_in_content(), GVCommon\js_encrypt(), WXR_Parser_SimpleXML\parse(), GravityView_View_Data\parse_post_content(), GravityView_Widget_Custom_Content\render_frontend(), GravityView_Widget\render_shortcode(), GravityView_Cache\set(), GravityView_Delete_Entry_Shortcode\shortcode(), and GravityView_Edit_Entry_Shortcode\shortcode().
$field_settings['content'] = apply_filters('gravityview/fields/custom/content_before', $field_settings['content'])
Allow for custom content behavior before merge tags replacement.
Since
1.6.2
Definition at line 26 of file templates/fields/custom.php.
Referenced by GravityView_API\entry_link_html(), GravityView_API\field_value(), and GravityView_Field_FileUpload\get_files_array().
$gravityview_view = GravityView_View::getInstance()
Definition at line 10 of file templates/fields/custom.php.