<?php
/**
 * Display the Poll widget
 *
 * @see ../class-gravityview-widget-poll.php
 */

$gravityview_view = GravityView_View::getInstance();

/**
 * Merge tag is already generated by the class.
 * Access array of settings to generate your own using the $gravityview_view->poll_settings variable.
 */
$merge_tag = $gravityview_view->poll_merge_tag;

echo GFCommon::replace_variables( $merge_tag, $gravityview_view->getForm(), array( 'id' => 0 ) );