GravityView: GravityView_Widget_Poll Class Reference
GravityView_Widget_Poll Class Reference
Widget to add custom content.
Public Member Functions
__construct ()
add_template_path ($file_paths)
Include this extension templates path.
get_frontend_settings ($widget_settings)
Get the display settings for the Poll widget.
pre_render_frontend ()
render_frontend ($widget_args, $content= '', $context= '')
Render the widget.
Public Member Functions inherited from GravityView_Widget
add_shortcode ($run_on_singular=true)
Add $this->shortcode_name shortcode to output self::render_frontend()
assign_widget_options ($options=array(), $template= '', $widget= '')
Assign template specific field options.
get_setting ($key)
Get a setting by the setting key.
get_settings ()
Get the widget settings.
get_widget_id ()
maybe_do_shortcode ($text, $widget=NULL)
Do shortcode if the Widget's shortcode exists.
pre_render_frontend ()
General validations when rendering the widget.
register_widget ($widgets)
Register widget to become available in admin.
render_frontend ($widget_args, $content= '', $context= '')
Frontend logic.
render_shortcode ($atts, $content= '', $context= '')
Protected Attributes
$show_on_single = false
Protected Attributes inherited from GravityView_Widget
$defaults = array()
$settings = array()
$shortcode_name
$widget_description = ''
$widget_id = ''
$widget_label = ''
$widget_subtitle = ''
Private Member Functions
enqueue_scripts_and_styles ()
Load the scripts and styles needed for the display of the poll widget.
Additional Inherited Members
Protected Member Functions inherited from GravityView_Widget
get_default_settings ()
Define general widget settings.
Detailed Description
Widget to add custom content.
Since
1.8
Definition at line 10 of file class-gravityview-widget-poll.php.
Constructor & Destructor Documentation
__construct ()
Todo:
add support for specifying poll field to display (via AJAX in field settings)
Since
1.8
Definition at line 22 of file class-gravityview-widget-poll.php.
References GravityView_Widget\$settings.
Member Function Documentation
add_template_path ($file_paths)
Include this extension templates path.
Since
1.8
Parameters
array $file_paths List of template paths ordered
Definition at line 72 of file class-gravityview-widget-poll.php.
enqueue_scripts_and_styles () private
Load the scripts and styles needed for the display of the poll widget.
Since
1.8
Definition at line 87 of file class-gravityview-widget-poll.php.
Referenced by render_frontend().
get_frontend_settings ($widget_settings)
Get the display settings for the Poll widget.
Parameters
array $widget_settings Settings for the Poll widget
Returns
array Final poll widget settings
Runs Filter:
gravityview/widget/poll/settings Modify display settings for the poll widget
Since
1.8
Parameters
array $settings Settings with field, style, percentages and counts keys
Definition at line 133 of file class-gravityview-widget-poll.php.
References GravityView_Widget\$settings.
Referenced by render_frontend().
pre_render_frontend ()
Since
1.8
Definition at line 103 of file class-gravityview-widget-poll.php.
References GravityView_View\getInstance().
Referenced by render_frontend().
render_frontend ($widget_args, $content = '', $context = '')
Render the widget.
See also
https://www.gravityhelp.com/documentation/article/polls-add-on/
Since
1.8
Definition at line 161 of file class-gravityview-widget-poll.php.
References $gravityview_view, $merge_tag, GravityView_Widget\$settings, enqueue_scripts_and_styles(), get_frontend_settings(), GravityView_View\getInstance(), and pre_render_frontend().
Field Documentation
$show_on_single = false protected
Definition at line 16 of file class-gravityview-widget-poll.php.
The documentation for this class was generated from the following file:
class-gravityview-widget-poll.php