GravityView: Gamajo_Template_Loader Class Reference
Gamajo_Template_Loader Class Reference
Public Member Functions
get_template_part ($slug, $name=null, $load=true)
Retrieve a template part.
locate_template ($template_names, $load=false, $require_once=true)
Retrieve the name of the highest priority template file that exists.
Protected Member Functions
get_template_file_names ($slug, $name)
Given a slug and optional name, create the file names of templates.
get_template_paths ()
Return a list of paths to check for template locations.
get_templates_dir ()
Return the path to the templates directory in this plugin.
Protected Attributes
$filter_prefix = 'your_plugin'
Prefix for filter names.
$plugin_directory = YOUR_PLUGIN_DIR
Reference to the root directory path of this plugin.
$plugin_template_directory = 'templates'
Directory name where templates are found in this plugin.
$theme_template_directory = 'your-plugin'
Directory name where custom templates for this plugin should be found in the theme.
Detailed Description
Definition at line 23 of file class-gamajo-template-loader.php.
Member Function Documentation
get_template_file_names ($slug, $name) protected
Given a slug and optional name, create the file names of templates.
Since
1.0.0
Parameters
string $slug
string $name
Returns
array
Allow template choices to be filtered.
The resulting array should be in the order of most specific first, to least specific last. e.g. 0 => recipe-instructions.php, 1 => recipe.php
Since
1.0.0
Parameters
array $templates Names of template files that should be looked for, for given slug and name.
string $slug Template slug.
string $name Template name.
Definition at line 100 of file class-gamajo-template-loader.php.
References $name, and $templates.
Referenced by get_template_part().
get_template_part ($slug, $name = null, $load = true)
Retrieve a template part.
Since
1.0.0
Gamajo_Template_Loader::get_template_possble_parts() Create file names of templates. Gamajo_Template_Loader::locate_template() Retrieve the name of the highest priority template file that exists.
Parameters
string $slug
string $name Optional. Default null.
bool $load Optional. Default true.
Returns
string
Definition at line 79 of file class-gamajo-template-loader.php.
References $name, $templates, get_template_file_names(), and locate_template().
Referenced by GravityView_View\render().
get_template_paths () protected
Return a list of paths to check for template locations.
Default is to check in a child theme (if relevant) before a parent theme, so that themes which inherit from a parent theme can just overload one file. If the template is not found in either of those, it looks in the theme-compat folder last.
Since
1.0.0
Returns
mixed|void
Allow ordered list of template paths to be amended.
Since
1.0.0
Parameters
array $var Default is directory in child theme at index 1, parent theme at 10, and plugin at 100.
Definition at line 180 of file class-gamajo-template-loader.php.
References get_templates_dir().
Referenced by locate_template().
get_templates_dir () protected
Return the path to the templates directory in this plugin.
May be overridden in subclass.
Since
1.0.0
Returns
string
Definition at line 217 of file class-gamajo-template-loader.php.
References $plugin_template_directory.
Referenced by get_template_paths().
locate_template ($template_names, $load = false, $require_once = true)
Retrieve the name of the highest priority template file that exists.
Searches in the STYLESHEETPATH before TEMPLATEPATH so that themes which inherit from a parent theme can just overload one file. If the template is not found in either of those, it looks in the theme-compat folder last.
Since
1.0.0
Gamajo_Tech_Loader::get_template_paths() Return a list of paths to check for template locations.
Parameters
string | array $template_names Template file(s) to search for, in order.
bool $load If true the template file will be loaded if it is found.
bool $require_once Whether to require_once or require. Default true. Has no effect if $load is false.
Returns
string The template filename if one is located.
Definition at line 140 of file class-gamajo-template-loader.php.
References get_template_paths().
Referenced by get_template_part().
Field Documentation
$filter_prefix = 'your_plugin' protected
Prefix for filter names.
Since
1.0.0
string
Definition at line 31 of file class-gamajo-template-loader.php.
$plugin_directory = YOUR_PLUGIN_DIR protected
Reference to the root directory path of this plugin.
Can either be a defined constant, or a relative reference from where the subclass lives.
Since
1.0.0
string
Definition at line 51 of file class-gamajo-template-loader.php.
$plugin_template_directory = 'templates' protected
Directory name where templates are found in this plugin.
Can either be a defined constant, or a relative reference from where the subclass lives.
Since
1.1.0
string
Definition at line 62 of file class-gamajo-template-loader.php.
Referenced by get_templates_dir().
$theme_template_directory = 'your-plugin' protected
Directory name where custom templates for this plugin should be found in the theme.
Since
1.0.0
string
Definition at line 40 of file class-gamajo-template-loader.php.
The documentation for this class was generated from the following file:
class-gamajo-template-loader.php