GravityView: GravityView_Edit_Entry_Render Class Reference
GravityView_Edit_Entry_Render Class Reference
Public Member Functions
__construct (GravityView_Edit_Entry $loader)
after_update ()
Perform actions normally performed after updating a lead.
custom_validation ($validation_results)
Make validation work for Edit Entry.
edit_entry_form ()
Display the Edit Entry form.
filter_admin_only_fields ($fields=array(), $edit_fields=null, $form=array(), $view_id=0)
Remove fields that shouldn't be visible based on the Gravity Forms adminOnly field property.
filter_conditional_logic ($form)
Remove the conditional logic rules from the form button and the form fields, if needed.
filter_modify_form_fields ($form, $ajax=false, $field_values= '')
Modify the form fields that are shown when using GFFormDisplay::get_form()
get_field_value ($value, $lead, $field)
Get the posted values from the edit form submission.
gform_pre_validation ($form)
Add field keys that Gravity Forms expects.
init ($gv_data)
Load required files and trigger edit flow.
is_edit_entry ()
Is the current page an Edit Entry page?
is_edit_entry_submission ()
Is the current page an Edit Entry page?
load ()
manage_conditional_logic ($has_conditional_logic, $form)
Disable the Gravity Forms conditional logic script and features on the Edit Entry screen.
maybe_update_post_fields ($form)
Loop through the fields being edited and if they include Post fields, update the Entry's post object.
modify_edit_field_input ($field_content= '', $field, $value, $lead_id=0, $form_id)
Fill-in the saved values into the form inputs.
modify_fileupload_settings ($plupload_init, $form_id, $instance)
Remove max_files validation (done on gravityforms.js) to avoid conflicts with GravityView Late validation done on self::custom_validation.
prevent_maybe_process_form ()
Because we're mimicking being a front-end Gravity Forms form while using a Gravity Forms backend form, we need to prevent them from saving twice.
print_scripts ()
Force Gravity Forms to output scripts as if it were in the admin.
process_save ()
Process edit entry form save.
process_save_process_files ($form_id)
Have GF handle file uploads.
render_form_buttons ()
Display the Update/Cancel/Delete buttons for the Edit Entry form.
setup_vars ()
When Edit entry view is requested setup the vars.
user_can_edit_entry ($echo=false)
Check if the user can edit the entry.
validate ()
Process validation for a edit entry submission.
verify_nonce ()
Is the current nonce valid for editing the entry?
Data Fields
$entry
$form
$form_after_validation = null
$form_id
$is_valid = NULL
$view_id
Static Public Attributes
static $nonce_key
Protected Attributes
$loader
Private Member Functions
check_user_cap_edit_field ($field)
checks if user has permissions to edit a specific field
form_prepare_for_save ()
Unset adminOnly and convert field input key to string.
get_configured_edit_fields ($form, $view_id)
Get the Edit Entry fields as configured in the View.
get_entry ()
TODO: This seems to be hacky...
merge_field_properties ($field, $field_setting)
Override GF Form field properties with the ones defined on the View.
render_edit_form ()
Display the Edit Entry form in the original Gravity Forms format.
user_can_edit_field ($field, $echo=false)
Check whether a field is editable by the current user, and optionally display an error message GravityView_Edit_Entry->check_user_cap_edit_field() Check user capabilities.
Static Private Attributes
static $nonce_field = 'is_gv_edit_entry'
static $supports_product_fields = false
static $supports_save_and_continue = false
Detailed Description
Definition at line 17 of file class-edit-entry-render.php.
Constructor & Destructor Documentation
__construct (GravityView_Edit_Entry $loader)
Definition at line 87 of file class-edit-entry-render.php.
References $loader.
Member Function Documentation
after_update ()
Perform actions normally performed after updating a lead.
Since
1.8
See also
GFEntryDetail::lead_detail_page()
Returns
void
Definition at line 480 of file class-edit-entry-render.php.
References $field.
Referenced by process_save().
check_user_cap_edit_field ($field) private
checks if user has permissions to edit a specific field
Needs to be used combined with GravityView_Edit_Entry::user_can_edit_field for maximum security!!
Parameters
[type] $field [description]
Returns
bool
Definition at line 1487 of file class-edit-entry-render.php.
custom_validation ($validation_results)
Make validation work for Edit Entry.
Because we're calling the GFFormDisplay::validate() in an unusual way (as a front-end form pretending to be a back-end form), validate() doesn't know we can't edit post fields. This goes through all the fields and if they're an invalid post field, we set them as valid. If there are still issues, we'll return false.
Parameters
[type] $validation_results [description]
Returns
[type] [description]
Definition at line 990 of file class-edit-entry-render.php.
References $field, and $value.
edit_entry_form ()
Display the Edit Entry form.
Returns
[type] [description]
Fixes weird wpautop() issue
See also
https://github.com/katzwebservices/GravityView/issues/451
Runs Filter:
gravityview_edit_entry_title Modify the edit entry title
Parameters
string $edit_entry_title Modify the "Edit Entry" title
GravityView_Edit_Entry_Render $this This object
Runs Filter:
gravityview/edit_entry/success Modify the edit entry success message (including the anchor link)
Since
1.5.4
Parameters
string $entry_updated_message Existing message
int $view_id View ID
array $entry Gravity Forms entry array
string $back_link URL to return to the original entry.
Since
1.6
By default, the lead_detail_edit method uses the RGFormsModel::get_lead_field_value() method, which doesn't fill in $_POST values when there is a validation error, because it was designed to work in the admin. We want to use the RGFormsModel::get_field_value() If the form has been submitted, use the values for the fields.
Definition at line 505 of file class-edit-entry-render.php.
References $back_link, GravityView_Edit_Entry\$file, GVCommon\generate_notice(), gravityview_ob_include(), and gravityview_strip_whitespace().
Referenced by init().
filter_admin_only_fields ($fields = array(), $edit_fields = null, $form = array(), $view_id = 0)
Remove fields that shouldn't be visible based on the Gravity Forms adminOnly field property.
Since
1.9.1
Parameters
array|GF_Field[] $fields Gravity Forms form fields
array | null $edit_fields Fields for the Edit Entry tab configured in the View Configuration
array $form GF Form array
int $view_id View ID
Returns
array Possibly modified form array
If the Edit Entry tab is not configured, adminOnly fields will not be shown to non-administrators. If the Edit Entry tab is configured, adminOnly fields will be shown to non-administrators, using the configured GV permissions
Since
1.9.1
Parameters
boolean $use_gf_adminonly_setting True: Hide field if set to Admin Only in GF and the user is not an admin. False: show field based on GV permissions, ignoring GF permissions.
array $form GF Form array
int $view_id View ID
Definition at line 1296 of file class-edit-entry-render.php.
filter_conditional_logic ($form)
Remove the conditional logic rules from the form button and the form fields, if needed.
Since
1.9
Parameters
$form
Returns
mixed
Definition at line 1331 of file class-edit-entry-render.php.
filter_modify_form_fields ($form, $ajax = false, $field_values = '')
Modify the form fields that are shown when using GFFormDisplay::get_form()
By default, all fields will be shown. We only want the Edit Tab configured fields to be shown.
Parameters
array $form
boolean $ajax Whether in AJAX mode
array | string $field_values Passed parameters to the form
Since
1.9
Returns
array Modified form array
Definition at line 663 of file class-edit-entry-render.php.
form_prepare_for_save () private
Unset adminOnly and convert field input key to string.
Returns
array $form
Definition at line 325 of file class-edit-entry-render.php.
References $field, and $form.
Referenced by process_save().
get_configured_edit_fields ($form, $view_id) private
Get the Edit Entry fields as configured in the View.
Since
1.8
Parameters
int $view_id
Returns
array Array of fields that are configured in the Edit tab in the Admin
Definition at line 1143 of file class-edit-entry-render.php.
References GravityView_View_Data\getInstance().
get_entry () private
TODO: This seems to be hacky...
we should remove it. Entry is set when updating the form using setup_vars()! Get the current entry and set it if it's not yet set.
Returns
array Gravity Forms entry array
Definition at line 1120 of file class-edit-entry-render.php.
References gravityview_get_entry(), and GravityView_frontend\is_single_entry().
get_field_value ($value, $lead, $field)
Get the posted values from the edit form submission.
GFFormsModel::get_field_value()
Parameters
mixed $value Existing field value, before edit
array $lead Gravity Forms entry array
array $field Gravity Forms field array
Returns
string [description]
Definition at line 820 of file class-edit-entry-render.php.
References $field, and $value.
gform_pre_validation ($form)
Add field keys that Gravity Forms expects.
See also
GFFormDisplay::validate()
Parameters
array $form GF Form
Returns
array Modified GF Form
this whole fileupload hack is because in the admin, Gravity Forms simply doesn't update any fileupload field if it's empty, but it DOES in the frontend.
What we have to do is set the value so that it doesn't get overwritten as empty on save and appears immediately in the Edit Entry screen again.
Definition at line 842 of file class-edit-entry-render.php.
References $field.
init ($gv_data)
Load required files and trigger edit flow.
Run when the is_edit_entry returns true.
Parameters
GravityView_View_Data $gv_data GravityView Data object
Returns
void
Definition at line 177 of file class-edit-entry-render.php.
References edit_entry_form(), print_scripts(), process_save(), setup_vars(), and user_can_edit_entry().
is_edit_entry ()
Is the current page an Edit Entry page?
Returns
boolean
Definition at line 134 of file class-edit-entry-render.php.
Referenced by modify_fileupload_settings().
is_edit_entry_submission ()
Is the current page an Edit Entry page?
Since
1.9
Returns
boolean
Definition at line 146 of file class-edit-entry-render.php.
Referenced by prevent_maybe_process_form().
load ()
"GRAVITYVIEW_DIR" "../../../"
Definition at line 91 of file class-edit-entry-render.php.
References GRAVITYVIEW_DIR.
manage_conditional_logic ($has_conditional_logic, $form)
Disable the Gravity Forms conditional logic script and features on the Edit Entry screen.
Since
1.9
Parameters
$has_conditional_logic
$form
Returns
mixed|void
Definition at line 1357 of file class-edit-entry-render.php.
maybe_update_post_fields ($form)
Loop through the fields being edited and if they include Post fields, update the Entry's post object.
Parameters
array $form Gravity Forms form
Returns
void
Definition at line 350 of file class-edit-entry-render.php.
References $field, $value, and GVCommon\get_field_array().
Referenced by process_save().
merge_field_properties ($field, $field_setting) private
Override GF Form field properties with the ones defined on the View.
Parameters
GF_Field $field GF Form field object
array $setting GV field options
Since
1.5
Returns
array
Normalize page numbers - avoid conflicts with page validation
Since
1.6
Definition at line 1260 of file class-edit-entry-render.php.
References $field, and gravityview_sanitize_html_class().
modify_edit_field_input ($field_content = '', $field, $value, $lead_id = 0, $form_id)
Fill-in the saved values into the form inputs.
Parameters
string $field_content Always empty.
GF_Field $field
string | array $value If array, it's a field with multiple inputs. If string, single input.
int $lead_id Lead ID. Always 0 for the gform_field_input filter.
int $form_id Form ID
Returns
mixed
See also
GFFormDisplay::get_counter_init_script() need to prevent adminOnly
Allow the pre-populated value to override saved value By default, pre-populate mechanism only kicks on empty fields
Parameters
boolean True: override saved values; False: don't override (default)
$field GF_Field object Gravity Forms field object
Since
1.13
change the field value if needed
Since
1.11
Parameters
mixed $field_value field value used to populate the input
object $field Gravity Forms field object (Class GF_Field)
Unset hack $_GET['page'] = 'gf_entries' We need the fileupload html field to render with the proper id (<li id="field_80_16" ... >)
Definition at line 695 of file class-edit-entry-render.php.
References $field, and $value.
modify_fileupload_settings ($plupload_init, $form_id, $instance)
Remove max_files validation (done on gravityforms.js) to avoid conflicts with GravityView Late validation done on self::custom_validation.
Parameters
$plupload_init array Plupload settings
$form_id
$instance
Returns
mixed
Definition at line 310 of file class-edit-entry-render.php.
References is_edit_entry().
prevent_maybe_process_form ()
Because we're mimicking being a front-end Gravity Forms form while using a Gravity Forms backend form, we need to prevent them from saving twice.
Returns
void
Definition at line 121 of file class-edit-entry-render.php.
References is_edit_entry_submission(), and verify_nonce().
print_scripts ()
Force Gravity Forms to output scripts as if it were in the admin.
Returns
void
Definition at line 207 of file class-edit-entry-render.php.
References $gravityview_view, and GravityView_View\getInstance().
Referenced by init().
process_save ()
Process edit entry form save.
This step is needed to unset the adminOnly from form fields
to avoid the capability validation of the method save_lead for GF 1.9+
Perform an action after the entry has been updated using Edit Entry
Parameters
array $form Gravity Forms form array
string $entry_id Numeric ID of the entry that was updated
Definition at line 222 of file class-edit-entry-render.php.
References after_update(), form_prepare_for_save(), maybe_update_post_fields(), process_save_process_files(), validate(), and verify_nonce().
Referenced by init().
process_save_process_files ($form_id)
Have GF handle file uploads.
Copy of code from GFFormDisplay::process_form()
Parameters
int $form_id
Definition at line 290 of file class-edit-entry-render.php.
References $form_id.
Referenced by process_save().
render_edit_form () private
Display the Edit Entry form in the original Gravity Forms format.
Since
1.9
Parameters
$form
$lead
$view_id
Returns
void
Definition at line 612 of file class-edit-entry-render.php.
References $html.
render_form_buttons ()
Display the Update/Cancel/Delete buttons for the Edit Entry form.
Since
1.8
Returns
string
Definition at line 643 of file class-edit-entry-render.php.
References GravityView_Edit_Entry\$file.
setup_vars ()
When Edit entry view is requested setup the vars.
Definition at line 153 of file class-edit-entry-render.php.
References $entries, $gravityview_view, GravityView_Edit_Entry\get_nonce_key(), and GravityView_View\getInstance().
Referenced by init().
user_can_edit_entry ($echo = false)
Check if the user can edit the entry.
Is the nonce valid?
Does the user have the right caps for the entry
Is the entry in the trash?
Todo:
Move to GVCommon
Parameters
boolean $echo Show error messages in the form?
Returns
boolean True: can edit form. False: nope.
Permalinks are turned off
There are two entries embedded using oEmbed
One of the entries has just been saved
If the Entry is embedded, there may be two entries on the same page. If that's the case, and one is being edited, the other should fail gracefully and not display an error.
Since
1.9
Definition at line 1382 of file class-edit-entry-render.php.
References GravityView_Edit_Entry\check_user_cap_edit_entry(), GVCommon\generate_notice(), GravityView_oEmbed\getInstance(), and gravityview_get_link().
Referenced by init().
user_can_edit_field ($field, $echo = false) private
Check whether a field is editable by the current user, and optionally display an error message GravityView_Edit_Entry->check_user_cap_edit_field() Check user capabilities.
Parameters
array $field Field or field settings array
boolean $echo Whether to show error message telling user they aren't allowed
Returns
boolean True: user can edit the current field; False: nope, they can't.
Definition at line 1455 of file class-edit-entry-render.php.
References GVCommon\generate_notice().
validate ()
Process validation for a edit entry submission.
Sets the is_valid object var
Returns
void
For some crazy reason, Gravity Forms doesn't validate Edit Entry form submissions. You can enter whatever you want! We try validating, and customize the results using self::custom_validation()
Definition at line 948 of file class-edit-entry-render.php.
Referenced by process_save().
verify_nonce ()
Is the current nonce valid for editing the entry?
Returns
boolean
Override nonce validation
Since
1.13
Parameters
int | boolean $valid False if invalid; 1 or 2 when nonce was generated
string $nonce_field Key used when validating submissions. Default: is_gv_edit_entry
Definition at line 1509 of file class-edit-entry-render.php.
Referenced by prevent_maybe_process_form(), and process_save().
Field Documentation
$entry
Definition at line 49 of file class-edit-entry-render.php.
$form
Definition at line 56 of file class-edit-entry-render.php.
Referenced by form_prepare_for_save().
$form_after_validation = null
Definition at line 63 of file class-edit-entry-render.php.
$form_id
Definition at line 70 of file class-edit-entry-render.php.
Referenced by process_save_process_files().
$is_valid = NULL
Definition at line 85 of file class-edit-entry-render.php.
$loader protected
Definition at line 19 of file class-edit-entry-render.php.
Referenced by __construct().
$nonce_field = 'is_gv_edit_entry' static private
Definition at line 30 of file class-edit-entry-render.php.
$nonce_key static
Definition at line 24 of file class-edit-entry-render.php.
$supports_product_fields = false static private
Definition at line 42 of file class-edit-entry-render.php.
$supports_save_and_continue = false static private
Definition at line 36 of file class-edit-entry-render.php.
$view_id
Definition at line 77 of file class-edit-entry-render.php.
The documentation for this class was generated from the following file:
class-edit-entry-render.php