GravityView: WXR_Parser_Regex Class Reference
WXR_Parser_Regex Class Reference
WXR Parser that uses regular expressions.
Public Member Functions
__construct ()
_normalize_tag ($matches)
fclose ($fp)
feof ($fp)
fgets ($fp, $len=8192)
fopen ($filename, $mode= 'r')
get_tag ($string, $tag)
parse ($file)
process_author ($a)
process_category ($c)
process_post ($post)
process_tag ($t)
process_term ($t)
Data Fields
$authors = array()
$base_url = ''
$categories = array()
$posts = array()
$tags = array()
$terms = array()
Detailed Description
WXR Parser that uses regular expressions.
Fallback for installs without an XML parser.
Definition at line 396 of file parsers.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 409 of file parsers.php.
Member Function Documentation
_normalize_tag ($matches)
Definition at line 638 of file parsers.php.
fclose ($fp)
Definition at line 660 of file parsers.php.
Referenced by parse().
feof ($fp)
Definition at line 648 of file parsers.php.
Referenced by parse().
fgets ($fp, $len = 8192)
Definition at line 654 of file parsers.php.
Referenced by parse().
fopen ($filename, $mode = 'r')
Definition at line 642 of file parsers.php.
Referenced by parse().
get_tag ($string, $tag)
Definition at line 482 of file parsers.php.
Referenced by process_author(), process_category(), process_post(), process_tag(), and process_term().
parse ($file)
Definition at line 413 of file parsers.php.
References $post, $url, fclose(), feof(), fgets(), fopen(), process_author(), process_category(), process_post(), process_tag(), and process_term().
Referenced by WXR_Parser\parse().
process_author ($a)
Definition at line 533 of file parsers.php.
References get_tag().
Referenced by parse().
process_category ($c)
Definition at line 503 of file parsers.php.
References get_tag().
Referenced by parse().
process_post ($post)
Definition at line 544 of file parsers.php.
References $post, and get_tag().
Referenced by parse().
process_tag ($t)
Definition at line 513 of file parsers.php.
References get_tag().
Referenced by parse().
process_term ($t)
Definition at line 522 of file parsers.php.
References get_tag().
Referenced by parse().
Field Documentation
$authors = array()
Definition at line 397 of file parsers.php.
$base_url = ''
Definition at line 402 of file parsers.php.
$categories = array()
Definition at line 399 of file parsers.php.
$posts = array()
Definition at line 398 of file parsers.php.
$tags = array()
Definition at line 400 of file parsers.php.
$terms = array()
Definition at line 401 of file parsers.php.
The documentation for this class was generated from the following file:
parsers.php