GravityView: other_entries.php File Reference
other_entries.php File Reference
Namespaces
GravityView
GPL2+
Variables
$created_by = rgar($field['entry'], 'created_by')
$criteria ['paging']
Modify the search parameters before the entries are fetched.
$criteria ['search_criteria']
$criteria ['search_criteria']['status'] = apply_filters('gravityview_status', 'active', $view_settings)
$deprecated = apply_filters('gravityview/field/other_entries/args', array(), $field)
$entries = GVCommon::get_entries($form_id, $criteria)
$field = $gravityview_view->getCurrentField()
if(empty($created_by)) $form_id = $gravityview_view->getFormId()
$gravityview_view = GravityView_View::getInstance()
if(empty($entries)&&$gravityview_view->getCurrentFieldSetting('no_entries_hide')) $list
$view_settings = gravityview_get_template_settings($gravityview_view->getViewId())
$view_settings ['page_size'] = $gravityview_view->getCurrentFieldSetting('page_size')
Variable Documentation
$created_by = rgar($field['entry'], 'created_by')
Definition at line 13 of file other_entries.php.
Referenced by GravityView_Change_Entry_Creator\update_entry_creator().
$criteria
Initial value:
= array(
    'offset' => 0,
    'page_size' => $view_settings['page_size']
)
Modify the search parameters before the entries are fetched.
Since
1.11
Parameters
array $criteria Gravity Forms search criteria array, as used by GVCommon::get_entries()
array $view_settings Associative array of settings with plugin defaults used if not set by the View
int $form_id The Gravity Forms ID
Definition at line 28 of file other_entries.php.
Referenced by GVCommon\calculate_get_entries_criteria(), GVCommon\check_entry_display(), GravityView_Recent_Entries_Widget\get_entries(), and GVCommon\get_entries().
$criteria['search_criteria']
Initial value:
= array(
    'field_filters' => array(
        array(
            'key' => 'created_by',
            'value' => $created_by,
            'operator' => 'is'
        )
    )
)
Definition at line 34 of file other_entries.php.
$criteria['search_criteria']['status'] = apply_filters('gravityview_status', 'active', $view_settings)
Definition at line 44 of file other_entries.php.
$deprecated = apply_filters('gravityview/field/other_entries/args', array(), $field)
Since
1.7.6
Deprecated:
since 1.11
Definition at line 81 of file other_entries.php.
$entries = GVCommon::get_entries($form_id, $criteria)
Definition at line 57 of file other_entries.php.
Referenced by GVCommon\get_entries(), GravityView_Delete_Entry_Shortcode\get_entry(), GravityView_Edit_Entry_Shortcode\get_entry(), GravityView_Admin_ApproveEntries\process_bulk_action(), GravityView_Edit_Entry_Render\setup_vars(), and GravityView_Admin_ApproveEntries\update_bulk().
$field = $gravityview_view->getCurrentField()
Definition at line 11 of file other_entries.php.
if (empty($created_by)) $form_id = $gravityview_view->getFormId()
Definition at line 20 of file other_entries.php.
Referenced by GravityView_frontend\_override_sorting_id_by_field_type(), GravityView_Admin_Views\add_connected_form_column_content(), GravityView_GF_Entries_List\add_edit_link(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_View_Data\add_view(), GravityView_Recent_Entries_Widget\ajax_get_view_merge_tag_data(), GravityView_Cache\delete(), GravityView_API\field_class(), GravityView_API\field_html_attr_id(), GravityView_Admin_Views\get_connected_form_links(), GVCommon\get_connected_views(), GravityView_Recent_Entries_Widget\get_entries(), GravityView_Delete_Entry_Shortcode\get_entry(), GravityView_Edit_Entry_Shortcode\get_entry(), GVCommon\get_entry_ids(), GVCommon\get_entry_meta(), GVCommon\get_form(), GravityView_Edit_Entry\get_nonce_key(), GravityView_frontend\get_search_criteria(), GravityView_Migrate\get_search_fields(), gravityview_get_connected_views(), gravityview_get_entry_ids(), gravityview_get_entry_meta(), gravityview_get_form(), GravityView_Cache\in_blacklist(), GravityView_Admin_ApproveEntries\process_bulk_action(), GravityView_Widget_Search\render_searchable_fields(), GravityView_Admin_Views\save_postdata(), GravityView_Delete_Entry_Shortcode\shortcode(), GravityView_Edit_Entry_Shortcode\shortcode(), GravityView_Admin_ApproveEntries\show_approve_entry_column(), GravityView_Admin_ApproveEntries\update_bulk(), and GravityView_frontend\updateViewSorting().
$gravityview_view = GravityView_View::getInstance()
Definition at line 9 of file other_entries.php.
if (empty($entries)&&$gravityview_view->getCurrentFieldSetting('no_entries_hide')) $list
Initial value:
= new GravityView_Entry_List(
    $entries,
    $gravityview_view->getPostId(),
    $field['form'],
    $gravityview_view->getCurrentFieldSetting('link_format'),
    $gravityview_view->getCurrentFieldSetting('after_link'),
    'other_entries'
)
Definition at line 65 of file other_entries.php.
$view_settings = gravityview_get_template_settings($gravityview_view->getViewId())
Definition at line 23 of file other_entries.php.
Referenced by GravityView_View_Data\add_view(), and GravityView_Recent_Entries_Widget\get_entries().
$view_settings['page_size'] = $gravityview_view->getCurrentFieldSetting('page_size')
Definition at line 25 of file other_entries.php.